from .util import MAXIMUM_PROTOBUF as MAXIMUM_PROTOBUF, find_by_name as find_by_name
from _typeshed import Incomplete

logger: Incomplete

class ONNXModel:
    node_name_counter: Incomplete
    def __init__(self, model, **kwargs) -> None: ...
    def check_is_large_model(self) -> None: ...
    @property
    def is_large_model(self): ...
    @property
    def model_path(self): ...
    @model_path.setter
    def model_path(self, path) -> None: ...
    def framework(self): ...
    @property
    def q_config(self): ...
    @q_config.setter
    def q_config(self, q_config) -> None: ...
    @property
    def hf_config(self): ...
    @property
    def model(self): ...
    @model.setter
    def model(self, model) -> None: ...
    def input(self): ...
    def output(self): ...
    def update(self) -> None: ...
    @property
    def graph_info(self): ...
    def save(self, root) -> None: ...
    def nodes(self): ...
    def initializer(self): ...
    def graph(self): ...
    def ir_version(self): ...
    def opset_import(self): ...
    def remove_node(self, node) -> None: ...
    def remove_nodes(self, nodes_to_remove) -> None: ...
    def add_node(self, node) -> None: ...
    def add_nodes(self, nodes_to_add) -> None: ...
    def add_initializer(self, tensor) -> None: ...
    def add_initializers(self, tensors) -> None: ...
    def get_initializer(self, name): ...
    def get_initializer_share_num(self, name): ...
    def get_node(self, name): ...
    def remove_initializer(self, tensor) -> None: ...
    def remove_initializers(self, init_to_remove) -> None: ...
    def set_initializer(self, tensor, array, raw: bool = False) -> None: ...
    @property
    def input_name_to_nodes(self): ...
    @property
    def output_name_to_node(self): ...
    def get_siblings(self, node): ...
    def get_children(self, node, input_name_to_nodes=None): ...
    def get_parents(self, node, output_name_to_node=None): ...
    def get_parent(self, node, idx, output_name_to_node=None): ...
    def find_node_by_name(self, node_name, new_nodes_list, graph): ...
    def find_nodes_by_initializer(self, graph, initializer): ...
    def get_scale_zero(self, tensor): ...
    def save_model_to_file(self, output_path, use_external_data_format: bool = False) -> None: ...
    @staticmethod
    def replace_node_input(node, old_input_name, new_input_name) -> None: ...
    def replace_input_of_all_nodes(self, old_input_name, new_input_name, white_optype=None, black_optype=None) -> None: ...
    @staticmethod
    def replace_node_output(node, old_output_name, new_output_name) -> None: ...
    def replace_output_of_all_nodes(self, old_output_name, new_output_name, white_optype=None, black_optype=None) -> None: ...
    def remove_unused_nodes(self) -> None: ...
    def topological_sort(self, enable_subgraph: bool = False) -> None: ...
    def get_nodes_chain(self, start, stop, result_chain=None): ...
    def find_split_node_for_layer_wise_quantization(self): ...
    def find_qkv_in_attention(self, find_all: bool = False): ...
    def find_ffn_matmul(self, attention_index, attention_matmul_list, block_len): ...
    def export(self, save_path, conf) -> None: ...
    def add_tensors_to_outputs(self, tensor_names) -> None: ...
    def remove_tensors_from_outputs(self, tensor_names) -> None: ...
    def match_first_parent(self, node, parent_op_type, output_name_to_node, exclude=None): ...
    def match_parent(self, node, parent_op_type, input_index=None, output_name_to_node=None, exclude=None, return_indice=None): ...
    def match_parent_path(self, node, parent_op_types, parent_input_index, output_name_to_node=None, return_indice=None): ...
    def is_smoothquant_model(self): ...
    def find_split_nodes(self): ...
    def split_model_with_node(self, split_node_name, path_of_model_to_split, shape_infer: bool = True, save_both_split_models: bool = True): ...
    def remove_unused_init(self) -> None: ...
    def load_model_initializer_by_tensor(self, data_path=None) -> None: ...
    def write_external_data_to_new_location(self, external_data_location: str = 'external.data', overwrite: bool = False) -> None: ...
    def merge_split_models(self, to_merge_model) -> None: ...
    def re_org_output(self, origin_output) -> None: ...
