from .onnx_model import ONNXModel as ONNXModel
from .util import simple_progress_bar as simple_progress_bar
from _typeshed import Incomplete

logger: Incomplete

def make_matmul_weight_only_node(node, weight_shape, num_bits, group_size, k_blocks, q_weight, scale, zero_point, accuracy_level: int = 0): ...
def quant_tensor(data, num_bits: int = 4, group_size: int = 32, scheme: str = 'asym', dtype: str = 'int', ratio: float = 1.0): ...
def quant_tensor_k_quant_cpu(data, num_bits: int = 4, group_size: int = 32): ...
def quant_tensor_k_quant_cuda(data, num_bits: int = 4, group_size: int = 32): ...
def qdq_tensor(data, num_bits: int = 4, group_size: int = 32, scheme: str = 'asym', dtype: str = 'int', ratio: float = 1.0): ...
def pad_tensor(weight, group_size, k_blocks): ...
def rtn_quantize(model, weight_config={}, num_bits: int = 4, group_size: int = 32, scheme: str = 'asym', ratios={}, accuracy_level: int = 0, providers=['CPUExecutionProvider'], algorithm: str = 'k_quant'): ...
def get_weight_scale(weight, group_size): ...
def prepare_inputs(model, n_samples, dataloader, providers): ...
def gptq(W, H, num_bits: int = 4, group_size: int = 32, scheme: str = 'asym', blocksize: int = 128, percdamp: float = 0.01, actorder: bool = False, mse: bool = False, perchannel: bool = True): ...
def gptq_quantize(model, dataloader, weight_config={}, num_bits: int = 4, group_size: int = 32, scheme: str = 'asym', n_samples: int = 128, percdamp: float = 0.01, blocksize: int = 128, actorder: bool = False, mse: bool = False, perchannel: bool = True, accuracy_level: int = 0, providers=['CPUExecutionProvider']): ...
