import abc
import ort_flatbuffers_py.fbs as fbs
from .types import FbsTypeInfo as FbsTypeInfo, value_name_to_typestr as value_name_to_typestr
from _typeshed import Incomplete
from abc import ABC, abstractmethod

class TypeUsageProcessor(ABC, metaclass=abc.ABCMeta):
    domain: Incomplete
    optype: Incomplete
    name: Incomplete
    def __init__(self, domain: str, optype: str) -> None: ...
    @abstractmethod
    def process_node(self, node: fbs.Node, value_name_to_typeinfo: dict): ...
    def is_typed_registration_needed(self, type_in_registration: str, globally_allowed_types: set[str] | None): ...
    def get_cpp_entry(self): ...
    @abstractmethod
    def to_config_entry(self): ...
    @abstractmethod
    def from_config_entry(self, entry: str): ...

class DefaultTypeUsageProcessor(TypeUsageProcessor):
    def __init__(self, domain: str, optype: str, inputs: [int] = [0], outputs: [int] = [], required_input_types: dict[int, set[str]] = {}, required_output_types: dict[int, set[str]] = {}) -> None: ...
    def is_input_type_enabled(self, reg_type, index, allowed_type_set=None): ...
    def is_output_type_enabled(self, reg_type, index, allowed_type_set=None): ...
    def process_node(self, node: fbs.Node, value_name_to_typeinfo: dict): ...
    def is_typed_registration_needed(self, type_in_registration: str, globally_allowed_types: set[str] | None): ...
    def get_cpp_entry(self): ...
    def to_config_entry(self): ...
    def from_config_entry(self, entry: str): ...

class Input1TypedRegistrationProcessor(DefaultTypeUsageProcessor):
    def __init__(self, domain: str, optype: str) -> None: ...
    def is_typed_registration_needed(self, type_in_registration: str, globally_allowed_types: set[str] | None): ...

class Output0TypedRegistrationProcessor(DefaultTypeUsageProcessor):
    def __init__(self, domain: str, optype: str) -> None: ...
    def is_typed_registration_needed(self, type_in_registration: str, globally_allowed_types: set[str] | None): ...

class OneHotProcessor(TypeUsageProcessor):
    def __init__(self) -> None: ...
    def process_node(self, node: fbs.Node, value_name_to_typeinfo: dict): ...
    def is_typed_registration_needed(self, type_in_registration: str, globally_allowed_types: set[str] | None): ...
    def to_config_entry(self): ...
    def from_config_entry(self, entry: str): ...

class OpTypeImplFilterInterface(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def is_typed_registration_needed(self, domain: str, optype: str, type_registration_str: str): ...
    @abstractmethod
    def get_cpp_entries(self): ...

class OperatorTypeUsageManager:
    def __init__(self) -> None: ...
    def process_node(self, node: fbs.Node, value_name_to_typeinfo: dict): ...
    def get_config_entry(self, domain: str, optype: str): ...
    def restore_from_config_entry(self, domain: str, optype: str, config_entry: str): ...
    def debug_dump(self) -> None: ...
    class _OpTypeImplFilter(OpTypeImplFilterInterface):
        def __init__(self, manager) -> None: ...
        def is_typed_registration_needed(self, domain: str, optype: str, type_registration_str: str): ...
        def get_cpp_entries(self): ...
    def make_op_type_impl_filter(self): ...

class GloballyAllowedTypesOpTypeImplFilter(OpTypeImplFilterInterface):
    def __init__(self, globally_allowed_types: set[str]) -> None: ...
    def is_typed_registration_needed(self, domain: str, optype: str, type_registration_str: str): ...
    def get_cpp_entries(self): ...
    def global_type_list(self): ...
