from .operator_type_usage_processors import OperatorTypeUsageManager as OperatorTypeUsageManager

class OrtFormatModelProcessor:
    def __init__(self, model_path: str, required_ops: dict, processors: OperatorTypeUsageManager) -> None: ...
    def process(self) -> None: ...
