import onnx
from .calibrate import TensorData as TensorData
from .onnx_model import ONNXModel as ONNXModel
from .quant_utils import DEQUANT_OP_NAME as DEQUANT_OP_NAME, ONNX_TYPE_TO_NP_TYPE as ONNX_TYPE_TO_NP_TYPE, QUANT_OP_NAME as QUANT_OP_NAME, TENSOR_NAME_QUANT_SUFFIX as TENSOR_NAME_QUANT_SUFFIX, find_by_name as find_by_name, get_opset_version as get_opset_version, model_has_infer_metadata as model_has_infer_metadata, normalize_axis as normalize_axis, pack_bytes_to_4bit as pack_bytes_to_4bit, quantize_data as quantize_data, quantize_nparray as quantize_nparray, save_and_reload_model_with_shape_infer as save_and_reload_model_with_shape_infer, tensor_proto_to_array as tensor_proto_to_array
from .tensor_quant_overrides import TensorQuantOverridesHelper as TensorQuantOverridesHelper
from _typeshed import Incomplete
from typing import Any

class QuantizationParams:
    data: Incomplete
    def __init__(self, **data: dict[str, Any]) -> None: ...
    def get(self, key, default_value=None): ...
    def __iter__(self): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __len__(self) -> int: ...

class BaseQuantizer:
    value_infos: Incomplete
    model: Incomplete
    opset_version: Incomplete
    per_channel: Incomplete
    reduce_range: Incomplete
    extra_options: Incomplete
    enable_subgraph_quantization: Incomplete
    parent: Incomplete
    force_quantize_no_input_check: Incomplete
    is_activation_symmetric: Incomplete
    min_real_range: Incomplete
    activation_qType: Incomplete
    weight_qType: Incomplete
    tensors_range: Incomplete
    nodes_to_quantize: Incomplete
    nodes_to_exclude: Incomplete
    op_types_to_quantize: Incomplete
    tensor_quant_overrides: Incomplete
    initializers: Incomplete
    tensor_quant_override_qtypes: Incomplete
    def __init__(self, model, per_channel, reduce_range, weight_qType, activation_qType, tensors_range, nodes_to_quantize, nodes_to_exclude, op_types_to_quantize, extra_options=None) -> None: ...
    def is_weight_symmetric(self, weight_quant_type: onnx.TensorProto.DataType) -> bool: ...
    def quantize_model(self) -> None: ...
    def is_input_a_initializer(self, input_name): ...
    def is_per_channel(self): ...
    def is_valid_quantize_weight(self, weight_name): ...
    def should_quantize_node(self, node): ...
    def quantize_bias_static_impl(self, bias_name, input_scale, weight_scale, beta: float = 1.0): ...
    def quantize_initializer_impl(self, weight, qType, reduce_range: bool = False, keep_float_weight: bool = False): ...
    def quantize_weight_per_channel_impl(self, weight_name, weight_qType, channel_axis, reduce_range: bool = True, keep_float_weight: bool = False): ...
    def adjust_tensor_ranges(self) -> None: ...
