import abc
import numpy as np
from .quant_utils import apply_plot as apply_plot, load_model_with_shape_infer as load_model_with_shape_infer, smooth_distribution as smooth_distribution
from _typeshed import Incomplete
from collections.abc import Sequence
from enum import Enum
from onnx import ModelProto as ModelProto
from pathlib import Path

def rel_entr(pk: np.ndarray, qk: np.ndarray) -> np.ndarray: ...
def entropy(pk: np.ndarray, qk: np.ndarray, base: float | None = None, axis: int = 0) -> np.ndarray: ...

class TensorData:
    def __init__(self, **kwargs) -> None: ...
    @property
    def range_value(self): ...
    @property
    def avg_std(self): ...
    def to_dict(self): ...

class TensorsData:
    calibration_method: Incomplete
    data: Incomplete
    def __init__(self, calibration_method, data: dict[str, TensorData | tuple]) -> None: ...
    def __iter__(self): ...
    def __contains__(self, key) -> bool: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def keys(self): ...
    def values(self): ...
    def items(self): ...
    def to_dict(self): ...

class CalibrationMethod(Enum):
    MinMax = 0
    Entropy = 1
    Percentile = 2
    Distribution = 3

class CalibrationDataReader(metaclass=abc.ABCMeta):
    @classmethod
    def __subclasshook__(cls, subclass): ...
    @abc.abstractmethod
    def get_next(self) -> dict: ...
    def __iter__(self): ...
    def __next__(self): ...
    def __len__(self) -> int: ...
    def set_range(self, start_index: int, end_index: int): ...

class CalibraterBase:
    model: Incomplete
    op_types_to_calibrate: Incomplete
    augmented_model_path: Incomplete
    symmetric: Incomplete
    use_external_data_format: Incomplete
    per_channel: Incomplete
    augment_model: Incomplete
    infer_session: Incomplete
    execution_providers: Incomplete
    def __init__(self, model_path: str | Path, op_types_to_calibrate: Sequence[str] | None = None, augmented_model_path: str = 'augmented_model.onnx', symmetric: bool = False, use_external_data_format: bool = False, per_channel: bool = False) -> None: ...
    def set_execution_providers(self, execution_providers=['CPUExecutionProvider']) -> None: ...
    def create_inference_session(self) -> None: ...
    def select_tensors_to_calibrate(self, model: ModelProto): ...
    def get_augment_model(self): ...
    def augment_graph(self) -> None: ...
    def collect_data(self, data_reader: CalibrationDataReader): ...
    def compute_data(self) -> TensorsData: ...

class MinMaxCalibrater(CalibraterBase):
    intermediate_outputs: Incomplete
    calibrate_tensors_range: Incomplete
    num_model_outputs: Incomplete
    model_original_outputs: Incomplete
    moving_average: Incomplete
    averaging_constant: Incomplete
    max_intermediate_outputs: Incomplete
    def __init__(self, model_path: str | Path, op_types_to_calibrate: Sequence[str] | None = None, augmented_model_path: str = 'augmented_model.onnx', symmetric: bool = False, use_external_data_format: bool = False, moving_average: bool = False, averaging_constant: float = 0.01, max_intermediate_outputs=None, per_channel: bool = False) -> None: ...
    def augment_graph(self): ...
    def clear_collected_data(self) -> None: ...
    def collect_data(self, data_reader: CalibrationDataReader): ...
    def merge_range(self, old_range, new_range): ...
    def compute_data(self) -> TensorsData: ...

class HistogramCalibrater(CalibraterBase):
    intermediate_outputs: Incomplete
    calibrate_tensors_range: Incomplete
    num_model_outputs: Incomplete
    model_original_outputs: Incomplete
    collector: Incomplete
    method: Incomplete
    num_bins: Incomplete
    num_quantized_bins: Incomplete
    percentile: Incomplete
    tensors_to_calibrate: Incomplete
    scenario: Incomplete
    def __init__(self, model_path: str | Path, op_types_to_calibrate: Sequence[str] | None = None, augmented_model_path: str = 'augmented_model.onnx', use_external_data_format: bool = False, method: str = 'percentile', symmetric: bool = False, num_bins: int = 128, num_quantized_bins: int = 2048, percentile: float = 99.999, scenario: str = 'same') -> None: ...
    def augment_graph(self) -> None: ...
    def clear_collected_data(self) -> None: ...
    def collect_data(self, data_reader: CalibrationDataReader): ...
    def compute_data(self) -> TensorsData: ...

class EntropyCalibrater(HistogramCalibrater):
    def __init__(self, model_path: str | Path, op_types_to_calibrate: Sequence[str] | None = None, augmented_model_path: str = 'augmented_model.onnx', use_external_data_format: bool = False, method: str = 'entropy', symmetric: bool = False, num_bins: int = 128, num_quantized_bins: int = 128) -> None: ...

class PercentileCalibrater(HistogramCalibrater):
    def __init__(self, model_path: str | Path, op_types_to_calibrate: Sequence[str] | None = None, augmented_model_path: str = 'augmented_model.onnx', use_external_data_format: bool = False, method: str = 'percentile', symmetric: bool = False, num_bins: int = 2048, percentile: float = 99.999) -> None: ...

class DistributionCalibrater(HistogramCalibrater):
    def __init__(self, model_path: str | Path, op_types_to_calibrate: Sequence[str] | None = None, augmented_model_path: str = 'augmented_model.onnx', use_external_data_format: bool = False, method: str = 'distribution', num_bins: int = 128, scenario: str = 'same') -> None: ...

class CalibrationDataCollector(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def collect(self, name_to_arr): ...
    @abc.abstractmethod
    def compute_collection_result(self): ...

class HistogramCollector(CalibrationDataCollector):
    histogram_dict: Incomplete
    method: Incomplete
    symmetric: Incomplete
    num_bins: Incomplete
    num_quantized_bins: Incomplete
    percentile: Incomplete
    scenario: Incomplete
    def __init__(self, method, symmetric, num_bins, num_quantized_bins, percentile, scenario) -> None: ...
    def get_histogram_dict(self): ...
    def collect(self, name_to_arr): ...
    def collect_absolute_value(self, name_to_arr) -> None: ...
    def collect_value(self, name_to_arr) -> None: ...
    def merge_histogram(self, old_histogram, data_arr, new_min, new_max, new_threshold): ...
    def compute_collection_result(self): ...
    def compute_percentile(self): ...
    def compute_entropy(self): ...
    def compute_distribution(self): ...
    def get_entropy_threshold(self, histogram, num_quantized_bins): ...

def create_calibrator(model: str | Path, op_types_to_calibrate: Sequence[str] | None = None, augmented_model_path: str = 'augmented_model.onnx', calibrate_method=..., use_external_data_format: bool = False, providers=None, extra_options={}): ...
