from .base_quantizer import BaseQuantizer as BaseQuantizer, QuantizationParams as QuantizationParams
from .calibrate import TensorData as TensorData
from .onnx_model import ONNXModel as ONNXModel
from .quant_utils import QuantizationMode as QuantizationMode, QuantizedValue as QuantizedValue, QuantizedValueType as QuantizedValueType, TENSOR_NAME_QUANT_SUFFIX as TENSOR_NAME_QUANT_SUFFIX, __producer__ as __producer__, __version__ as __version__, add_infer_metadata as add_infer_metadata, attribute_to_kwarg as attribute_to_kwarg, compute_scale_zp as compute_scale_zp, compute_scale_zp_float8 as compute_scale_zp_float8, find_by_name as find_by_name, get_qmin_qmax_for_qType as get_qmin_qmax_for_qType, get_qrange_for_qType as get_qrange_for_qType, ms_domain as ms_domain, quantize_onnx_initializer as quantize_onnx_initializer, save_and_reload_model_with_shape_infer as save_and_reload_model_with_shape_infer, tensor_proto_to_array as tensor_proto_to_array
from .registry import CreateOpQuantizer as CreateOpQuantizer
from _typeshed import Incomplete

class ONNXQuantizer(BaseQuantizer):
    value_infos: Incomplete
    model: Incomplete
    mode: Incomplete
    static: Incomplete
    fuse_dynamic_quant: Incomplete
    q_matmul_const_b_only: Incomplete
    new_nodes: Incomplete
    graph_scope: str
    tensor_names: Incomplete
    quantization_params: Incomplete
    fixed_qrange_uint8_name: str
    fixed_qrange_int8_name: str
    fixed_zero_name: str
    fixed_zero_zp_name: str
    quantized_value_map: Incomplete
    generated_value_names: Incomplete
    def __init__(self, model, per_channel, reduce_range, mode, static, weight_qType, activation_qType, tensors_range, nodes_to_quantize, nodes_to_exclude, op_types_to_quantize, extra_options=None) -> None: ...
    def quantize_subgraph(self, subgraph, graph_key): ...
    def quantize_node_with_sub_graph(self, node): ...
    def has_QDQ_nodes(self): ...
    def find_initializer_in_path(self, initializer_name): ...
    def add_new_nodes(self, nodes) -> None: ...
    def quantize_model(self): ...
    def get_tensor_type(self, tensor_name, mandatory: bool = False): ...
    def is_float_tensor(self, tensor_name): ...
    def find_quantized_value(self, input_name): ...
    def adjust_single_weight_scale_if_needed(self, bias_val, input_scale, weight_scale, weight_scale_dtype, weight_name, bias_name, qrange, multiplicative_epsilon, idx=None): ...
    def quantize_bias_static(self, bias_name, input_name, weight_name, beta: float = 1.0): ...
    def contains_tensor(self, tensor_name): ...
    def quantize_activation(self, node, indices, from_subgraph: bool = False): ...
    def quantize_weight(self, node, indices, reduce_range: bool = False, op_level_per_channel: bool = False, axis: int = -1, from_subgraph: bool = False): ...
    def quantize_initializer(self, weight, qType, reduce_range: bool = False, keep_float_weight: bool = False): ...
    def quantize_weight_per_channel(self, weight_name, weight_qType, channel_axis, reduce_range: bool = True, keep_float_weight: bool = False): ...
    def calculate_quantization_params(self): ...
