from .quant_utils import attribute_to_kwarg as attribute_to_kwarg, find_by_name as find_by_name
from _typeshed import Incomplete
from onnx.onnx_pb import ModelProto as ModelProto

class ONNXModel:
    model: Incomplete
    def __init__(self, model: ModelProto) -> None: ...
    def nodes(self): ...
    def initializer(self): ...
    def initializer_extend(self, inits) -> None: ...
    def graph(self): ...
    def ir_version(self): ...
    def opset_import(self): ...
    def set_opset_import(self, domain, version) -> None: ...
    def remove_node(self, node) -> None: ...
    def remove_nodes(self, nodes_to_remove) -> None: ...
    def add_node(self, node) -> None: ...
    def add_nodes(self, nodes_to_add) -> None: ...
    def add_initializer(self, tensor) -> None: ...
    def get_initializer(self, name): ...
    def find_graph_input(self, input_name): ...
    def find_graph_output(self, output_name): ...
    def get_tensor_type(self, tensor_name: str): ...
    def get_constant_value(self, output_name): ...
    def get_initializer_name_set(self): ...
    def remove_initializer(self, tensor) -> None: ...
    def remove_initializers(self, init_to_remove) -> None: ...
    def get_non_initializer_inputs(self): ...
    def input_name_to_nodes(self): ...
    def output_name_to_node(self): ...
    def get_children(self, node, input_name_to_nodes=None): ...
    def get_parents(self, node, output_name_to_node=None): ...
    def get_parent(self, node, idx, output_name_to_node=None): ...
    def find_node_by_name(self, node_name, new_nodes_list, graph): ...
    def get_largest_node_name_suffix(self, node_name_prefix): ...
    def get_largest_initializer_name_suffix(self, initializer_name_prefix): ...
    def find_nodes_by_initializer(self, graph, initializer): ...
    def replace_gemm_with_matmul(self) -> None: ...
    def save_model_to_file(self, output_path, use_external_data_format: bool = False) -> None: ...
    @staticmethod
    def replace_node_input(node, old_input_name, new_input_name) -> None: ...
    def replace_input_of_all_nodes(self, old_input_name, new_input_name) -> None: ...
    def replace_input_of_nodes(self, old_input_name, new_input_name, node_names_set) -> None: ...
    @staticmethod
    def replace_node_output(node, old_output_name, new_output_name) -> None: ...
    def replace_output_of_all_nodes(self, old_output_name, new_output_name) -> None: ...
    def replace_output_of_nodes(self, old_output_name, new_output_name, node_names_set) -> None: ...
    def remove_unused_constant(self) -> None: ...
    def is_graph_output(self, output_name): ...
    def is_graph_input(self, tensor_name: str) -> bool: ...
    def topological_sort(self) -> None: ...
    def clean_initializers(self): ...
