import numpy
from .calibrate import CalibraterBase as CalibraterBase, CalibrationDataReader as CalibrationDataReader
from .onnx_model import ONNXModel as ONNXModel
from .quant_utils import DEQUANT_OP_NAME as DEQUANT_OP_NAME, DEQUANT_OUTPUT_SUFFIX as DEQUANT_OUTPUT_SUFFIX, QUANT_INPUT_SUFFIX as QUANT_INPUT_SUFFIX, TENSOR_NAME_QUANT_SUFFIX as TENSOR_NAME_QUANT_SUFFIX, find_by_name as find_by_name, load_model_with_shape_infer as load_model_with_shape_infer
from collections.abc import Callable as Callable, Sequence
from pathlib import Path

def modify_model_output_intermediate_tensors(input_model_path: str | Path, output_model_path: str | Path, op_types_for_saving: Sequence[str] | None = None, save_as_external_data: bool = False) -> None: ...
def collect_activations(augmented_model: str, input_reader: CalibrationDataReader, session_options=None, execution_providers: Sequence[str] | None = None) -> dict[str, list[numpy.ndarray]]: ...
def create_activation_matching(qdq_activations: dict[str, Sequence[numpy.ndarray]], float_activations: dict[str, Sequence[numpy.ndarray]] | None = None) -> dict[str, dict[str, Sequence[numpy.ndarray]]]: ...
def create_weight_matching(float_model_path: str, qdq_model_path: str) -> dict[str, dict[str, numpy.ndarray]]: ...
def compute_signal_to_quantization_noice_ratio(x: Sequence[numpy.ndarray] | numpy.ndarray, y: Sequence[numpy.ndarray] | numpy.ndarray) -> float: ...
def compute_weight_error(weights_match: dict[str, dict[str, numpy.ndarray]], err_func: Callable[[numpy.ndarray, numpy.ndarray], float] = ...) -> dict[str, float]: ...
def compute_activation_error(activations_match: dict[str, dict[str, Sequence[numpy.ndarray]]], err_func: Callable[[Sequence[numpy.ndarray], Sequence[numpy.ndarray]], float] = ...) -> dict[str, dict[str, float]]: ...
