import numpy
import onnx
from _typeshed import Incomplete
from enum import Enum
from onnx import ModelProto as ModelProto, TensorProto
from onnxruntime import GraphOptimizationLevel as GraphOptimizationLevel, InferenceSession as InferenceSession, SessionOptions as SessionOptions
from pathlib import Path

__producer__: str
__version__: str
onnx_domain: str
ms_domain: str
QUANT_OP_NAME: str
QUANT_INPUT_SUFFIX: str
DEQUANT_OP_NAME: str
DEQUANT_OUTPUT_SUFFIX: str
TENSOR_NAME_QUANT_SUFFIX: str
MODEL_SIZE_THRESHOLD: int
FLOAT8_DISTRIBUTIONS: Incomplete
type_to_name: Incomplete

class QuantizationMode(Enum):
    IntegerOps = 0
    QLinearOps = 1
    @staticmethod
    def from_string(mode): ...

class QuantizedValueType(Enum):
    Input = 0
    Initializer = 1
    @staticmethod
    def from_string(v): ...

class QuantType(Enum):
    QInt8 = 0
    QUInt8 = 1
    QFLOAT8E4M3FN = 2
    QInt16 = 3
    QUInt16 = 4
    QInt4 = 5
    QUInt4 = 6
    @staticmethod
    def from_string(t): ...
    @property
    def tensor_type(self): ...

class QuantFormat(Enum):
    QOperator = 0
    QDQ = 1
    @staticmethod
    def from_string(format): ...

ONNX_TYPE_TO_NP_TYPE: Incomplete
ONNX_INT_TYPE_RANGE: Incomplete
ONNX_INT_TYPE_SYMMETRIC_RANGE: Incomplete
ONNX_INT_TYPE_REDUCED_RANGE: Incomplete

def quantize_nparray(qType, arr, scale, zero_point, low=None, high=None): ...
def compute_scale_zp(rmin, rmax, qmin, qmax, symmetric: bool = False, min_real_range=None): ...
def compute_scale_zp_float8(element_type, std): ...
def compute_data_quant_params(data: numpy.ndarray, quant_type: onnx.TensorProto.DataType, symmetric: bool, reduce_range: bool = False, min_real_range: float | None = None, rmin_override: float | None = None, rmax_override: float | None = None) -> tuple[numpy.ndarray, numpy.ndarray]: ...
def quantize_data(data, qType, symmetric, reduce_range: bool = False, min_real_range=None, rmin_override=None, rmax_override=None) -> tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray]: ...
def quantize_onnx_initializer(weight: onnx.TensorProto, quant_type: onnx.TensorProto.DataType, zero_point: numpy.ndarray, scale: numpy.ndarray, axis: int | None = None, quant_weight_name: str | None = None) -> onnx.TensorProto: ...
def get_qmin_qmax_for_qType(qType, reduce_range: bool = False, symmetric: bool = False): ...
def get_qrange_for_qType(qType, reduce_range: bool = False, symmetric: bool = False): ...
def normalize_axis(axis: int, rank: int) -> tuple[bool, int]: ...
def pack_bytes_to_4bit(src_8bit: bytes) -> bytearray: ...

class QuantizedInitializer:
    name: Incomplete
    initializer: Incomplete
    rmins: Incomplete
    rmaxs: Incomplete
    zero_points: Incomplete
    scales: Incomplete
    data: Incomplete
    quantized_data: Incomplete
    axis: Incomplete
    def __init__(self, name, initializer, rmins, rmaxs, zero_points, scales, data=[], quantized_data=[], axis=None) -> None: ...

class QuantizedValue:
    original_name: Incomplete
    q_name: Incomplete
    scale_name: Incomplete
    zp_name: Incomplete
    value_type: Incomplete
    axis: Incomplete
    node_type: Incomplete
    node_qtype: Incomplete
    scale_type: Incomplete
    def __init__(self, name, new_quantized_name, scale_name, zero_point_name, quantized_value_type, axis=None, node_type=None, node_qtype=None, scale_type=None) -> None: ...

class BiasToQuantize:
    bias_name: Incomplete
    input_name: Incomplete
    weight_name: Incomplete
    def __init__(self, bias_name, input_name, weight_name) -> None: ...

def attribute_to_kwarg(attribute): ...
def find_by_name(item_name, item_list): ...
def get_elem_index(elem_name, elem_list): ...
def get_mul_node(inputs, output, name): ...
def generate_identified_filename(filename: Path, identifier: str) -> Path: ...
def apply_plot(hist, hist_edges) -> None: ...
def write_calibration_table(calibration_cache, dir: str = '.'): ...
def smooth_distribution(p, eps: float = 0.0001): ...
def model_has_external_data(model_path: Path): ...
def optimize_model(model_path: Path, opt_model_path: Path): ...
def add_pre_process_metadata(model: ModelProto): ...
def model_has_pre_process_metadata(model: ModelProto) -> bool: ...
def add_infer_metadata(model: ModelProto): ...
def model_has_infer_metadata(model: ModelProto) -> bool: ...
def get_opset_version(model: ModelProto) -> int: ...
def update_opset_version(model: ModelProto, weight_type: QuantType) -> ModelProto: ...
def load_model_with_shape_infer(model_path: Path) -> ModelProto: ...
def save_and_reload_model_with_shape_infer(model: ModelProto) -> ModelProto: ...
def tensor_proto_to_array(initializer: TensorProto) -> numpy.ndarray: ...
def add_quant_suffix(tensor_name: str) -> str: ...
def add_quant_input_suffix(tensor_name: str) -> str: ...
def add_quant_output_suffix(tensor_name) -> str: ...
def add_dequant_suffix(tensor_name) -> str: ...
def add_dequant_input_suffix(tensor_name) -> str: ...
def add_dequant_output_suffix(tensor_name) -> str: ...
