from _typeshed import Incomplete
from onnxruntime.quantization import QuantFormat as QuantFormat, QuantType as QuantType, StaticQuantConfig as StaticQuantConfig, quantize as quantize
from onnxruntime.quantization.calibrate import CalibrationDataReader as CalibrationDataReader, CalibrationMethod as CalibrationMethod

class OnnxModelCalibrationDataReader(CalibrationDataReader):
    model_dir: Incomplete
    calibration_data: Incomplete
    def __init__(self, model_path) -> None: ...
    def get_next(self) -> dict: ...
    def read_onnx_pb_data(self, file_pb): ...

def parse_arguments(): ...
def get_tensor_quant_overrides(file): ...
def main() -> None: ...
