import onnx
from .quant_utils import QuantType as QuantType
from _typeshed import Incomplete
from collections.abc import MutableMapping
from dataclasses import dataclass
from typing import Any

@dataclass
class QuantTypeInfo:
    quant_type: QuantType
    symmetric: bool | None = ...
    reduce_range: bool | None = ...
    axis: int | None = ...
    def __eq__(self, other: object): ...
    @staticmethod
    def load_from_dict(raw_dict: dict[str, Any], default_qtype: QuantType | None = None, default_symmetric: bool | None = None, default_reduce_range: bool | None = None) -> QuantTypeInfo: ...
    def save_to_dict(self, raw_dict: dict[str, Any]): ...

class TensorQuantOverridesHelper(MutableMapping):
    overrides: Incomplete
    quant_types: Incomplete
    keys_unsupported_with_scale_zp: Incomplete
    def __init__(self, raw_overrides: dict[str, list[dict[str, Any]]]) -> None: ...
    def has_per_tensor_overrides(self, tensor_name: str) -> bool: ...
    def has_per_channel_overrides(self, tensor_name: str) -> bool: ...
    def overrides_scale_zp(self, tensor_name: str) -> bool: ...
    def get_per_tensor_overrides(self, tensor_name: str, default_val: dict[str, Any] | None = None) -> dict[str, Any] | None: ...
    def get_per_channel_overrides(self, tensor_name: str, default_val: list[dict[str, Any]] | None = None) -> list[dict[str, Any]] | None: ...
    def get_quant_types(self) -> set[QuantType]: ...
    def is_valid(self, initializers: dict[str, onnx.TensorProto], activation_names: set[str], default_activation_qtype) -> tuple[bool, str | None]: ...
    def update_tensor_overrides(self, tensor_name: str, new_vals: dict[str, Any], channels: list[int] | None = None, overwrite: bool = True) -> bool: ...
    def get_node_output_qtype_info(self, output_name: str, default_qtype: QuantType | None, default_symmetric: bool | None = None) -> QuantTypeInfo: ...
    def get_node_input_qtype_info(self, input_name: str, node_name: str, default_qtype: QuantType | None, default_symmetric: bool | None = None, default_reduce_range: bool | None = None) -> QuantTypeInfo: ...
    def pprint_str(self, indent=None) -> str: ...
    def empty(self) -> bool: ...
    def get_dict(self) -> dict[str, list[dict[str, Any]]]: ...
    def __setitem__(self, key: str, value: list[dict]): ...
    def __getitem__(self, key: str) -> list[dict]: ...
    def __delitem__(self, key: str): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
