import onnx
from ..onnx_model import ONNXModel as ONNXModel

class Fusion:
    search_op_type: str
    fused_op_type: str
    model: ONNXModel
    nodes_to_remove: list
    nodes_to_add: list
    def __init__(self, model: ONNXModel, fused_op_type: str, search_op_type: str) -> None: ...
    def fuse(self, node: onnx.NodeProto, input_name_to_nodes: dict[str, list[onnx.NodeProto]], output_name_to_node: dict[str, onnx.NodeProto]): ...
    def apply(self) -> bool: ...
    def create_unique_node_name(self): ...
    @staticmethod
    def is_safe_to_fuse_nodes(nodes_to_remove: list[onnx.NodeProto], keep_outputs: list[str], input_name_to_nodes: dict[str, list[onnx.NodeProto]], output_name_to_node: dict[str, onnx.NodeProto]) -> bool: ...
    @staticmethod
    def get_node_attribute(node: onnx.NodeProto, attribute_name: str): ...
    @staticmethod
    def input_index(node_output: str, child_node: onnx.NodeProto) -> int: ...
    @staticmethod
    def tensor_shape_to_list(tensor_type) -> list[int]: ...
    def get_constant_input(self, node: onnx.NodeProto): ...
    def find_constant_input(self, node: onnx.NodeProto, expected_value: float, delta: float = 1e-06) -> int: ...
    def has_constant_input(self, node: onnx.NodeProto, expected_value: float, delta: float = 1e-06) -> bool: ...
    def is_constant_with_specified_rank(self, output_name: str, rank: int) -> bool: ...
    def match_first_parent(self, node: onnx.NodeProto, parent_op_type: str, output_name_to_node: dict[str, onnx.NodeProto] | None = None, exclude: list[onnx.NodeProto] = []) -> tuple[onnx.NodeProto | None, int | None]: ...
    def match_parent(self, node: onnx.NodeProto, parent_op_type: str, input_index: int | None = None, output_name_to_node: dict[str, onnx.NodeProto] | None = None, exclude: list[onnx.NodeProto] = [], return_indice: list[int] | None = None) -> onnx.NodeProto | None: ...
    def match_parent_path(self, node: onnx.NodeProto, parent_op_types: list[str], parent_input_index: list[int] | None = None, output_name_to_node: dict[str, onnx.NodeProto] | None = None, return_indice: list[int] | None = None) -> list[onnx.NodeProto] | None: ...
    def match_parent_paths(self, node: onnx.NodeProto, paths: list[tuple[list[str], list[int]]], output_name_to_node: dict[str, onnx.NodeProto]) -> tuple[int, list[onnx.NodeProto] | None, list[int] | None]: ...
    def find_first_child_by_type(self, node: onnx.NodeProto, child_type: str, input_name_to_nodes: dict[str, list[onnx.NodeProto]] | None = None, recursive: bool = True) -> onnx.NodeProto | None: ...
