import onnx
from ..onnx_model import ONNXModel as ONNXModel
from .fusion import Fusion as Fusion

class FusionGelu(Fusion):
    def __init__(self, model: ONNXModel) -> None: ...
    def fuse(self, erf_node: onnx.NodeProto, input_name_to_nodes: dict[str, list[onnx.NodeProto]], output_name_to_node: dict[str, onnx.NodeProto]): ...
    def fuse_1(self, erf_node: onnx.NodeProto, input_name_to_nodes: dict[str, list[onnx.NodeProto]], output_name_to_node: dict[str, onnx.NodeProto]) -> bool: ...
    def fuse_2(self, erf_node: onnx.NodeProto, input_name_to_nodes: dict[str, list[onnx.NodeProto]], output_name_to_node: dict[str, onnx.NodeProto]) -> bool: ...
    def fuse_3(self, erf_node: onnx.NodeProto, input_name_to_nodes: dict[str, list[onnx.NodeProto]], output_name_to_node: dict[str, onnx.NodeProto]) -> bool: ...
