import abc
import numpy as np
import onnx
from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any

class RuntimeTypeError(RuntimeError): ...
class RuntimeContextError(RuntimeError): ...
class RuntimeImplementationError(NotImplementedError): ...
class DefaultNone: ...

class RefAttrName:
    name: Incomplete
    def __init__(self, name: str) -> None: ...

class OnnxType:
    type_proto: Incomplete
    def __init__(self, type_proto: onnx.TypeProto) -> None: ...

class SparseTensor:
    values: Incomplete
    indices: Incomplete
    shape: Incomplete
    def __init__(self, values: np.ndarray, indices: np.ndarray, shape: tuple[int]) -> None: ...
    @property
    def dtype(self) -> Any: ...

def to_sparse_tensor(att: onnx.AttributeProto) -> SparseTensor: ...

class Graph:
    g: Incomplete
    def __init__(self, g: onnx.GraphProto) -> None: ...

class OpRun(abc.ABC, metaclass=abc.ABCMeta):
    op_domain: str
    onnx_node: Incomplete
    run_params: Incomplete
    has_subgraph: bool
    def __init__(self, onnx_node: onnx.NodeProto, run_params: dict[str, Any], schema: Any = None) -> None: ...
    @staticmethod
    def implicit_inputs(graph: onnx.GraphProto) -> list[str]: ...
    @property
    def input(self) -> Sequence[str]: ...
    @property
    def output(self) -> Sequence[str]: ...
    @property
    def op_type(self) -> str: ...
    @property
    def domain(self) -> str: ...
    def need_context(self) -> bool: ...
    def run(self, *args, linked_attributes=None, context=None): ...
    @classmethod
    def infer_name(cls): ...
    @classmethod
    def make_node(cls, n_inputs: int | None = None, n_outputs: int | None = None, **kwargs: Any) -> onnx.NodeProto: ...
    @classmethod
    def create(cls, n_inputs: int | None = None, n_outputs: int | None = None, verbose: int = 0, **kwargs: Any) -> Any: ...
    @classmethod
    def eval(cls, *args: list[Any], n_outputs: int | None = None, verbose: int = 0, **kwargs: Any) -> Any: ...

class OpRunExpand(OpRun):
    def __init__(self, *args, **kwargs) -> None: ...

class OpFunction(OpRun):
    impl_: Incomplete
    attributes_: Incomplete
    def __init__(self, onnx_node: onnx.NodeProto, run_params: dict[str, Any] | None, impl: Any = None, attributes: dict[str, Any] | None = None) -> None: ...

class OpFunctionContextDependant(OpFunction):
    parent: Incomplete
    schema_: Incomplete
    def __init__(self, onnx_node: onnx.NodeProto, run_params: dict[str, Any] | None, parent: Any = None) -> None: ...
