import abc
from _typeshed import Incomplete
from onnx.onnx_pb import NodeProto as NodeProto
from onnx.reference.op_run import OpRun as OpRun, RuntimeTypeError as RuntimeTypeError
from typing import Any

class OpRunUnary(OpRun, metaclass=abc.ABCMeta):
    def run(self, x): ...

class OpRunUnaryNum(OpRunUnary, metaclass=abc.ABCMeta):
    def run(self, x): ...

class OpRunBinary(OpRun, metaclass=abc.ABCMeta):
    def run(self, x, y): ...

class OpRunBinaryComparison(OpRunBinary, metaclass=abc.ABCMeta): ...

class OpRunBinaryNum(OpRunBinary, metaclass=abc.ABCMeta):
    def run(self, x, y): ...

class OpRunBinaryNumpy(OpRunBinaryNum):
    numpy_fct: Incomplete
    def __init__(self, numpy_fct: Any, onnx_node: NodeProto, run_params: dict[str, Any]) -> None: ...

class OpRunReduceNumpy(OpRun, metaclass=abc.ABCMeta):
    axes: Incomplete
    def __init__(self, onnx_node: NodeProto, run_params: dict[str, Any]) -> None: ...
    def is_axes_empty(self, axes): ...
    def handle_axes(self, axes, noop_with_empty_axes: bool = False): ...
    def output_shape(self, data, axes, keepdims): ...
    def reduce_constant(self, data, const_val, axes, keepdims): ...
