from onnx.reference.ops.op_pool_common import CommonPool as CommonPool

class AveragePool_1(CommonPool): ...
class AveragePool_7(CommonPool): ...
class AveragePool_11(CommonPool): ...
class AveragePool_19(CommonPool): ...
