from onnx.reference.op_run import OpRun as OpRun

def construct_original_grid(data_size, align_corners): ...
def apply_affine_transform(theta_n, original_grid_homo): ...

class AffineGrid(OpRun): ...
