from onnx.helper import np_dtype_to_tensor_dtype as np_dtype_to_tensor_dtype
from onnx.reference.op_run import OpRun as OpRun
from onnx.reference.ops.op_cast import cast_to as cast_to

class CastLike_15(OpRun): ...
class CastLike_19(OpRun): ...
class CastLike_25(OpRun): ...
