import numpy as np
import onnx
from onnx.reference.op_run import OpRun as OpRun

def cast_to(x: np.ndarray, to: onnx.TensorProto.DataType, saturate: bool, round_mode: str = 'up'): ...

class Cast_1(OpRun): ...
class Cast_19(OpRun): ...
class Cast_24(OpRun): ...
class Cast_25(OpRun): ...
