from onnx import TensorProto as TensorProto
from onnx.helper import np_dtype_to_tensor_dtype as np_dtype_to_tensor_dtype, tensor_dtype_to_np_dtype as tensor_dtype_to_np_dtype
from onnx.reference.op_run import OpRun as OpRun

class _CommonDequantizeLinear(OpRun): ...
class DequantizeLinear_19(_CommonDequantizeLinear): ...
class DequantizeLinear_21(_CommonDequantizeLinear): ...
class DequantizeLinear_23(_CommonDequantizeLinear): ...
class DequantizeLinear_25(_CommonDequantizeLinear): ...
