from _typeshed import Incomplete
from onnx.reference.op_run import OpRun as OpRun

class CommonGRU(OpRun):
    n_outputs: Incomplete
    number_of_gates: int
    def __init__(self, onnx_node, run_params) -> None: ...
    def f(self, x): ...
    def g(self, x): ...

class GRU(CommonGRU):
    def __init__(self, onnx_node, run_params) -> None: ...
