import numpy as np
from onnx.reference.op_run import OpRun as OpRun

def gather_numpy_2(self, index: np.ndarray) -> np.ndarray: ...
def gather_numpy(self, dim: int, index: np.ndarray) -> np.ndarray: ...

class GatherElements(OpRun): ...
