import numpy as np
from _typeshed import Incomplete
from onnx.reference.op_run import OpRun as OpRun

class CommonLSTM(OpRun):
    n_outputs: Incomplete
    n_gates: int
    def __init__(self, onnx_node, run_params) -> None: ...
    def f(self, x: np.ndarray) -> np.ndarray: ...
    def g(self, x: np.ndarray) -> np.ndarray: ...
    def h(self, x: np.ndarray) -> np.ndarray: ...

class LSTM(CommonLSTM):
    def __init__(self, onnx_node, run_params) -> None: ...
