import dataclasses
import numpy as np
from _typeshed import Incomplete
from onnx.reference.op_run import OpRun as OpRun

@dataclasses.dataclass
class PrepareContext:
    boxes_data_: np.ndarray | None = ...
    boxes_size_: int = ...
    scores_data_: np.ndarray | None = ...
    scores_size_: int = ...
    max_output_boxes_per_class_: np.ndarray | None = ...
    score_threshold_: np.ndarray | None = ...
    iou_threshold_: np.ndarray | None = ...
    num_batches_: int = ...
    num_classes_: int = ...
    num_boxes_: int = ...

class SelectedIndex:
    batch_index_: Incomplete
    class_index_: Incomplete
    box_index_: Incomplete
    def __init__(self, batch_index: int = 0, class_index: int = 0, box_index: int = 0) -> None: ...

def max_min(lhs: float, rhs: float) -> tuple[float, float]: ...
def suppress_by_iou(boxes_data: np.ndarray, box_index1: int, box_index2: int, center_point_box: int, iou_threshold: float) -> bool: ...

class BoxInfo:
    score_: Incomplete
    idx_: Incomplete
    def __init__(self, score: float = 0, idx: int = -1) -> None: ...
    def __lt__(self, rhs) -> bool: ...

class NonMaxSuppression(OpRun):
    def get_thresholds_from_inputs(self, pc: PrepareContext, max_output_boxes_per_class: int, iou_threshold: float, score_threshold: float) -> tuple[int, float, float]: ...
    def prepare_compute(self, pc: PrepareContext, boxes_tensor: np.ndarray, scores_tensor: np.ndarray, max_output_boxes_per_class_tensor: np.ndarray, iou_threshold_tensor: np.ndarray, score_threshold_tensor: np.ndarray): ...
