import numpy as np
from collections.abc import Sequence
from onnx.reference.op_run import OpRun as OpRun

def get_pad_shape(auto_pad: str, input_spatial_shape: Sequence[int], kernel_spatial_shape: Sequence[int], strides_spatial: Sequence[int], output_spatial_shape: Sequence[int]) -> Sequence[int]: ...
def get_pad_with_auto_pad(auto_pad: str, pad_shape: Sequence[int]) -> Sequence[int]: ...
def get_output_shape_explicit_padding(pads: Sequence[int] | None, input_spatial_shape: Sequence[int], kernel_spatial_shape: Sequence[int], strides_spatial: Sequence[int], dilations: Sequence[int] | None = None, ceil_mode: bool = False) -> tuple[Sequence[int], Sequence[int]]: ...
def get_output_shape_auto_pad(auto_pad: str, input_spatial_shape: Sequence[int], kernel_spatial_shape: Sequence[int], strides_spatial: Sequence[int]) -> Sequence[int]: ...
def pool(padded: np.ndarray, x_shape: Sequence[int], kernel: Sequence[int], strides: Sequence[int], out_shape: Sequence[int], pooling_type: str, pads_required: Sequence[int] | None = None, pads: Sequence[int] | None = None, dilations: Sequence[int] | None = None, count_include_pad: int = 0, p: int = 1) -> np.ndarray: ...

class CommonPool(OpRun): ...
