from onnx import TensorProto as TensorProto
from onnx.helper import np_dtype_to_tensor_dtype as np_dtype_to_tensor_dtype, tensor_dtype_to_np_dtype as tensor_dtype_to_np_dtype
from onnx.reference.op_run import OpRun as OpRun

class _CommonQuantizeLinear(OpRun): ...
class QuantizeLinear_10(_CommonQuantizeLinear): ...
class QuantizeLinear_19(_CommonQuantizeLinear): ...
class QuantizeLinear_21(_CommonQuantizeLinear): ...
class QuantizeLinear_23(_CommonQuantizeLinear): ...
class QuantizeLinear_25(_CommonQuantizeLinear): ...
