from onnx.reference.ops._op import OpRunReduceNumpy as OpRunReduceNumpy

def compute_log_sum_exp(data, axes, keepdims): ...

class ReduceLogSumExp_1(OpRunReduceNumpy): ...
class ReduceLogSumExp_18(OpRunReduceNumpy): ...
