import numpy as np
from onnx.reference.op_run import OpRun as OpRun

def reshape_reference_implementation(data: np.ndarray, shape: np.ndarray, allowzero: int = 0) -> np.ndarray: ...

class CommonReshape(OpRun): ...
class Reshape_5(CommonReshape): ...
class Reshape_14(CommonReshape): ...
