import abc
from _typeshed import Incomplete
from onnx.reference.op_run import OpRun as OpRun

class CommonSplit(OpRun, metaclass=abc.ABCMeta):
    n_outputs: Incomplete
    def __init__(self, onnx_node, run_params) -> None: ...
    def common_run(self, mat, split, axis, num_outputs): ...

class Split_2(CommonSplit): ...
class Split_11(Split_2): ...
class Split_13(CommonSplit): ...
class Split_18(CommonSplit): ...
