from onnx.reference.op_run import OpRun as OpRun

def softmaxcrossentropy(x, target, weight=None, reduction: str = 'mean', ignore_index=None, get_log_prob=None): ...

class SoftmaxCrossEntropyLoss(OpRun): ...
