import numpy as np
from onnx.reference.op_run import OpRun as OpRun

def pad_empty_string(split_lists: list | np.ndarray, padding_requirement: list | int) -> list: ...
def split_with_padding(x, separator=None, maxsplit=None): ...

class StringSplit(OpRun): ...
