import collections
import numpy as np
from _typeshed import Incomplete
from enum import IntEnum
from onnx.reference.op_run import OpRun as OpRun

class IntMap(collections.UserDict):
    added_keys: Incomplete
    def __init__(self) -> None: ...
    def emplace(self, key, value): ...
    @property
    def first_key(self): ...

class NgramPart:
    id_: Incomplete
    def __init__(self, nid: int) -> None: ...
    def init(self) -> None: ...
    def empty(self): ...
    def has_leaves(self): ...
    @property
    def leaves_(self): ...
    def find(self, key): ...
    def emplace(self, key, value): ...
    def __getitem__(self, key): ...

class WeightingCriteria(IntEnum):
    NONE = 0
    TF = 1
    IDF = 2
    TFIDF = 3

def populate_grams(els, els_index, n_ngrams: int, ngram_size: int, ngram_id: int, c): ...

class TfIdfVectorizer(OpRun):
    weighting_criteria_: Incomplete
    min_gram_length_: Incomplete
    max_gram_length_: Incomplete
    max_skip_count_: Incomplete
    ngram_counts_: Incomplete
    ngram_indexes_: Incomplete
    output_size_: Incomplete
    weights_: Incomplete
    pool_int64s_: Incomplete
    pool_strings_: Incomplete
    int64_map_: Incomplete
    def __init__(self, onnx_node, run_params) -> None: ...
    def increment_count(self, ngram_id: int, row_num: int, frequencies: list[int]) -> None: ...
    def output_result(self, B: int, frequencies: list[int]) -> np.ndarray: ...
    def compute_impl(self, X: np.ndarray, row_num: int, row_size: int, frequencies: list[int], max_gram_length=None, max_skip_count=None, min_gram_length=None, mode=None, ngram_counts=None, ngram_indexes=None, pool_int64s=None, pool_strings=None, weights=None) -> None: ...
