import abc
from onnx.reference.op_run import OpRun as OpRun

def topk_sorted_implementation(X, k, axis, largest): ...

class _CommonTopK(OpRun, metaclass=abc.ABCMeta): ...
class TopK_1(_CommonTopK): ...
class TopK_10(_CommonTopK): ...
class TopK_11(_CommonTopK): ...
