import pathlib
import typing

def path_match_suffix_ignore_case(path: pathlib.Path | str, suffix: str) -> bool: ...
def files_from_file_or_dir(file_or_dir_path: pathlib.Path | str, predicate: typing.Callable[[pathlib.Path], bool] = ...) -> list[pathlib.Path]: ...
