from _typeshed import Incomplete

float_dict: Incomplete
integer_dict: Incomplete

def generate_feeds(sess, symbolic_dims: dict | None = None): ...
def run_model(model_path, num_iters: int = 1, debug=None, profile=None, symbolic_dims=None, feeds=None, override_initializers: bool = True): ...
def main(): ...
