import logging
import onnx
import onnxruntime as ort
import pathlib
from _typeshed import Incomplete

def iterate_graph_per_node_func(graph, per_node_func, **func_args) -> None: ...
def iterate_graph_per_graph_func(graph, per_graph_func, **func_args) -> None: ...
def get_opsets_imported(model: onnx.ModelProto): ...
def update_onnx_opset(model_path: pathlib.Path, opset: int, out_path: pathlib.Path | None = None, logger: logging.Logger | None = None): ...
def optimize_model(model_path: pathlib.Path, output_path: pathlib.Path, level: ort.GraphOptimizationLevel = ..., log_level: int = 3, use_external_initializers: bool = False): ...
def remove_invalid_dim_values(graph: onnx.GraphProto): ...
def make_dim_param_fixed(graph: onnx.GraphProto, param_name: str, value: int): ...
def make_input_shape_fixed(graph: onnx.GraphProto, input_name: str, fixed_shape: [int]): ...
def fix_output_shapes(model: onnx.ModelProto): ...
def get_producer_consumer_maps(graph: onnx.GraphProto): ...
def is_fixed_size_tensor(value: onnx.ValueInfoProto): ...
def get_optimization_level(level): ...

class ModelProtoWithShapeInfo:
    model_path: Incomplete
    model_with_shape_info: Incomplete
    def __init__(self, model_path: pathlib.Path) -> None: ...
    def __del__(self) -> None: ...
