from _typeshed import Incomplete
from collections.abc import Sequence
from onnx import defs as defs, helper as helper
from onnx.backend.sample.ops import collect_sample_implementations as collect_sample_implementations
from onnx.backend.test.case import collect_snippets as collect_snippets
from onnx.defs import ONNX_ML_DOMAIN as ONNX_ML_DOMAIN, OpSchema as OpSchema
from typing import NamedTuple

SNIPPETS: Incomplete
SAMPLE_IMPLEMENTATIONS: Incomplete
ONNX_ML: Incomplete

def display_number(v: int) -> str: ...
def should_render_domain(domain: str, output: str) -> bool: ...
def format_name_with_domain(domain: str, schema_name: str) -> str: ...
def format_function_versions(function_versions: Sequence[int]) -> str: ...
def format_versions(versions: Sequence[OpSchema], changelog: str) -> str: ...
def display_attr_type(v: OpSchema.AttrType) -> str: ...
def display_domain(domain: str) -> str: ...
def display_domain_short(domain: str) -> str: ...
def display_version_link(name: str, version: int, changelog: str) -> str: ...
def generate_formal_parameter_tags(formal_parameter: OpSchema.FormalParameter) -> str: ...
def display_schema(schema: OpSchema, versions: Sequence[OpSchema], changelog: str) -> str: ...
def support_level_str(level: OpSchema.SupportType) -> str: ...

class Args(NamedTuple):
    output: str
    changelog: str

def main(args: Args) -> None: ...
