import numpy as np
from onnx import TensorProto
from onnx_model import OnnxModel

def fake_input_ids_data(input_ids: TensorProto, batch_size: int, sequence_length: int, dictionary_size: int) -> np.ndarray: ...
def fake_segment_ids_data(segment_ids: TensorProto, batch_size: int, sequence_length: int) -> np.ndarray: ...
def get_random_length(max_sequence_length: int, average_sequence_length: int): ...
def fake_input_mask_data(input_mask: TensorProto, batch_size: int, sequence_length: int, average_sequence_length: int, random_sequence_length: bool, mask_type: int = 2) -> np.ndarray: ...
def output_test_data(directory: str, inputs: dict[str, np.ndarray]): ...
def fake_test_data(batch_size: int, sequence_length: int, test_cases: int, dictionary_size: int, verbose: bool, random_seed: int, input_ids: TensorProto, segment_ids: TensorProto, input_mask: TensorProto, average_sequence_length: int, random_sequence_length: bool, mask_type: int): ...
def generate_test_data(batch_size: int, sequence_length: int, test_cases: int, seed: int, verbose: bool, input_ids: TensorProto, segment_ids: TensorProto, input_mask: TensorProto, average_sequence_length: int, random_sequence_length: bool, mask_type: int, dictionary_size: int = 10000): ...
def get_graph_input_from_embed_node(onnx_model, embed_node, input_index): ...
def find_bert_inputs(onnx_model: OnnxModel, input_ids_name: str | None = None, segment_ids_name: str | None = None, input_mask_name: str | None = None) -> tuple[np.ndarray | None, np.ndarray | None, np.ndarray | None]: ...
def get_bert_inputs(onnx_file: str, input_ids_name: str | None = None, segment_ids_name: str | None = None, input_mask_name: str | None = None) -> tuple[np.ndarray | None, np.ndarray | None, np.ndarray | None]: ...
def parse_arguments(): ...
def create_and_save_test_data(model: str, output_dir: str, batch_size: int, sequence_length: int, test_cases: int, seed: int, verbose: bool, input_ids_name: str | None, segment_ids_name: str | None, input_mask_name: str | None, only_input_tensors: bool, average_sequence_length: int, random_sequence_length: bool, mask_type: int): ...
def main() -> None: ...
