import argparse
import onnx
import torch
from _typeshed import Incomplete
from benchmark_helper import Precision
from enum import Enum
from onnx import GraphProto as GraphProto, ModelProto as ModelProto, TensorProto
from onnx_model import OnnxModel
from onnxruntime import GraphOptimizationLevel as GraphOptimizationLevel, InferenceSession as InferenceSession, SessionOptions as SessionOptions, get_available_providers as get_available_providers
from onnxruntime.transformers.models.gpt2.gpt2_helper import PRETRAINED_GPT2_MODELS as PRETRAINED_GPT2_MODELS
from onnxruntime.transformers.models.t5.t5_helper import PRETRAINED_MT5_MODELS as PRETRAINED_MT5_MODELS, PRETRAINED_T5_MODELS as PRETRAINED_T5_MODELS
from transformers import GPT2LMHeadModel, T5ForConditionalGeneration
from typing import Any

logger: Incomplete

class GenerationType(Enum):
    BEAMSEARCH = 'beam_search'
    GREEDYSEARCH = 'greedy_search'
    SAMPLING = 'sampling'

def parse_arguments(argv: list[str] | None = None) -> argparse.Namespace: ...
def gpt2_to_onnx(args: argparse.Namespace): ...
def t5_to_onnx(args: argparse.Namespace): ...
def shape_inference(onnx_path: str, use_external_data_format: bool = True): ...
def pad_weights_of_logits_matmul(onnx_path: str, use_external_data_format: bool = True) -> bool: ...
def create_ort_session(model_path: str, use_gpu: bool, use_sln_strict_mode: bool) -> InferenceSession: ...
def verify_gpt2_subgraph(graph: onnx.GraphProto, precision: Precision): ...
def verify_t5_decoder_subgraph(graph: onnx.GraphProto, precision: Precision): ...
def verify_t5_encoder_decoder_init_subgraph(graph: onnx.GraphProto, precision: Precision): ...
def remove_shared_initializers(graph1: GraphProto, graph2: GraphProto, shared_prefix: str = 'shared_', min_elements: int = 1024, signature_cache1: dict | None = None, signature_cache2: dict | None = None): ...
def get_shared_initializers(encoder_model: ModelProto, decoder_model: ModelProto): ...
def move_initializers(graph: GraphProto, min_elements: int = 1024) -> list[TensorProto]: ...
def kwargs_of(node): ...
def shape_of(vi): ...
def update_decoder_subgraph_past_present_share_buffer(subg: GraphProto): ...
def update_decoder_subgraph_use_decoder_masked_attention(subg: GraphProto, is_beam_search: bool, switch_attention: bool) -> bool: ...
def find_past_seq_len_usage(subg: GraphProto): ...
def add_cache_indirection_to_mha(model: OnnxModel, past_seq_len_name: str): ...
def add_output_qk_to_mha(model: OnnxModel, dtype: int = 0, skip_node_idxs: list[int] = []): ...
def fix_past_sequence_length(model: OnnxModel): ...
def replace_mha_with_dmmha(model: OnnxModel, past_seq_len_name: str): ...
def replace_mha_with_gqa(model: OnnxModel, attn_mask: str, kv_num_heads: int = 0, world_size: int = 1, window_size: int = -1): ...
def update_decoder_subgraph_output_cross_attention(subg: GraphProto): ...
def update_decoder_subgraph_share_buffer_and_use_decoder_masked_mha(subg: ModelProto): ...
def pack_qkv_for_decoder_masked_mha(model_proto: ModelProto): ...
def update_input_shapes_for_gpt2_decoder_model(decoder_onnx_path: str, use_external_data_format: bool = True): ...
def generate_gpt2_init_decoder(decoder_onnx_path: str, init_decoder_onnx_path: str, use_external_data_format: bool = True) -> bool: ...
def make_dim_proto_numeric_t5(model, config) -> None: ...
def convert_generation_model(args: argparse.Namespace, generation_type: GenerationType = ...): ...
def test_torch_performance(args: argparse.Namespace, model: GPT2LMHeadModel | T5ForConditionalGeneration, input_ids: torch.Tensor, attention_mask: torch.Tensor, eos_token_id: int, pad_token_id: int, bad_words_ids: list[list[int]]) -> dict[str, Any]: ...
def create_attention_mask(input_ids, pad_token_id): ...
def test_gpt_model(args: argparse.Namespace, sentences: list[str] | None = None, is_greedy: bool = False): ...
def test_t5_model(args: argparse.Namespace, sentences: list[str] | None = None): ...
def main(argv: list[str] | None = None, sentences: list[str] | None = None): ...
