import onnx
from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any

logger: Incomplete

class DynamoOnnxHelper:
    model: Incomplete
    def __init__(self, model: onnx.ModelProto) -> None: ...
    def update_edges(self, edge_mapping: dict) -> None: ...
    def unroll_function(self, func_name: str) -> None: ...
    def remove_function(self, func_name: str, input_id: int, output_id: int) -> None: ...
    def remove_dropout_layer(self) -> None: ...
    def remove_lm_head_layer(self) -> None: ...
    def add_initializer(self, name: str, data_type: int, dims: Sequence[int], vals: Any, raw: bool = True): ...
    def convert_constants_to_initializers(self, min_size: int = 1) -> None: ...
    def clear_metadata(self) -> None: ...
    @staticmethod
    def fold_transpose_initializers(model) -> None: ...
