from _typeshed import Incomplete
from onnx import NodeProto as NodeProto, TensorProto

logger: Incomplete

def convert_np_to_float16(np_array, min_positive_val: float = 5.96e-08, max_finite_val: float = 65504.0): ...
def convert_tensor_float_to_float16(tensor, min_positive_val: float = 5.96e-08, max_finite_val: float = 65504.0): ...
def make_value_info_from_tensor(tensor): ...

DEFAULT_OP_BLOCK_LIST: Incomplete
ALWAYS_FLOAT_INPUTS: Incomplete

class InitializerTracker:
    initializer: Incomplete
    fp32_nodes: Incomplete
    fp16_nodes: Incomplete
    def __init__(self, initializer: TensorProto) -> None: ...
    def add_node(self, node: NodeProto, is_node_blocked): ...

def convert_float_to_float16(model, min_positive_val: float = 5.96e-08, max_finite_val: float = 65504.0, keep_io_types: bool = False, disable_shape_infer: bool = False, op_block_list=None, node_block_list=None, force_fp16_initializers: bool = False, force_fp16_inputs=None, use_bfloat16_as_blocked_nodes_dtype: bool = False): ...
def float_to_float16_max_diff(tensor, min_positive_val: float = 5.96e-08, max_finite_val: float = 65504.0): ...
