from _typeshed import Incomplete
from fusion_attention import FusionAttention
from fusion_base import Fusion
from onnx import FunctionProto as FunctionProto, NodeProto as NodeProto
from onnx_model import OnnxModel

logger: Incomplete

class FusionRotaryAttention(FusionAttention):
    def __init__(self, model: OnnxModel, hidden_size: int, num_heads: int) -> None: ...
    def create_mha_node(self, input: str, output: str, q_rotary: NodeProto, k_rotary: NodeProto, v_matmul: NodeProto, attn_mask: str = '', add_qk: str = '', past_k: str = '', past_v: str = '', present_k: str = '', present_v: str = '', scale: float | None = None) -> NodeProto | None: ...
    def check_runtime_shape_paths_for_function(self, reshape_qkv_2, reshape_qkv_1, reshape_q_2, reshape_k_2, reshape_v_2, reshape_v_1, add_qk, root_input): ...
    def check_runtime_shape_paths_for_nodes(self, reshape_qkv, reshape_q, reshape_k, reshape_v, root_input): ...
    prune_graph: bool
    def fuse(self, normalize_node, input_name_to_nodes, output_name_to_node): ...

class FusionRotaryEmbeddings(Fusion):
    base_name: str
    def __init__(self, model: OnnxModel) -> None: ...
    def reassign_extra_outputs(self, rot_emb_node: NodeProto, function: FunctionProto): ...
    def create_rotary_embeddings_from_function(self, node: NodeProto): ...
    def create_rotary_embeddings_from_nodes(self, root_input: str, position_ids: str, cos_slice: str, sin_slice: str, output: str): ...
    prune_graph: bool
    def fuse(self, node, input_name_to_nodes, output_name_to_node): ...
