from _typeshed import Incomplete
from fusion_base import Fusion
from onnx_model import OnnxModel

logger: Incomplete

class FusionSkipGroupNorm(Fusion):
    shape_infer_helper: Incomplete
    def __init__(self, model: OnnxModel) -> None: ...
    def create_transpose_node(self, input_name: str, perm: list[int], output_name=None): ...
    def get_skip_index(self, add, is_channel_last: bool): ...
    def has_multiple_consumers(self, output_name, input_name_to_nodes): ...
    def remove_if_safe(self, node, input_name_to_nodes) -> None: ...
    def is_bias_1d(self, bias_name: str): ...
    def match_bias_path(self, node, input_name_to_nodes, output_name_to_node): ...
    def match_transpose_from_nhwc(self, output_name, input_name_to_nodes, output_name_to_node): ...
    prune_graph: bool
    def fuse(self, node, input_name_to_nodes, output_name_to_node) -> None: ...
