from _typeshed import Incomplete
from fusion_base import Fusion
from onnx_model import OnnxModel as OnnxModel

logger: Incomplete

class FusionConstantFold(Fusion):
    count: int
    def __init__(self, model: OnnxModel) -> None: ...
    def apply(self) -> None: ...
    def fuse(self, node, input_name_to_nodes, output_name_to_node) -> None: ...
    def fuse_1(self, node, input_name_to_nodes, output_name_to_node) -> None: ...
    def fuse_2(self, node, input_name_to_nodes, output_name_to_node) -> None: ...
