from _typeshed import Incomplete
from fusion_base import Fusion
from onnx import NodeProto as NodeProto
from onnx_model import OnnxModel

logger: Incomplete

class FusionTranspose(Fusion):
    def __init__(self, model: OnnxModel) -> None: ...
    def fuse(self, transpose_node: NodeProto, input_name_to_nodes: dict[str, list[NodeProto]], output_name_to_node: dict[str, NodeProto]): ...

class FusionInsertTranspose(Fusion):
    def __init__(self, model: OnnxModel) -> None: ...
    def create_transpose_node(self, input_name: str, perm: list[int], output_name=None): ...
    def fuse(self, group_norm_node: NodeProto, input_name_to_nodes: dict[str, list[NodeProto]], output_name_to_node: dict[str, NodeProto]): ...
