from _typeshed import Incomplete
from fusion_base import Fusion
from onnx import NodeProto as NodeProto
from onnx_model import OnnxModel

logger: Incomplete

class FusionMultiHeadAttentionSam2(Fusion):
    hidden_size: Incomplete
    num_heads: Incomplete
    num_heads_warning: bool
    hidden_size_warning: bool
    def __init__(self, model: OnnxModel, hidden_size: int, num_heads: int) -> None: ...
    def get_decoder_num_heads(self, reshape_q: NodeProto) -> int: ...
    def get_encoder_num_heads(self, reshape_in: NodeProto) -> int: ...
    def get_hidden_size(self, layernorm_node): ...
    def get_num_heads_and_hidden_size(self, reshape_q: NodeProto, layernorm_node: NodeProto, is_encoder: bool = False) -> tuple[int, int]: ...
    def create_attention_node(self, q_matmul: NodeProto, q_add: NodeProto, k_matmul: NodeProto, k_add: NodeProto, v_matmul: NodeProto, v_add: NodeProto, num_heads: int, hidden_size: int, output: str) -> NodeProto | None: ...
    prune_graph: bool
    def fuse(self, normalize_node, input_name_to_nodes, output_name_to_node) -> None: ...
    def match_attention_subgraph(self, node_after_output_projection): ...
    def fuse_sam_encoder_pattern(self, normalize_node, input_name_to_nodes, output_name_to_node) -> bool: ...
    def match_sam_encoder_attention_subgraph(self, node_after_output_projection, input_index=None): ...
    def create_mha_node(self, reshape_q: NodeProto, transpose_k: NodeProto, transpose_v: NodeProto, num_heads: int) -> NodeProto: ...
