from _typeshed import Incomplete
from fusion_base import Fusion
from onnx_model import OnnxModel as OnnxModel

logger: Incomplete

class FusionFastGelu(Fusion):
    def __init__(self, model: OnnxModel) -> None: ...
    def fuse(self, tanh_node, input_name_to_nodes: dict, output_name_to_node: dict): ...
    def fuse_1(self, tanh_node, input_name_to_nodes, output_name_to_node) -> bool | None: ...
    def fuse_2(self, tanh_node, input_name_to_nodes: dict, output_name_to_node: dict) -> bool | None: ...
    def fuse_3(self, tanh_node, input_name_to_nodes: dict, output_name_to_node: dict) -> bool | None: ...
    def fuse_4(self, tanh_node, input_name_to_nodes: dict, output_name_to_node: dict) -> bool | None: ...
