from _typeshed import Incomplete
from fusion_base import Fusion
from onnx_model import OnnxModel

logger: Incomplete

class FusionLayerNormalization(Fusion):
    check_constant_and_dimension: Incomplete
    force: Incomplete
    def __init__(self, model: OnnxModel, check_constant_and_dimension: bool = True, force: bool = False) -> None: ...
    prune_graph: bool
    def fuse(self, node, input_name_to_nodes: dict, output_name_to_node: dict): ...

class FusionLayerNormalizationNCHW(Fusion):
    def __init__(self, model: OnnxModel) -> None: ...
    def get_weight_or_bias(self, output_name, description): ...
    def create_transpose_node(self, input_name: str, perm: list[int], output_name=None): ...
    def fuse(self, node, input_name_to_nodes: dict, output_name_to_node: dict): ...

class FusionLayerNormalizationTF(Fusion):
    def __init__(self, model: OnnxModel) -> None: ...
    def fuse(self, node, input_name_to_nodes: dict, output_name_to_node: dict): ...
