from _typeshed import Incomplete
from fusion_base import Fusion
from onnx import NodeProto as NodeProto
from onnx_model import OnnxModel as OnnxModel

logger: Incomplete

class FusionAttentionUnet(Fusion):
    hidden_size: Incomplete
    num_heads: Incomplete
    is_cross_attention: Incomplete
    enable_packed_qkv: Incomplete
    enable_packed_kv: Incomplete
    num_heads_warning: bool
    hidden_size_warning: bool
    def __init__(self, model: OnnxModel, hidden_size: int, num_heads: int, is_cross_attention: bool, enable_packed_qkv: bool, enable_packed_kv: bool) -> None: ...
    def get_num_heads(self, reshape_q: NodeProto, is_torch2: bool = False) -> int: ...
    def get_hidden_size(self, layernorm_node): ...
    def get_num_heads_and_hidden_size(self, reshape_q: NodeProto, layernorm_node: NodeProto, is_torch2: bool = False) -> tuple[int, int]: ...
    def create_attention_node(self, q_matmul: NodeProto, k_matmul: NodeProto, v_matmul: NodeProto, num_heads: int, hidden_size: int, input: str, output: str) -> NodeProto | None: ...
    def create_attention_node_lora(self, q_matmul_add: NodeProto, k_matmul_add: NodeProto, v_matmul_add: NodeProto, num_heads: int, hidden_size: int, input: str, output: str) -> NodeProto | None: ...
    prune_graph: bool
    def fuse(self, normalize_node, input_name_to_nodes, output_name_to_node) -> None: ...
    def match_qkv_torch1(self, root_input, skip_add): ...
    def match_qkv_torch2(self, root_input, skip_add): ...
    def match_qkv_torch1_lora(self, root_input, skip_add): ...
    def match_qkv_torch2_lora(self, root_input, skip_add): ...
    def match_lora_path(self, add_node: NodeProto): ...
    def fuse_a1111_fp16(self, normalize_node, input_name_to_nodes, output_name_to_node): ...
    def match_qkv_a1111(self, root_input, skip_add): ...
