from _typeshed import Incomplete
from numpy import ndarray
from onnx import NodeProto as NodeProto, TensorProto
from onnx_model import OnnxModel as OnnxModel

logger: Incomplete

class FusionUtils:
    model: OnnxModel
    def __init__(self, model: OnnxModel) -> None: ...
    def cast_graph_input_to_int32(self, input_name: str) -> tuple[bool, str]: ...
    def cast_input(self, input_name: str, target_type: str = 'int32'): ...
    def add_cast_node(self, input_name: str, to_type: int, output_name: str | None = None, output_name_to_node=None, graph_name: str | None = None): ...
    def cast_input_to_int32(self, input_name: str): ...
    def remove_cast_int32(self, input_name: str): ...
    @staticmethod
    def update_node_input(node, i, new_input_name, input_name_to_nodes): ...
    @staticmethod
    def skip_parent(model: OnnxModel, node, parent_node, input_name_to_nodes, node_input_index: int = 0, parent_input_index: int = 0): ...
    def get_squeeze_or_unsqueeze_axes(self, node: NodeProto) -> ndarray | None: ...
    @staticmethod
    def check_node_attribute(node, attribute_name: str, expected_value, default_value=None): ...
    @staticmethod
    def transpose_2d_int8_tensor(tensor: TensorProto): ...
    @staticmethod
    def check_qdq_node_for_fusion(node: NodeProto, model: OnnxModel, allow_per_tensor_quantization_only: bool = True): ...
    def check_node_input_value(self, node, input_index: int, expected_value): ...
    def remove_identity_nodes(self) -> None: ...
    def remove_cascaded_cast_nodes(self) -> None: ...
    def remove_useless_cast_nodes(self) -> None: ...
    def remove_useless_reshape_nodes(self) -> None: ...

class NumpyHelper:
    @staticmethod
    def to_array(tensor: TensorProto, fill_zeros: bool = False) -> ndarray: ...
