from _typeshed import Incomplete
from fusion_base import Fusion
from fusion_options import AttentionMaskFormat
from onnx import NodeProto
from onnx_model import OnnxModel as OnnxModel

logger: Incomplete

class AttentionMask:
    model: Incomplete
    mask_indice: Incomplete
    mask_casted: Incomplete
    utils: Incomplete
    mask_format: Incomplete
    opset_version: Incomplete
    def __init__(self, model: OnnxModel) -> None: ...
    def set_mask_format(self, mask_format: AttentionMaskFormat): ...
    def set_mask_indice(self, mask, mask_index) -> None: ...
    def get_first_mask(self): ...
    def process_mask(self, mask_2d: str) -> str | None: ...

class FusionAttention(Fusion):
    hidden_size: Incomplete
    num_heads: Incomplete
    attention_mask: Incomplete
    use_multi_head_attention: Incomplete
    disable_multi_head_attention_bias: Incomplete
    mask_filter_value: Incomplete
    num_heads_warning: bool
    hidden_size_warning: bool
    shape_infer: Incomplete
    shape_infer_done: bool
    def __init__(self, model: OnnxModel, hidden_size: int, num_heads: int, attention_mask: AttentionMask | None = None, use_multi_head_attention: bool = False, disable_multi_head_attention_bias: bool = False, search_op_types: list[str] = ['SkipLayerNormalization', 'LayerNormalization']) -> None: ...
    def get_num_heads_and_hidden_size_from_concat(self, concat: NodeProto) -> tuple[int, int]: ...
    def get_num_heads_and_hidden_size(self, reshape_q: NodeProto) -> tuple[int, int]: ...
    def get_add_qk_str(self, add_qk: NodeProto): ...
    def reshape_add_qk(self, add_qk: str): ...
    def concat_kv(self, past_k: str, past_v: str) -> str: ...
    def split_kv(self, present_k_name: str, present_v_name: str, kv_node: str): ...
    def create_combined_qkv_bias(self, q_add: NodeProto, k_add: NodeProto | None, v_add: NodeProto | None, name_prefix: str) -> NodeProto | None: ...
    def create_packed_qkv_matmul_node(self, q_matmul: NodeProto, k_matmul: NodeProto, v_matmul: NodeProto, q_add: NodeProto, k_add: NodeProto | None, v_add: NodeProto | None) -> tuple[NodeProto, NodeProto, NodeProto]: ...
    def create_multihead_attention_node(self, q_matmul: NodeProto, k_matmul: NodeProto | str | None, v_matmul: NodeProto | str | None, q_add: NodeProto, k_add: NodeProto | None, v_add: NodeProto | None, num_heads: int, hidden_size: int, output: str, key_padding_mask: str = '', add_qk: str = '', unidirectional: bool = False, past_k: str = '', past_v: str = '', present_k: str = '', present_v: str = '', packed_qkv: bool = False) -> NodeProto | None: ...
    def create_attention_node(self, mask_index: str | None, q_matmul: NodeProto, k_matmul: NodeProto, v_matmul: NodeProto, q_add: NodeProto, k_add: NodeProto, v_add: NodeProto, num_heads: int, hidden_size: int, first_input: str, output: str, add_qk_str: str = '', causal: bool = False, past_k: str = '', past_v: str = '', present_k: str = '', present_v: str = '', scale: float | None = None) -> NodeProto | None: ...
    prune_graph: bool
    def fuse(self, node, input_name_to_nodes, output_name_to_node) -> None: ...
