from _typeshed import Incomplete
from fusion_base import Fusion
from onnx import NodeProto as NodeProto
from onnx_model import OnnxModel as OnnxModel

logger: Incomplete

class FusionEmbedLayerNoMask(Fusion):
    utils: Incomplete
    shape_infer: Incomplete
    shape_infer_done: bool
    attention: Incomplete
    embed_node: Incomplete
    def __init__(self, model: OnnxModel, description: str = 'no mask') -> None: ...
    def match_two_gather(self, add: NodeProto) -> None | tuple[NodeProto, NodeProto]: ...
    cross_attention: Incomplete
    def check_attention_subgraph(self, layernorm: NodeProto, input_name_to_nodes: dict[str, list[NodeProto]], is_distil_bert: bool) -> bool: ...
    def match_position_embedding_distilbert(self, position_embedding_gather, input_ids, output_name_to_node): ...
    def match_position_embedding_roberta(self, position_embedding_gather, input_ids, output_name_to_node): ...
    def match_position_embedding_bert(self, position_embedding_gather, input_ids, output_name_to_node): ...
    def match_position_embedding(self, position_embedding_gather, input_ids, output_name_to_node): ...
    def check_embedding(self, word_embedding_gather, segment_embedding_gather, position_embedding_gather): ...
    def cast_to_int32(self, input_name: str) -> tuple[str, None | NodeProto]: ...
    def create_fused_node(self, input_ids: str, layernorm: NodeProto, word_embedding_gather: NodeProto, position_embedding_gather: NodeProto, segment_embedding_gather: None | NodeProto, position_ids: str | None = None, embedding_sum_output: bool = False, embedding_sum_name=None): ...
    prune_graph: bool
    def finish_fusion(self, layernorm, embed_node) -> None: ...
    def is_skip_layer_norm_with_sum_output(self, node): ...
    def fuse_gpt2(self, layernorm, add_before_layernorm, input_name_to_nodes, output_name_to_node, optional_segment_gather=None): ...
    def fuse_distilbert(self, layernorm, add_before_layernorm, input_name_to_nodes, output_name_to_node): ...
    def fuse_bert(self, layernorm, add_before_layernorm, input_name_to_nodes, output_name_to_node): ...
    def fuse(self, node, input_name_to_nodes, output_name_to_node) -> None: ...

class FusionEmbedLayerNormalization(FusionEmbedLayerNoMask):
    use_mask_index: Incomplete
    def __init__(self, model: OnnxModel, use_mask_index: bool = False) -> None: ...
    def replace_mask(self, mask_int32, attention_nodes) -> None: ...
    attention: Incomplete
    cross_attention: Incomplete
    embed_node: Incomplete
    def fuse(self, node, input_name_to_nodes, output_name_to_node) -> None: ...
