from _typeshed import Incomplete
from fusion_base import Fusion
from onnx import NodeProto as NodeProto
from onnx_model import OnnxModel as OnnxModel

logger: Incomplete

class FusionMultiHeadAttentionMMDit(Fusion):
    unsqueeze_update_map: Incomplete
    def __init__(self, model: OnnxModel) -> None: ...
    def get_num_heads(self, start_node: NodeProto, output_name_to_node, input_index: int = 0) -> int: ...
    def get_num_heads_from_k(self, transpose_k: NodeProto, output_name_to_node, concat_before_transpose: bool) -> int: ...
    def reshape_to_3d(self, input_name: str, output_name: str) -> str: ...
    def adjust_query_from_bnsh_to_bsd_no_concat(self, mul_q: NodeProto, output_name_to_node) -> str | None: ...
    def adjust_query_from_bnsh_to_bsd(self, mul_q: NodeProto, output_name_to_node) -> str | None: ...
    def update_unsqueeze_axes_1_to_2(self, unsqueeze: NodeProto) -> str: ...
    def update_unsqueeze_axes(self, add: NodeProto, output_name_to_node: dict[str, NodeProto]) -> bool: ...
    def adjust_flux_query_from_bnsh_to_bsd(self, mul_q: NodeProto, output_name_to_node) -> str | None: ...
    def adjust_flux_single_query_from_bnsh_to_bsd(self, mul_q: NodeProto, output_name_to_node) -> str | None: ...
    def transpose_reshape_bnsh_to_bsd(self, q: str, output_name_to_node) -> str | None: ...
    def create_multihead_attention_node(self, q: str, k: str, v: str, output: str, num_heads: int) -> NodeProto: ...
    prune_graph: bool
    def fuse(self, node, input_name_to_nodes, output_name_to_node) -> None: ...
