import numpy
import torch
from _typeshed import Incomplete
from collections.abc import Mapping
from onnxruntime import InferenceSession as InferenceSession, RunOptions as RunOptions
from typing import Any

ShapeDict = Mapping[str, tuple | list[int]]
logger: Incomplete

class TypeHelper:
    @staticmethod
    def get_input_type(ort_session: InferenceSession, name: str) -> str: ...
    @staticmethod
    def get_output_type(ort_session, name: str) -> str: ...
    @staticmethod
    def ort_type_to_numpy_type(ort_type: str): ...
    @staticmethod
    def ort_type_to_torch_type(ort_type: str): ...
    @staticmethod
    def get_io_onnx_type_map(ort_session: InferenceSession) -> dict[str, int]: ...
    @staticmethod
    def ort_type_to_onnx_type(ort_type: str): ...
    @staticmethod
    def numpy_type_to_torch_type(numpy_type: numpy.dtype): ...
    @staticmethod
    def torch_type_to_numpy_type(torch_type: torch.dtype): ...
    @staticmethod
    def get_io_numpy_type_map(ort_session: InferenceSession) -> dict[str, numpy.dtype]: ...
    @staticmethod
    def get_io_torch_type_map(ort_session: InferenceSession) -> dict[str, torch.dtype]: ...

class IOBindingHelper:
    @staticmethod
    def get_output_buffers(ort_session: InferenceSession, output_shapes, device): ...
    @staticmethod
    def prepare_io_binding(ort_session, input_ids: torch.Tensor, position_ids: torch.Tensor, attention_mask: torch.Tensor, past: list[torch.Tensor], output_buffers, output_shapes): ...
    @staticmethod
    def get_outputs_from_io_binding_buffer(ort_session, output_buffers, output_shapes, return_numpy: bool = True): ...

class CudaSession:
    ort_session: Incomplete
    input_names: Incomplete
    output_names: Incomplete
    io_name_to_onnx_type: Incomplete
    io_name_to_torch_type: Incomplete
    io_binding: Incomplete
    enable_cuda_graph: Incomplete
    input_tensors: Incomplete
    output_tensors: Incomplete
    device: Incomplete
    buffer_sharing: dict[str, str]
    def __init__(self, ort_session: InferenceSession, device: torch.device, enable_cuda_graph: bool = False) -> None: ...
    def set_buffer_sharing(self, input_name: str, output_name: str): ...
    def __del__(self) -> None: ...
    def bind_input_and_buffer_sharing(self, name: str, tensor: torch.Tensor): ...
    def allocate_buffers(self, shape_dict: ShapeDict): ...
    def infer(self, feed_dict: dict[str, torch.Tensor], run_options: RunOptions = None, synchronize: bool = True): ...
    @staticmethod
    def get_cuda_provider_options(device_id: int, enable_cuda_graph: bool, stream: int = 0) -> dict[str, Any]: ...

class GpuBinding(CudaSession):
    gpu_graph_id: Incomplete
    shape_dict: Incomplete
    stream: Incomplete
    last_run_gpu_graph_id: Incomplete
    def __init__(self, ort_session: InferenceSession, device: torch.device, shape_dict: ShapeDict, enable_gpu_graph: bool = False, gpu_graph_id: int = -1, stream: int = 0, buffer_sharing: dict[str, str] | None = None) -> None: ...
    def get_run_options(self, disable_cuda_graph_in_run: bool = False) -> RunOptions: ...
    def infer(self, feed_dict: dict[str, torch.Tensor], disable_cuda_graph_in_run: bool = False): ...

class GpuBindingManager:
    ort_session: Incomplete
    device: Incomplete
    graph_bindings: Incomplete
    no_graph_binding: Incomplete
    stream: Incomplete
    max_cuda_graphs: Incomplete
    def __init__(self, ort_session: InferenceSession, device: torch.device, stream: int = 0, max_cuda_graphs: int = 1) -> None: ...
    def get_binding(self, shape_dict: ShapeDict, use_cuda_graph: bool = False, buffer_sharing: dict[str, str] | None = None) -> GpuBinding: ...
