import torch
from pathlib import Path
from torch import nn as nn

def disable_huggingface_init(): ...
def get_model_parameter_size(model: nn.Module): ...
def initialize_model_and_sample_inputs(hf_model: str, cache_dir: str | None, tokenizer=None): ...
def auto_pipeline_parallel(model: nn.Module, gpulist: list, sample_inputs: tuple): ...
def retrieve_onnx_inputs(model: nn.Module, sample_inputs: tuple, with_past: bool): ...
def move_to_appropriate_device(model: nn.Module, sample_inputs_tp: tuple) -> nn.Module: ...
def adapt_inputs_to_device(sample_inputs: tuple, device: torch.device) -> tuple: ...
def fetch_onnx_inputs_outputs_name(model: nn.Module, onnx_inputs: list, torch_input_names: tuple, past_key_values: tuple, with_past: bool, input_with_past: bool): ...
def do_export_internal(model: nn.Module, onnx_io_tuple: tuple, onnx_inputs: tuple, onnx_path: Path, opset: int): ...
def export_onnx(hf_model: str, cache_dir: str | None, onnx_path_str: str, with_past: bool, opset: int): ...
def parse_arguments(): ...
