from _typeshed import Incomplete

class MachineInfo:
    silent: Incomplete
    logger: Incomplete
    machine_info: Incomplete
    def __init__(self, silent: bool = False, logger=None) -> None: ...
    def get_machine_info(self): ...
    def get_memory_info(self) -> dict: ...
    def get_cpu_info(self) -> dict: ...
    def get_gpu_info_by_nvml(self) -> dict: ...
    def get_related_packages(self) -> list[str]: ...
    def get_onnxruntime_info(self) -> dict: ...
    def get_pytorch_info(self) -> dict: ...
    def get_tensorflow_info(self) -> dict: ...

def parse_arguments(): ...
def get_machine_info(silent: bool = True) -> str: ...
def get_device_info(silent: bool = True) -> str: ...
