from _typeshed import Incomplete
from dynamo_onnx_helper import DynamoOnnxHelper
from fusion_base import Fusion
from fusion_options import AttentionOpType, FusionOptions as FusionOptions
from onnx import ModelProto as ModelProto, NodeProto as NodeProto
from onnx_model import OnnxModel

logger: Incomplete

class ProcessGemmWFunc:
    def __call__(self, x): ...

class ProcessMatMulQFunc:
    def __call__(self, x): ...

class ProcessMatMulKFunc:
    def __call__(self, x): ...

class ProcessMatMulVFunc:
    def __call__(self, x): ...

class ProcessBiasQFunc:
    def __call__(self, x): ...

class ProcessBiasKFunc:
    def __call__(self, x): ...

class ProcessBiasVFunc:
    def __call__(self, x): ...

class ProcessRotCacheFunc:
    def __call__(self, x): ...

class Fission(Fusion):
    def __init__(self, model: OnnxModel, nodes_to_find: list[str]) -> None: ...
    attn_op_type: Incomplete
    def set_attention_op_type(self, attn_op_type: AttentionOpType): ...
    def get_uname(self, layer_id, name): ...
    def get_edge_by_name(self, edges, name): ...
    def get_input_by_name(self, node, name): ...
    def get_output_by_name(self, node, name): ...
    def process_initializer(self, initializer_name, functor, custom_name=None): ...
    def add_fp32_value_info(self, name) -> None: ...
    def add_int64_value_info(self, name) -> None: ...
    def replace_fp32_value_info(self, name, shape) -> None: ...
    def set_unique_name_and_add_nodes(self, subgraph_nodes: list[NodeProto], layer_id: int, layer_known_edges_names: list[str]): ...
    def layernorm(self, inputs: list[str], outputs: list[str], prefix: str = ''): ...
    def gemm(self, inputs: list[str], outputs: list[str], prefix: str = ''): ...
    def rotary(self, inputs: list[str], outputs: list[str], prefix: str = '', rot_dim: int = 32, num_heads: int = 32): ...
    def fastgelu(self, inputs: list[str], outputs: list[str], prefix: str = ''): ...
    def add(self, inputs: list[str], outputs: list[str], prefix: str = ''): ...
    def mha(self, inputs: list[str], outputs: list[str], prefix: str = '', num_heads: int = 32): ...
    def gqa(self, inputs: list[str], outputs: list[str], prefix: str = '', num_heads: int = 32): ...
    def attention(self, inputs: list[str], outputs: list[str], prefix: str = '', num_heads: int = 32): ...
    def paged_attn(self, inputs: list[str], outputs: list[str], prefix: str = '', num_heads: int = 32, head_size: int = 80, scale: float = 0.11180339753627777): ...

class Phi2PreProcessor(DynamoOnnxHelper):
    num_hidden_layers: int
    num_attention_heads: Incomplete
    hidden_size: Incomplete
    func_name: str
    def __init__(self, model: ModelProto, num_heads: int, hidden_size: int) -> None: ...
    def get_phi2_edge_dict(self) -> dict: ...
    def simplify_phi2_op_type(self) -> None: ...
    use_attn: Incomplete
    use_vllm: Incomplete
    def process_graph_io(self, attn_op_type: AttentionOpType): ...
    def preprocess_onnx(self, attn_op_type: AttentionOpType): ...

class FissionTransformerEmbeddingPhi(Fission):
    def __init__(self, model: OnnxModel) -> None: ...
    prune_graph: bool
    def fuse(self, node, input_name_to_nodes, output_name_to_node) -> None: ...

class FissionTransformerLayerNormPhi(Fission):
    def __init__(self, model: OnnxModel) -> None: ...
    prune_graph: bool
    def fuse(self, node, input_name_to_nodes, output_name_to_node) -> None: ...

class FissionTransformerCausalLMHeadPhi(Fission):
    def __init__(self, model: OnnxModel) -> None: ...
    prune_graph: bool
    def fuse(self, node, input_name_to_nodes, output_name_to_node) -> None: ...

class FissionTransformerBlockPhi(Fission):
    num_heads: Incomplete
    func_to_layer_id: Incomplete
    def __init__(self, model: OnnxModel, num_heads: int) -> None: ...
    def get_layer_id(self, node): ...
    def get_gqa_aux_nodes(self): ...
    def pack_qkv_gemm(self, q_w, k_w, v_w, q_b, k_b, v_b, weight_name, bias_name): ...
    prune_graph: bool
    def fuse(self, node, input_name_to_nodes, output_name_to_node) -> None: ...

class PhiOnnxModel(OnnxModel):
    phi2_preprocessor: Incomplete
    fission_transformer_block: Incomplete
    fission_causal_lm_head: Incomplete
    fission_transformer_layernorm: Incomplete
    fission_transformer_embedding: Incomplete
    def __init__(self, model: ModelProto, num_heads: int, hidden_size: int) -> None: ...
    fuse_sln: Incomplete
    fuse_bias_sln: Incomplete
    def optimize(self, options: FusionOptions | None = None, add_dynamic_axes: bool = False): ...
    def get_fused_operator_statistics(self): ...
    def is_fully_optimized(self, fused_op_count=None): ...
