from _typeshed import Incomplete
from fusion_attention import AttentionMask, FusionAttention
from fusion_base import Fusion
from onnx import NodeProto as NodeProto
from onnx_model import OnnxModel as OnnxModel
from onnx_model_bert import BertOnnxModel

logger: Incomplete

class FusionT5Attention(FusionAttention):
    static_kv: int
    def __init__(self, model: OnnxModel, hidden_size: int, num_heads: int, attention_mask: AttentionMask) -> None: ...
    def make_attention_node(self, mask_index: str | None, q_matmul: NodeProto, k_matmul: NodeProto, v_matmul: NodeProto, num_heads: int, hidden_size: int, input: str, output: str, attn_bias: str | None, scale: float) -> NodeProto | None: ...
    def create_mha_node(self, query: str, key: str, value: str, mask_index: str | None, attn_bias: str | None, past_key: str | None, past_value: str | None, output: str, present_key: str | None, present_value: str | None, num_heads: int, hidden_size: int) -> NodeProto | None: ...
    def fuse(self, node, input_name_to_nodes, output_name_to_node) -> None: ...
    mask_filter_value: Incomplete
    prune_graph: bool
    def fuse_t5_encoder(self, softmax_node, input_name_to_nodes, output_name_to_node): ...
    def fuse_t5_decoder(self, softmax_node, input_name_to_nodes, output_name_to_node) -> None: ...

class FusionRelativePositionBiasBlock(Fusion):
    def __init__(self, model: OnnxModel) -> None: ...
    prune_graph: bool
    def fuse(self, node, input_name_to_nodes, output_name_to_node) -> None: ...

class T5OnnxModel(BertOnnxModel):
    attention_mask: Incomplete
    attention_fusion: Incomplete
    layer_norm_fusion: Incomplete
    skip_layer_norm_fusion: Incomplete
    rpb_fusion: Incomplete
    def __init__(self, model, num_heads: int = 0, hidden_size: int = 0) -> None: ...
    def fuse_attention(self) -> None: ...
    def fuse_layer_norm(self) -> None: ...
    def fuse_skip_layer_norm(self, shape_infer: bool = True) -> None: ...
    def adjust_rel_pos_bis_length_input(self) -> None: ...
    def remove_extended_mask_decoder_init(self) -> None: ...
    def remove_extended_mask_decoder(self) -> None: ...
    def preprocess(self) -> None: ...
    def postprocess(self) -> None: ...
