from _typeshed import Incomplete
from fusion_options import FusionOptions as FusionOptions
from onnx import ModelProto as ModelProto
from onnx_model import OnnxModel

logger: Incomplete

class BertOnnxModel(OnnxModel):
    num_heads: Incomplete
    hidden_size: Incomplete
    attention_mask: Incomplete
    attention_fusion: Incomplete
    qordered_attention_fusion: Incomplete
    utils: Incomplete
    def __init__(self, model: ModelProto, num_heads: int = 0, hidden_size: int = 0) -> None: ...
    def fuse_constant_fold(self) -> None: ...
    def fuse_attention(self) -> None: ...
    def fuse_gelu(self) -> None: ...
    def fuse_bias_gelu(self, is_fastgelu) -> None: ...
    def gelu_approximation(self) -> None: ...
    def fuse_gemm_fast_gelu(self) -> None: ...
    def fuse_add_bias_skip_layer_norm(self) -> None: ...
    def fuse_reshape(self) -> None: ...
    def fuse_shape(self) -> None: ...
    def fuse_embed_layer(self, use_mask_index) -> None: ...
    def fuse_layer_norm(self) -> None: ...
    def fuse_simplified_layer_norm(self) -> None: ...
    def fuse_skip_layer_norm(self, shape_infer: bool = True) -> None: ...
    def fuse_skip_simplified_layer_norm(self) -> None: ...
    def fuse_rotary_embeddings(self): ...
    def fuse_qordered_mamtul(self) -> None: ...
    def get_graph_inputs_from_node_type(self, op_type: str, input_indices: list[int], casted: bool): ...
    def get_graph_inputs_from_fused_nodes(self, casted: bool): ...
    def change_graph_inputs_to_int32(self) -> None: ...
    def use_dynamic_axes(self, dynamic_batch_dim: str = 'batch_size', dynamic_seq_len: str = 'max_seq_len') -> None: ...
    def preprocess(self) -> None: ...
    def adjust_reshape_and_expand(self) -> None: ...
    def clean_graph(self) -> None: ...
    def postprocess(self) -> None: ...
    def optimize(self, options: FusionOptions | None = None, add_dynamic_axes: bool = False): ...
    def get_fused_operator_statistics(self): ...
    def is_fully_optimized(self, fused_op_count=None): ...
    def convert_to_packing_mode(self, use_symbolic_shape_infer: bool = False): ...
