from _typeshed import Incomplete
from fusion_options import FusionOptions as FusionOptions
from onnx import ModelProto as ModelProto
from onnx_model_bert import BertOnnxModel

logger: Incomplete

class MmditOnnxModel(BertOnnxModel):
    def __init__(self, model: ModelProto, num_heads: int = 0, hidden_size: int = 0) -> None: ...
    def postprocess(self) -> None: ...
    def fuse_layer_norm(self) -> None: ...
    def fuse_multi_head_attention(self) -> None: ...
    def optimize(self, options: FusionOptions | None = None, add_dynamic_axes: bool = False): ...
    def get_fused_operator_statistics(self): ...
