from _typeshed import Incomplete
from onnx import GraphProto, ModelProto as ModelProto, NodeProto as NodeProto, TensorProto, ValueInfoProto
from shape_infer_helper import SymbolicShapeInferenceHelper

logger: Incomplete

class OnnxModel:
    def __init__(self, model) -> None: ...
    model: ModelProto
    shape_infer_helper: SymbolicShapeInferenceHelper
    enable_shape_infer: bool
    all_graphs: list[GraphProto] | None
    def initialize(self, model) -> None: ...
    def disable_shape_inference(self) -> None: ...
    def infer_runtime_shape(self, dynamic_axis_mapping={}, update: bool = False): ...
    def input_name_to_nodes(self, exclude_subgraphs: bool = False): ...
    def output_name_to_node(self, exclude_subgraphs: bool = False): ...
    def functions(self): ...
    def nodes(self): ...
    def graph(self): ...
    def graphs(self): ...
    def get_graphs_input_names(self): ...
    def get_graphs_output_names(self): ...
    def get_graph_by_node(self, node): ...
    def get_graph_by_name(self, graph_name): ...
    def get_topological_insert_id(self, graph, outputs): ...
    def remove_node(self, node) -> None: ...
    def remove_nodes(self, nodes_to_remove) -> None: ...
    def add_node(self, node, graph_name=None) -> None: ...
    def add_nodes(self, nodes_to_add, node_name_to_graph_name=None) -> None: ...
    def add_initializer(self, tensor, graph_name=None) -> None: ...
    def add_input(self, input, graph_name=None) -> None: ...
    @staticmethod
    def replace_node_input(node, old_input_name, new_input_name) -> None: ...
    def replace_input_of_all_nodes(self, old_input_name, new_input_name) -> None: ...
    @staticmethod
    def replace_node_output(node, old_output_name, new_output_name) -> None: ...
    def replace_output_of_all_nodes(self, old_output_name, new_output_name) -> None: ...
    def get_initializer(self, name): ...
    def get_nodes_by_op_type(self, op_type): ...
    def get_children(self, node, input_name_to_nodes=None, output_index=None): ...
    def get_parents(self, node, output_name_to_node=None): ...
    def get_parent(self, node, i, output_name_to_node=None): ...
    def match_first_parent(self, node, parent_op_type, output_name_to_node, exclude=[]): ...
    def match_parent(self, node, parent_op_type, input_index=None, output_name_to_node=None, exclude=[], return_indice=None): ...
    def match_parent_paths(self, node, paths, output_name_to_node): ...
    def match_parent_paths_all(self, node, paths, output_name_to_node): ...
    def match_parent_path(self, node, parent_op_types, parent_input_index=None, output_name_to_node=None, return_indice=None): ...
    def find_first_child_by_type(self, node, child_type, input_name_to_nodes=None, recursive: bool = True): ...
    def match_child_path(self, node, child_op_types, edges: list[tuple[int, int]] | None = None, input_name_to_nodes=None, exclude=[]): ...
    def find_first_parent_by_type(self, node, parent_type, output_name_to_node=None, recursive: bool = True): ...
    def get_constant_value(self, output_name): ...
    def get_constant_input(self, node): ...
    def find_constant_input(self, node, expected_value, delta: float = 1e-06): ...
    def is_constant_with_specified_dimension(self, output_name, dimensions, description): ...
    def has_constant_input(self, node, expected_value, delta: float = 1e-06): ...
    def get_children_subgraph_nodes(self, root_node, stop_nodes, input_name_to_nodes=None): ...
    def tensor_shape_to_list(self, tensor_type): ...
    def get_dtype(self, name: str, symbolic_shape_helper: SymbolicShapeInferenceHelper | None = None): ...
    def get_shape(self, name: str, symbolic_shape_helper: SymbolicShapeInferenceHelper | None = None): ...
    @staticmethod
    def get_node_attribute(node: NodeProto, attribute_name: str): ...
    def remove_cascaded_cast_nodes(self) -> None: ...
    def remove_useless_cast_nodes(self) -> None: ...
    def convert_model_float32_to_float16(self, cast_input_output: bool = True) -> None: ...
    def convert_float_to_float16(self, use_symbolic_shape_infer: bool = True, **kwargs) -> None: ...
    def create_node_name(self, op_type, name_prefix=None): ...
    def find_graph_input(self, input_name): ...
    def find_graph_output(self, output_name): ...
    def get_parent_subgraph_nodes(self, node, stop_nodes, output_name_to_node=None): ...
    def get_graph_inputs(self, current_node, recursive: bool = False): ...
    @staticmethod
    def input_index(node_output, child_node): ...
    def remove_unused_constant(self) -> None: ...
    def prune_graph(self, outputs=None, allow_remove_graph_inputs: bool = True): ...
    def update_graph(self, verbose: bool = False, allow_remove_graph_inputs: bool = False) -> None: ...
    def is_safe_to_fuse_nodes(self, nodes_to_remove, keep_outputs, input_name_to_nodes, output_name_to_node): ...
    @staticmethod
    def graph_topological_sort(graph, is_deterministic: bool = False): ...
    def topological_sort(self, is_deterministic: bool = False, dump_model_on_failure: bool = False) -> None: ...
    @staticmethod
    def save(model, output_path, save_as_external_data: bool = False, all_tensors_to_one_file: bool = True, size_threshold: int = 1024, convert_attribute: bool = False) -> None: ...
    def save_model_to_file(self, output_path, use_external_data_format: bool = False, all_tensors_to_one_file: bool = True, size_threshold: int = 1024, convert_attribute: bool = False) -> None: ...
    def get_graph_inputs_excluding_initializers(self): ...
    def get_opset_version(self): ...
    def get_operator_statistics(self, include_domain: bool = False): ...
    @staticmethod
    def to_data_hash(tensor: TensorProto, base_dir: str = '') -> int: ...
    @staticmethod
    def has_same_value(tensor1: TensorProto, tensor2: TensorProto, signature_cache1: dict | None = None, signature_cache2: dict | None = None, rtol: float = 1e-05, atol: float = 1e-08) -> bool: ...
    def remove_initializer(self, tensor) -> None: ...
    def remove_duplicated_initializer(self, cache: dict | None): ...
    def add_prefix_to_names(self, prefix: str): ...
    def clean_shape_infer(self) -> None: ...
    def use_float16(self): ...
    def change_graph_input_type(self, graph_input: ValueInfoProto, new_type: int): ...
    def change_graph_output_type(self, graph_output: ValueInfoProto, new_type: int): ...
    def rename_graph_output(self, old_name: str, new_name: str): ...
