from _typeshed import Incomplete
from fusion_options import FusionOptions as FusionOptions
from onnx import ModelProto as ModelProto
from onnx_model_bert import BertOnnxModel

logger: Incomplete

class UnetOnnxModel(BertOnnxModel):
    def __init__(self, model: ModelProto, num_heads: int = 0, hidden_size: int = 0) -> None: ...
    def preprocess(self) -> None: ...
    def postprocess(self) -> None: ...
    def remove_useless_div(self) -> None: ...
    def convert_conv_to_nhwc(self) -> None: ...
    def merge_adjacent_transpose(self) -> None: ...
    def fuse_multi_head_attention(self, options: FusionOptions | None = None): ...
    def fuse_bias_add(self) -> None: ...
    def optimize(self, options: FusionOptions | None = None): ...
    def get_fused_operator_statistics(self): ...
