from _typeshed import Incomplete
from fusion_options import FusionOptions
from onnx import ModelProto
from onnx_model import OnnxModel

logger: Incomplete
MODEL_TYPES: Incomplete

def optimize_by_onnxruntime(onnx_model: str | ModelProto | None = None, use_gpu: bool = False, optimized_model_path: str | None = None, opt_level: int | None = 99, disabled_optimizers: list[str] = [], verbose: bool = False, save_as_external_data: bool = False, external_data_filename: str = '', external_data_file_threshold: int = 1024, *, provider: str | None = None, **deprecated_kwargs) -> str: ...
def optimize_by_fusion(model: ModelProto, model_type: str = 'bert', num_heads: int = 0, hidden_size: int = 0, optimization_options: FusionOptions | None = None) -> OnnxModel: ...
def optimize_model(input: str | ModelProto, model_type: str = 'bert', num_heads: int = 0, hidden_size: int = 0, optimization_options: FusionOptions | None = None, opt_level: int | None = None, use_gpu: bool = False, only_onnxruntime: bool = False, verbose: bool = False, *, provider: str | None = None) -> OnnxModel: ...
def get_fusion_statistics(optimized_model_path: str) -> dict[str, int]: ...
def main() -> None: ...
