import torch
from _typeshed import Incomplete

logger: Incomplete

class PastKeyValuesHelper:
    @staticmethod
    def get_past_names(num_layers, present: bool = False): ...
    @staticmethod
    def group_by_self_or_cross(present_key_values): ...
    @staticmethod
    def group_by_layer(past, num_layers): ...
    @staticmethod
    def back_group_by_layer(past_key_values: tuple[tuple[torch.Tensor]]): ...
    @staticmethod
    def group_by_self_and_cross(present_key_values: tuple[torch.Tensor], concat: bool = False): ...
    @staticmethod
    def get_input_names(past_key_values: tuple[tuple[torch.Tensor]], encoder: bool = True): ...
