def parse_arguments(argv=None): ...
def run_profile(onnx_model_path, use_gpu, provider, basic_optimization, thread_num, all_inputs): ...
def get_dim_from_type_proto(dim): ...
def get_shape_from_type_proto(type_proto): ...
def create_dummy_inputs(onnx_model, batch_size, sequence_length, samples): ...
def create_bert_inputs(onnx_model, batch_size, sequence_length, samples, input_ids_name=None, segment_ids_name=None, input_mask_name=None): ...
def create_gpt2_inputs(onnx_model, batch_size, sequence_length, past_sequence_length, samples): ...
def create_longformer_inputs(onnx_model, batch_size, sequence_length, global_length, samples): ...
def run(args): ...
