from _typeshed import Incomplete
from collections import deque as deque
from onnx_model import OnnxModel
from pathlib import Path as Path

logger: Incomplete
CONSTANT_SHAPE_NAME_PREFIX: str
RESHAPE_INPUT_SHAPE_PREFIX: str

class BertOnnxModelShapeOptimizer(OnnxModel):
    def __init__(self, onnx_model) -> None: ...
    def add_shape_initializer(self, shape): ...
    def get_shape_outputs(self): ...
    def get_reshape_shape_inputs(self): ...
    def add_shape_for_reshape_input(self): ...
    def add_extra_graph_output(self, extra_outputs): ...
    def use_static_input(self, inputs, batch_size: int = 1, max_seq_len: int = 128) -> None: ...
    def create_dummy_inputs(self, input_ids, segment_ids, input_mask, batch_size, sequence_length, elem_type, dictionary_size: int = 8): ...
    bert_inputs: Incomplete
    def shape_optimization(self, temp_model_path, input_ids, segment_ids, input_mask, output_names, batch_size, sequence_length, enable_shape_opt, enable_reshape_opt, verbose) -> None: ...
    def update_target_shape(self, shapes, shape_input, input_shape, verbose) -> None: ...
    def validate_input(self, input: str): ...
    def validate_outputs(self, output_names: list[str]): ...
    def optimize(self, output_path: str, input_ids: str, segment_ids: str, input_mask: str, enable_shape_opt: bool, enable_reshape_opt: bool, output_names: list[str] | None = None, batch_size: int = 1, sequence_length: int = 128, verbose: bool = False): ...

def parse_arguments(): ...
def setup_logging(verbose) -> None: ...
def main() -> None: ...
