import numpy as np
from _typeshed import Incomplete

def compute_logistic(val: float) -> float: ...

logistic: Incomplete

def compute_softmax_zero(values: np.ndarray) -> np.ndarray: ...
def softmax_zero(values: np.ndarray) -> np.ndarray: ...
def softmax(values: np.ndarray) -> np.ndarray: ...
def erf_inv(x: float) -> float: ...
def compute_probit(val: float) -> float: ...

probit: Incomplete

def expit(x: np.ndarray) -> np.ndarray: ...
