from onnx.reference.ops.aionnxml._common_classifier import compute_logistic as compute_logistic, compute_probit as compute_probit, compute_softmax_zero as compute_softmax_zero, logistic as logistic, softmax as softmax, softmax_zero as softmax_zero
from onnx.reference.ops.aionnxml._op_run_aionnxml import OpRunAiOnnxMl as OpRunAiOnnxMl
from onnx.reference.ops.aionnxml.op_svm_helper import SVMCommon as SVMCommon

def multiclass_probability(k, R): ...
def sigmoid_probability(score, proba, probb): ...
def write_scores(n_classes, scores, post_transform, add_second_class): ...
def set_score_svm(max_weight, maxclass, has_proba, weights_are_all_positive_, classlabels, posclass, negclass): ...

class SVMClassifier(OpRunAiOnnxMl): ...
