import numpy as np
from _typeshed import Incomplete

class TreeEnsembleAttributes:
    def __init__(self) -> None: ...
    def add(self, name, value) -> None: ...

class TreeEnsemble:
    atts: Incomplete
    tree_ids: Incomplete
    root_index: Incomplete
    node_index: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def leaf_index_tree(self, X: np.ndarray, tree_id: int) -> int: ...
    def leave_index_tree(self, X: np.ndarray) -> np.ndarray: ...
