from _typeshed import Incomplete

np: Incomplete

class Attribute:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsAttribute(cls, buf, offset: int = 0): ...
    @classmethod
    def AttributeBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Name(self): ...
    def DocString(self): ...
    def Type(self): ...
    def F(self): ...
    def I(self): ...
    def S(self): ...
    def T(self): ...
    def G(self): ...
    def Floats(self, j): ...
    def FloatsAsNumpy(self): ...
    def FloatsLength(self): ...
    def FloatsIsNone(self): ...
    def Ints(self, j): ...
    def IntsAsNumpy(self): ...
    def IntsLength(self): ...
    def IntsIsNone(self): ...
    def Strings(self, j): ...
    def StringsLength(self): ...
    def StringsIsNone(self): ...
    def Tensors(self, j): ...
    def TensorsLength(self): ...
    def TensorsIsNone(self): ...
    def Graphs(self, j): ...
    def GraphsLength(self): ...
    def GraphsIsNone(self): ...

def AttributeStart(builder) -> None: ...
def Start(builder) -> None: ...
def AttributeAddName(builder, name) -> None: ...
def AddName(builder, name) -> None: ...
def AttributeAddDocString(builder, docString) -> None: ...
def AddDocString(builder, docString) -> None: ...
def AttributeAddType(builder, type) -> None: ...
def AddType(builder, type) -> None: ...
def AttributeAddF(builder, f) -> None: ...
def AddF(builder, f) -> None: ...
def AttributeAddI(builder, i) -> None: ...
def AddI(builder, i) -> None: ...
def AttributeAddS(builder, s) -> None: ...
def AddS(builder, s) -> None: ...
def AttributeAddT(builder, t) -> None: ...
def AddT(builder, t) -> None: ...
def AttributeAddG(builder, g) -> None: ...
def AddG(builder, g) -> None: ...
def AttributeAddFloats(builder, floats) -> None: ...
def AddFloats(builder, floats) -> None: ...
def AttributeStartFloatsVector(builder, numElems): ...
def StartFloatsVector(builder, numElems: int) -> int: ...
def AttributeAddInts(builder, ints) -> None: ...
def AddInts(builder, ints) -> None: ...
def AttributeStartIntsVector(builder, numElems): ...
def StartIntsVector(builder, numElems: int) -> int: ...
def AttributeAddStrings(builder, strings) -> None: ...
def AddStrings(builder, strings) -> None: ...
def AttributeStartStringsVector(builder, numElems): ...
def StartStringsVector(builder, numElems: int) -> int: ...
def AttributeAddTensors(builder, tensors) -> None: ...
def AddTensors(builder, tensors) -> None: ...
def AttributeStartTensorsVector(builder, numElems): ...
def StartTensorsVector(builder, numElems: int) -> int: ...
def AttributeAddGraphs(builder, graphs) -> None: ...
def AddGraphs(builder, graphs) -> None: ...
def AttributeStartGraphsVector(builder, numElems): ...
def StartGraphsVector(builder, numElems: int) -> int: ...
def AttributeEnd(builder): ...
def End(builder): ...
