from _typeshed import Incomplete

np: Incomplete

class DeprecatedSubGraphSessionState:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsDeprecatedSubGraphSessionState(cls, buf, offset: int = 0): ...
    @classmethod
    def DeprecatedSubGraphSessionStateBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def GraphId(self): ...
    def SessionState(self): ...

def DeprecatedSubGraphSessionStateStart(builder) -> None: ...
def Start(builder) -> None: ...
def DeprecatedSubGraphSessionStateAddGraphId(builder, graphId) -> None: ...
def AddGraphId(builder, graphId) -> None: ...
def DeprecatedSubGraphSessionStateAddSessionState(builder, sessionState) -> None: ...
def AddSessionState(builder, sessionState) -> None: ...
def DeprecatedSubGraphSessionStateEnd(builder): ...
def End(builder): ...
