from _typeshed import Incomplete

np: Incomplete

class DeprecatedKernelCreateInfos:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsDeprecatedKernelCreateInfos(cls, buf, offset: int = 0): ...
    @classmethod
    def DeprecatedKernelCreateInfosBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def NodeIndices(self, j): ...
    def NodeIndicesAsNumpy(self): ...
    def NodeIndicesLength(self): ...
    def NodeIndicesIsNone(self): ...
    def KernelDefHashes(self, j): ...
    def KernelDefHashesAsNumpy(self): ...
    def KernelDefHashesLength(self): ...
    def KernelDefHashesIsNone(self): ...

def DeprecatedKernelCreateInfosStart(builder) -> None: ...
def Start(builder) -> None: ...
def DeprecatedKernelCreateInfosAddNodeIndices(builder, nodeIndices) -> None: ...
def AddNodeIndices(builder, nodeIndices) -> None: ...
def DeprecatedKernelCreateInfosStartNodeIndicesVector(builder, numElems): ...
def StartNodeIndicesVector(builder, numElems: int) -> int: ...
def DeprecatedKernelCreateInfosAddKernelDefHashes(builder, kernelDefHashes) -> None: ...
def AddKernelDefHashes(builder, kernelDefHashes) -> None: ...
def DeprecatedKernelCreateInfosStartKernelDefHashesVector(builder, numElems): ...
def StartKernelDefHashesVector(builder, numElems: int) -> int: ...
def DeprecatedKernelCreateInfosEnd(builder): ...
def End(builder): ...
