from _typeshed import Incomplete

np: Incomplete

class DeprecatedSessionState:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsDeprecatedSessionState(cls, buf, offset: int = 0): ...
    @classmethod
    def DeprecatedSessionStateBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Kernels(self): ...
    def SubGraphSessionStates(self, j): ...
    def SubGraphSessionStatesLength(self): ...
    def SubGraphSessionStatesIsNone(self): ...

def DeprecatedSessionStateStart(builder) -> None: ...
def Start(builder) -> None: ...
def DeprecatedSessionStateAddKernels(builder, kernels) -> None: ...
def AddKernels(builder, kernels) -> None: ...
def DeprecatedSessionStateAddSubGraphSessionStates(builder, subGraphSessionStates) -> None: ...
def AddSubGraphSessionStates(builder, subGraphSessionStates) -> None: ...
def DeprecatedSessionStateStartSubGraphSessionStatesVector(builder, numElems): ...
def StartSubGraphSessionStatesVector(builder, numElems: int) -> int: ...
def DeprecatedSessionStateEnd(builder): ...
def End(builder): ...
