from _typeshed import Incomplete

np: Incomplete

class Dimension:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsDimension(cls, buf, offset: int = 0): ...
    @classmethod
    def DimensionBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Value(self): ...
    def Denotation(self): ...

def DimensionStart(builder) -> None: ...
def Start(builder) -> None: ...
def DimensionAddValue(builder, value) -> None: ...
def AddValue(builder, value) -> None: ...
def DimensionAddDenotation(builder, denotation) -> None: ...
def AddDenotation(builder, denotation) -> None: ...
def DimensionEnd(builder): ...
def End(builder): ...
