from _typeshed import Incomplete

np: Incomplete

class EdgeEnd:
    @classmethod
    def SizeOf(cls): ...
    def Init(self, buf, pos) -> None: ...
    def NodeIndex(self): ...
    def SrcArgIndex(self): ...
    def DstArgIndex(self): ...

def CreateEdgeEnd(builder, nodeIndex, srcArgIndex, dstArgIndex): ...
