from _typeshed import Incomplete

np: Incomplete

class FloatProperty:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsFloatProperty(cls, buf, offset: int = 0): ...
    @classmethod
    def FloatPropertyBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Name(self): ...
    def Value(self): ...

def FloatPropertyStart(builder) -> None: ...
def Start(builder) -> None: ...
def FloatPropertyAddName(builder, name) -> None: ...
def AddName(builder, name) -> None: ...
def FloatPropertyAddValue(builder, value) -> None: ...
def AddValue(builder, value) -> None: ...
def FloatPropertyEnd(builder): ...
def End(builder): ...
