from _typeshed import Incomplete

np: Incomplete

class Graph:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsGraph(cls, buf, offset: int = 0): ...
    @classmethod
    def GraphBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Initializers(self, j): ...
    def InitializersLength(self): ...
    def InitializersIsNone(self): ...
    def NodeArgs(self, j): ...
    def NodeArgsLength(self): ...
    def NodeArgsIsNone(self): ...
    def Nodes(self, j): ...
    def NodesLength(self): ...
    def NodesIsNone(self): ...
    def MaxNodeIndex(self): ...
    def NodeEdges(self, j): ...
    def NodeEdgesLength(self): ...
    def NodeEdgesIsNone(self): ...
    def Inputs(self, j): ...
    def InputsLength(self): ...
    def InputsIsNone(self): ...
    def Outputs(self, j): ...
    def OutputsLength(self): ...
    def OutputsIsNone(self): ...
    def SparseInitializers(self, j): ...
    def SparseInitializersLength(self): ...
    def SparseInitializersIsNone(self): ...
    def RuntimeOptimizations(self): ...

def GraphStart(builder) -> None: ...
def Start(builder) -> None: ...
def GraphAddInitializers(builder, initializers) -> None: ...
def AddInitializers(builder, initializers) -> None: ...
def GraphStartInitializersVector(builder, numElems): ...
def StartInitializersVector(builder, numElems: int) -> int: ...
def GraphAddNodeArgs(builder, nodeArgs) -> None: ...
def AddNodeArgs(builder, nodeArgs) -> None: ...
def GraphStartNodeArgsVector(builder, numElems): ...
def StartNodeArgsVector(builder, numElems: int) -> int: ...
def GraphAddNodes(builder, nodes) -> None: ...
def AddNodes(builder, nodes) -> None: ...
def GraphStartNodesVector(builder, numElems): ...
def StartNodesVector(builder, numElems: int) -> int: ...
def GraphAddMaxNodeIndex(builder, maxNodeIndex) -> None: ...
def AddMaxNodeIndex(builder, maxNodeIndex) -> None: ...
def GraphAddNodeEdges(builder, nodeEdges) -> None: ...
def AddNodeEdges(builder, nodeEdges) -> None: ...
def GraphStartNodeEdgesVector(builder, numElems): ...
def StartNodeEdgesVector(builder, numElems: int) -> int: ...
def GraphAddInputs(builder, inputs) -> None: ...
def AddInputs(builder, inputs) -> None: ...
def GraphStartInputsVector(builder, numElems): ...
def StartInputsVector(builder, numElems: int) -> int: ...
def GraphAddOutputs(builder, outputs) -> None: ...
def AddOutputs(builder, outputs) -> None: ...
def GraphStartOutputsVector(builder, numElems): ...
def StartOutputsVector(builder, numElems: int) -> int: ...
def GraphAddSparseInitializers(builder, sparseInitializers) -> None: ...
def AddSparseInitializers(builder, sparseInitializers) -> None: ...
def GraphStartSparseInitializersVector(builder, numElems): ...
def StartSparseInitializersVector(builder, numElems: int) -> int: ...
def GraphAddRuntimeOptimizations(builder, runtimeOptimizations) -> None: ...
def AddRuntimeOptimizations(builder, runtimeOptimizations) -> None: ...
def GraphEnd(builder): ...
def End(builder): ...
