from _typeshed import Incomplete

np: Incomplete

class IntProperty:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsIntProperty(cls, buf, offset: int = 0): ...
    @classmethod
    def IntPropertyBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Name(self): ...
    def Value(self): ...

def IntPropertyStart(builder) -> None: ...
def Start(builder) -> None: ...
def IntPropertyAddName(builder, name) -> None: ...
def AddName(builder, name) -> None: ...
def IntPropertyAddValue(builder, value) -> None: ...
def AddValue(builder, value) -> None: ...
def IntPropertyEnd(builder): ...
def End(builder): ...
