from _typeshed import Incomplete

np: Incomplete

class KernelTypeStrArgsEntry:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsKernelTypeStrArgsEntry(cls, buf, offset: int = 0): ...
    @classmethod
    def KernelTypeStrArgsEntryBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def KernelTypeStr(self): ...
    def Args(self, j): ...
    def ArgsLength(self): ...
    def ArgsIsNone(self): ...

def KernelTypeStrArgsEntryStart(builder) -> None: ...
def Start(builder) -> None: ...
def KernelTypeStrArgsEntryAddKernelTypeStr(builder, kernelTypeStr) -> None: ...
def AddKernelTypeStr(builder, kernelTypeStr) -> None: ...
def KernelTypeStrArgsEntryAddArgs(builder, args) -> None: ...
def AddArgs(builder, args) -> None: ...
def KernelTypeStrArgsEntryStartArgsVector(builder, numElems): ...
def StartArgsVector(builder, numElems: int) -> int: ...
def KernelTypeStrArgsEntryEnd(builder): ...
def End(builder): ...
