from _typeshed import Incomplete

np: Incomplete

class KernelTypeStrResolver:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsKernelTypeStrResolver(cls, buf, offset: int = 0): ...
    @classmethod
    def KernelTypeStrResolverBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def OpKernelTypeStrArgs(self, j): ...
    def OpKernelTypeStrArgsLength(self): ...
    def OpKernelTypeStrArgsIsNone(self): ...

def KernelTypeStrResolverStart(builder) -> None: ...
def Start(builder) -> None: ...
def KernelTypeStrResolverAddOpKernelTypeStrArgs(builder, opKernelTypeStrArgs) -> None: ...
def AddOpKernelTypeStrArgs(builder, opKernelTypeStrArgs) -> None: ...
def KernelTypeStrResolverStartOpKernelTypeStrArgsVector(builder, numElems): ...
def StartOpKernelTypeStrArgsVector(builder, numElems: int) -> int: ...
def KernelTypeStrResolverEnd(builder): ...
def End(builder): ...
