from _typeshed import Incomplete

np: Incomplete

class MapType:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsMapType(cls, buf, offset: int = 0): ...
    @classmethod
    def MapTypeBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def KeyType(self): ...
    def ValueType(self): ...

def MapTypeStart(builder) -> None: ...
def Start(builder) -> None: ...
def MapTypeAddKeyType(builder, keyType) -> None: ...
def AddKeyType(builder, keyType) -> None: ...
def MapTypeAddValueType(builder, valueType) -> None: ...
def AddValueType(builder, valueType) -> None: ...
def MapTypeEnd(builder): ...
def End(builder): ...
