from _typeshed import Incomplete

np: Incomplete

class Model:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsModel(cls, buf, offset: int = 0): ...
    @classmethod
    def ModelBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def IrVersion(self): ...
    def OpsetImport(self, j): ...
    def OpsetImportLength(self): ...
    def OpsetImportIsNone(self): ...
    def ProducerName(self): ...
    def ProducerVersion(self): ...
    def Domain(self): ...
    def ModelVersion(self): ...
    def DocString(self): ...
    def Graph(self): ...
    def GraphDocString(self): ...
    def MetadataProps(self, j): ...
    def MetadataPropsLength(self): ...
    def MetadataPropsIsNone(self): ...

def ModelStart(builder) -> None: ...
def Start(builder) -> None: ...
def ModelAddIrVersion(builder, irVersion) -> None: ...
def AddIrVersion(builder, irVersion) -> None: ...
def ModelAddOpsetImport(builder, opsetImport) -> None: ...
def AddOpsetImport(builder, opsetImport) -> None: ...
def ModelStartOpsetImportVector(builder, numElems): ...
def StartOpsetImportVector(builder, numElems: int) -> int: ...
def ModelAddProducerName(builder, producerName) -> None: ...
def AddProducerName(builder, producerName) -> None: ...
def ModelAddProducerVersion(builder, producerVersion) -> None: ...
def AddProducerVersion(builder, producerVersion) -> None: ...
def ModelAddDomain(builder, domain) -> None: ...
def AddDomain(builder, domain) -> None: ...
def ModelAddModelVersion(builder, modelVersion) -> None: ...
def AddModelVersion(builder, modelVersion) -> None: ...
def ModelAddDocString(builder, docString) -> None: ...
def AddDocString(builder, docString) -> None: ...
def ModelAddGraph(builder, graph) -> None: ...
def AddGraph(builder, graph) -> None: ...
def ModelAddGraphDocString(builder, graphDocString) -> None: ...
def AddGraphDocString(builder, graphDocString) -> None: ...
def ModelAddMetadataProps(builder, metadataProps) -> None: ...
def AddMetadataProps(builder, metadataProps) -> None: ...
def ModelStartMetadataPropsVector(builder, numElems): ...
def StartMetadataPropsVector(builder, numElems: int) -> int: ...
def ModelEnd(builder): ...
def End(builder): ...
