from _typeshed import Incomplete

np: Incomplete

class ModuleState:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsModuleState(cls, buf, offset: int = 0): ...
    @classmethod
    def ModuleStateBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def RequiresGradParams(self, j): ...
    def RequiresGradParamsLength(self): ...
    def RequiresGradParamsIsNone(self): ...
    def FrozenParams(self, j): ...
    def FrozenParamsLength(self): ...
    def FrozenParamsIsNone(self): ...
    def IsNominalState(self): ...
    def HasExternalData(self): ...

def ModuleStateStart(builder) -> None: ...
def Start(builder) -> None: ...
def ModuleStateAddRequiresGradParams(builder, requiresGradParams) -> None: ...
def AddRequiresGradParams(builder, requiresGradParams) -> None: ...
def ModuleStateStartRequiresGradParamsVector(builder, numElems): ...
def StartRequiresGradParamsVector(builder, numElems: int) -> int: ...
def ModuleStateAddFrozenParams(builder, frozenParams) -> None: ...
def AddFrozenParams(builder, frozenParams) -> None: ...
def ModuleStateStartFrozenParamsVector(builder, numElems): ...
def StartFrozenParamsVector(builder, numElems: int) -> int: ...
def ModuleStateAddIsNominalState(builder, isNominalState) -> None: ...
def AddIsNominalState(builder, isNominalState) -> None: ...
def ModuleStateAddHasExternalData(builder, hasExternalData) -> None: ...
def AddHasExternalData(builder, hasExternalData) -> None: ...
def ModuleStateEnd(builder): ...
def End(builder): ...
