from _typeshed import Incomplete

np: Incomplete

class NodesToOptimizeIndices:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsNodesToOptimizeIndices(cls, buf, offset: int = 0): ...
    @classmethod
    def NodesToOptimizeIndicesBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def NodeIndices(self, j): ...
    def NodeIndicesAsNumpy(self): ...
    def NodeIndicesLength(self): ...
    def NodeIndicesIsNone(self): ...
    def NumInputs(self): ...
    def NumOutputs(self): ...
    def HasVariadicInput(self): ...
    def HasVariadicOutput(self): ...
    def NumVariadicInputs(self): ...
    def NumVariadicOutputs(self): ...

def NodesToOptimizeIndicesStart(builder) -> None: ...
def Start(builder) -> None: ...
def NodesToOptimizeIndicesAddNodeIndices(builder, nodeIndices) -> None: ...
def AddNodeIndices(builder, nodeIndices) -> None: ...
def NodesToOptimizeIndicesStartNodeIndicesVector(builder, numElems): ...
def StartNodeIndicesVector(builder, numElems: int) -> int: ...
def NodesToOptimizeIndicesAddNumInputs(builder, numInputs) -> None: ...
def AddNumInputs(builder, numInputs) -> None: ...
def NodesToOptimizeIndicesAddNumOutputs(builder, numOutputs) -> None: ...
def AddNumOutputs(builder, numOutputs) -> None: ...
def NodesToOptimizeIndicesAddHasVariadicInput(builder, hasVariadicInput) -> None: ...
def AddHasVariadicInput(builder, hasVariadicInput) -> None: ...
def NodesToOptimizeIndicesAddHasVariadicOutput(builder, hasVariadicOutput) -> None: ...
def AddHasVariadicOutput(builder, hasVariadicOutput) -> None: ...
def NodesToOptimizeIndicesAddNumVariadicInputs(builder, numVariadicInputs) -> None: ...
def AddNumVariadicInputs(builder, numVariadicInputs) -> None: ...
def NodesToOptimizeIndicesAddNumVariadicOutputs(builder, numVariadicOutputs) -> None: ...
def AddNumVariadicOutputs(builder, numVariadicOutputs) -> None: ...
def NodesToOptimizeIndicesEnd(builder): ...
def End(builder): ...
