from _typeshed import Incomplete

np: Incomplete

class NodeEdge:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsNodeEdge(cls, buf, offset: int = 0): ...
    @classmethod
    def NodeEdgeBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def NodeIndex(self): ...
    def InputEdges(self, j): ...
    def InputEdgesLength(self): ...
    def InputEdgesIsNone(self): ...
    def OutputEdges(self, j): ...
    def OutputEdgesLength(self): ...
    def OutputEdgesIsNone(self): ...

def NodeEdgeStart(builder) -> None: ...
def Start(builder) -> None: ...
def NodeEdgeAddNodeIndex(builder, nodeIndex) -> None: ...
def AddNodeIndex(builder, nodeIndex) -> None: ...
def NodeEdgeAddInputEdges(builder, inputEdges) -> None: ...
def AddInputEdges(builder, inputEdges) -> None: ...
def NodeEdgeStartInputEdgesVector(builder, numElems): ...
def StartInputEdgesVector(builder, numElems: int) -> int: ...
def NodeEdgeAddOutputEdges(builder, outputEdges) -> None: ...
def AddOutputEdges(builder, outputEdges) -> None: ...
def NodeEdgeStartOutputEdgesVector(builder, numElems): ...
def StartOutputEdgesVector(builder, numElems: int) -> int: ...
def NodeEdgeEnd(builder): ...
def End(builder): ...
