from _typeshed import Incomplete

np: Incomplete

class OpIdKernelTypeStrArgsEntry:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsOpIdKernelTypeStrArgsEntry(cls, buf, offset: int = 0): ...
    @classmethod
    def OpIdKernelTypeStrArgsEntryBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def OpId(self): ...
    def KernelTypeStrArgs(self, j): ...
    def KernelTypeStrArgsLength(self): ...
    def KernelTypeStrArgsIsNone(self): ...

def OpIdKernelTypeStrArgsEntryStart(builder) -> None: ...
def Start(builder) -> None: ...
def OpIdKernelTypeStrArgsEntryAddOpId(builder, opId) -> None: ...
def AddOpId(builder, opId) -> None: ...
def OpIdKernelTypeStrArgsEntryAddKernelTypeStrArgs(builder, kernelTypeStrArgs) -> None: ...
def AddKernelTypeStrArgs(builder, kernelTypeStrArgs) -> None: ...
def OpIdKernelTypeStrArgsEntryStartKernelTypeStrArgsVector(builder, numElems): ...
def StartKernelTypeStrArgsVector(builder, numElems: int) -> int: ...
def OpIdKernelTypeStrArgsEntryEnd(builder): ...
def End(builder): ...
