from _typeshed import Incomplete

np: Incomplete

class OptimizerGroup:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsOptimizerGroup(cls, buf, offset: int = 0): ...
    @classmethod
    def OptimizerGroupBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def GroupName(self): ...
    def Step(self): ...
    def InitialLearningRate(self): ...
    def OptimizerStates(self, j): ...
    def OptimizerStatesLength(self): ...
    def OptimizerStatesIsNone(self): ...

def OptimizerGroupStart(builder) -> None: ...
def Start(builder) -> None: ...
def OptimizerGroupAddGroupName(builder, groupName) -> None: ...
def AddGroupName(builder, groupName) -> None: ...
def OptimizerGroupAddStep(builder, step) -> None: ...
def AddStep(builder, step) -> None: ...
def OptimizerGroupAddInitialLearningRate(builder, initialLearningRate) -> None: ...
def AddInitialLearningRate(builder, initialLearningRate) -> None: ...
def OptimizerGroupAddOptimizerStates(builder, optimizerStates) -> None: ...
def AddOptimizerStates(builder, optimizerStates) -> None: ...
def OptimizerGroupStartOptimizerStatesVector(builder, numElems): ...
def StartOptimizerStatesVector(builder, numElems: int) -> int: ...
def OptimizerGroupEnd(builder): ...
def End(builder): ...
