from _typeshed import Incomplete

np: Incomplete

class ParameterOptimizerState:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsParameterOptimizerState(cls, buf, offset: int = 0): ...
    @classmethod
    def ParameterOptimizerStateBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def ParamName(self): ...
    def Momentums(self, j): ...
    def MomentumsLength(self): ...
    def MomentumsIsNone(self): ...

def ParameterOptimizerStateStart(builder) -> None: ...
def Start(builder) -> None: ...
def ParameterOptimizerStateAddParamName(builder, paramName) -> None: ...
def AddParamName(builder, paramName) -> None: ...
def ParameterOptimizerStateAddMomentums(builder, momentums) -> None: ...
def AddMomentums(builder, momentums) -> None: ...
def ParameterOptimizerStateStartMomentumsVector(builder, numElems): ...
def StartMomentumsVector(builder, numElems: int) -> int: ...
def ParameterOptimizerStateEnd(builder): ...
def End(builder): ...
