from _typeshed import Incomplete

np: Incomplete

class PropertyBag:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsPropertyBag(cls, buf, offset: int = 0): ...
    @classmethod
    def PropertyBagBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Ints(self, j): ...
    def IntsLength(self): ...
    def IntsIsNone(self): ...
    def Floats(self, j): ...
    def FloatsLength(self): ...
    def FloatsIsNone(self): ...
    def Strings(self, j): ...
    def StringsLength(self): ...
    def StringsIsNone(self): ...

def PropertyBagStart(builder) -> None: ...
def Start(builder) -> None: ...
def PropertyBagAddInts(builder, ints) -> None: ...
def AddInts(builder, ints) -> None: ...
def PropertyBagStartIntsVector(builder, numElems): ...
def StartIntsVector(builder, numElems: int) -> int: ...
def PropertyBagAddFloats(builder, floats) -> None: ...
def AddFloats(builder, floats) -> None: ...
def PropertyBagStartFloatsVector(builder, numElems): ...
def StartFloatsVector(builder, numElems: int) -> int: ...
def PropertyBagAddStrings(builder, strings) -> None: ...
def AddStrings(builder, strings) -> None: ...
def PropertyBagStartStringsVector(builder, numElems): ...
def StartStringsVector(builder, numElems: int) -> int: ...
def PropertyBagEnd(builder): ...
def End(builder): ...
