from _typeshed import Incomplete

np: Incomplete

class RuntimeOptimizationRecord:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsRuntimeOptimizationRecord(cls, buf, offset: int = 0): ...
    @classmethod
    def RuntimeOptimizationRecordBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def ActionId(self): ...
    def NodesToOptimizeIndices(self): ...
    def ProducedOpIds(self, j): ...
    def ProducedOpIdsLength(self): ...
    def ProducedOpIdsIsNone(self): ...

def RuntimeOptimizationRecordStart(builder) -> None: ...
def Start(builder) -> None: ...
def RuntimeOptimizationRecordAddActionId(builder, actionId) -> None: ...
def AddActionId(builder, actionId) -> None: ...
def RuntimeOptimizationRecordAddNodesToOptimizeIndices(builder, nodesToOptimizeIndices) -> None: ...
def AddNodesToOptimizeIndices(builder, nodesToOptimizeIndices) -> None: ...
def RuntimeOptimizationRecordAddProducedOpIds(builder, producedOpIds) -> None: ...
def AddProducedOpIds(builder, producedOpIds) -> None: ...
def RuntimeOptimizationRecordStartProducedOpIdsVector(builder, numElems): ...
def StartProducedOpIdsVector(builder, numElems: int) -> int: ...
def RuntimeOptimizationRecordEnd(builder): ...
def End(builder): ...
