from _typeshed import Incomplete

np: Incomplete

class RuntimeOptimizationRecordContainerEntry:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsRuntimeOptimizationRecordContainerEntry(cls, buf, offset: int = 0): ...
    @classmethod
    def RuntimeOptimizationRecordContainerEntryBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def OptimizerName(self): ...
    def RuntimeOptimizationRecords(self, j): ...
    def RuntimeOptimizationRecordsLength(self): ...
    def RuntimeOptimizationRecordsIsNone(self): ...

def RuntimeOptimizationRecordContainerEntryStart(builder) -> None: ...
def Start(builder) -> None: ...
def RuntimeOptimizationRecordContainerEntryAddOptimizerName(builder, optimizerName) -> None: ...
def AddOptimizerName(builder, optimizerName) -> None: ...
def RuntimeOptimizationRecordContainerEntryAddRuntimeOptimizationRecords(builder, runtimeOptimizationRecords) -> None: ...
def AddRuntimeOptimizationRecords(builder, runtimeOptimizationRecords) -> None: ...
def RuntimeOptimizationRecordContainerEntryStartRuntimeOptimizationRecordsVector(builder, numElems): ...
def StartRuntimeOptimizationRecordsVector(builder, numElems: int) -> int: ...
def RuntimeOptimizationRecordContainerEntryEnd(builder): ...
def End(builder): ...
