from _typeshed import Incomplete

np: Incomplete

class RuntimeOptimizations:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsRuntimeOptimizations(cls, buf, offset: int = 0): ...
    @classmethod
    def RuntimeOptimizationsBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Records(self, j): ...
    def RecordsLength(self): ...
    def RecordsIsNone(self): ...

def RuntimeOptimizationsStart(builder) -> None: ...
def Start(builder) -> None: ...
def RuntimeOptimizationsAddRecords(builder, records) -> None: ...
def AddRecords(builder, records) -> None: ...
def RuntimeOptimizationsStartRecordsVector(builder, numElems): ...
def StartRecordsVector(builder, numElems: int) -> int: ...
def RuntimeOptimizationsEnd(builder): ...
def End(builder): ...
