from _typeshed import Incomplete

np: Incomplete

class SequenceType:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsSequenceType(cls, buf, offset: int = 0): ...
    @classmethod
    def SequenceTypeBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def ElemType(self): ...

def SequenceTypeStart(builder) -> None: ...
def Start(builder) -> None: ...
def SequenceTypeAddElemType(builder, elemType) -> None: ...
def AddElemType(builder, elemType) -> None: ...
def SequenceTypeEnd(builder): ...
def End(builder): ...
