from _typeshed import Incomplete

np: Incomplete

class Shape:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsShape(cls, buf, offset: int = 0): ...
    @classmethod
    def ShapeBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Dim(self, j): ...
    def DimLength(self): ...
    def DimIsNone(self): ...

def ShapeStart(builder) -> None: ...
def Start(builder) -> None: ...
def ShapeAddDim(builder, dim) -> None: ...
def AddDim(builder, dim) -> None: ...
def ShapeStartDimVector(builder, numElems): ...
def StartDimVector(builder, numElems: int) -> int: ...
def ShapeEnd(builder): ...
def End(builder): ...
