from _typeshed import Incomplete

np: Incomplete

class SparseTensor:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsSparseTensor(cls, buf, offset: int = 0): ...
    @classmethod
    def SparseTensorBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Values(self): ...
    def Indices(self): ...
    def Dims(self, j): ...
    def DimsAsNumpy(self): ...
    def DimsLength(self): ...
    def DimsIsNone(self): ...

def SparseTensorStart(builder) -> None: ...
def Start(builder) -> None: ...
def SparseTensorAddValues(builder, values) -> None: ...
def AddValues(builder, values) -> None: ...
def SparseTensorAddIndices(builder, indices) -> None: ...
def AddIndices(builder, indices) -> None: ...
def SparseTensorAddDims(builder, dims) -> None: ...
def AddDims(builder, dims) -> None: ...
def SparseTensorStartDimsVector(builder, numElems): ...
def StartDimsVector(builder, numElems: int) -> int: ...
def SparseTensorEnd(builder): ...
def End(builder): ...
