from _typeshed import Incomplete

np: Incomplete

class StringStringEntry:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsStringStringEntry(cls, buf, offset: int = 0): ...
    @classmethod
    def StringStringEntryBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Key(self): ...
    def Value(self): ...

def StringStringEntryStart(builder) -> None: ...
def Start(builder) -> None: ...
def StringStringEntryAddKey(builder, key) -> None: ...
def AddKey(builder, key) -> None: ...
def StringStringEntryAddValue(builder, value) -> None: ...
def AddValue(builder, value) -> None: ...
def StringStringEntryEnd(builder): ...
def End(builder): ...
