from _typeshed import Incomplete

np: Incomplete

class StringProperty:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsStringProperty(cls, buf, offset: int = 0): ...
    @classmethod
    def StringPropertyBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Name(self): ...
    def Value(self): ...

def StringPropertyStart(builder) -> None: ...
def Start(builder) -> None: ...
def StringPropertyAddName(builder, name) -> None: ...
def AddName(builder, name) -> None: ...
def StringPropertyAddValue(builder, value) -> None: ...
def AddValue(builder, value) -> None: ...
def StringPropertyEnd(builder): ...
def End(builder): ...
