from _typeshed import Incomplete

np: Incomplete

class Tensor:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsTensor(cls, buf, offset: int = 0): ...
    @classmethod
    def TensorBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Name(self): ...
    def DocString(self): ...
    def Dims(self, j): ...
    def DimsAsNumpy(self): ...
    def DimsLength(self): ...
    def DimsIsNone(self): ...
    def DataType(self): ...
    def RawData(self, j): ...
    def RawDataAsNumpy(self): ...
    def RawDataLength(self): ...
    def RawDataIsNone(self): ...
    def StringData(self, j): ...
    def StringDataLength(self): ...
    def StringDataIsNone(self): ...
    def ExternalDataOffset(self): ...

def TensorStart(builder) -> None: ...
def Start(builder) -> None: ...
def TensorAddName(builder, name) -> None: ...
def AddName(builder, name) -> None: ...
def TensorAddDocString(builder, docString) -> None: ...
def AddDocString(builder, docString) -> None: ...
def TensorAddDims(builder, dims) -> None: ...
def AddDims(builder, dims) -> None: ...
def TensorStartDimsVector(builder, numElems): ...
def StartDimsVector(builder, numElems: int) -> int: ...
def TensorAddDataType(builder, dataType) -> None: ...
def AddDataType(builder, dataType) -> None: ...
def TensorAddRawData(builder, rawData) -> None: ...
def AddRawData(builder, rawData) -> None: ...
def TensorStartRawDataVector(builder, numElems): ...
def StartRawDataVector(builder, numElems: int) -> int: ...
def TensorAddStringData(builder, stringData) -> None: ...
def AddStringData(builder, stringData) -> None: ...
def TensorStartStringDataVector(builder, numElems): ...
def StartStringDataVector(builder, numElems: int) -> int: ...
def TensorAddExternalDataOffset(builder, externalDataOffset) -> None: ...
def AddExternalDataOffset(builder, externalDataOffset) -> None: ...
def TensorEnd(builder): ...
def End(builder): ...
