from _typeshed import Incomplete

np: Incomplete

class TensorTypeAndShape:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsTensorTypeAndShape(cls, buf, offset: int = 0): ...
    @classmethod
    def TensorTypeAndShapeBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def ElemType(self): ...
    def Shape(self): ...

def TensorTypeAndShapeStart(builder) -> None: ...
def Start(builder) -> None: ...
def TensorTypeAndShapeAddElemType(builder, elemType) -> None: ...
def AddElemType(builder, elemType) -> None: ...
def TensorTypeAndShapeAddShape(builder, shape) -> None: ...
def AddShape(builder, shape) -> None: ...
def TensorTypeAndShapeEnd(builder): ...
def End(builder): ...
