from _typeshed import Incomplete

np: Incomplete

class TypeInfo:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsTypeInfo(cls, buf, offset: int = 0): ...
    @classmethod
    def TypeInfoBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Denotation(self): ...
    def ValueType(self): ...
    def Value(self): ...

def TypeInfoStart(builder) -> None: ...
def Start(builder) -> None: ...
def TypeInfoAddDenotation(builder, denotation) -> None: ...
def AddDenotation(builder, denotation) -> None: ...
def TypeInfoAddValueType(builder, valueType) -> None: ...
def AddValueType(builder, valueType) -> None: ...
def TypeInfoAddValue(builder, value) -> None: ...
def AddValue(builder, value) -> None: ...
def TypeInfoEnd(builder): ...
def End(builder): ...
