from _typeshed import Incomplete

np: Incomplete

class ValueInfo:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsValueInfo(cls, buf, offset: int = 0): ...
    @classmethod
    def ValueInfoBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Name(self): ...
    def DocString(self): ...
    def Type(self): ...

def ValueInfoStart(builder) -> None: ...
def Start(builder) -> None: ...
def ValueInfoAddName(builder, name) -> None: ...
def AddName(builder, name) -> None: ...
def ValueInfoAddDocString(builder, docString) -> None: ...
def AddDocString(builder, docString) -> None: ...
def ValueInfoAddType(builder, type) -> None: ...
def AddType(builder, type) -> None: ...
def ValueInfoEnd(builder): ...
def End(builder): ...
