import logging
import onnx
import pathlib
from ..onnx_model_utils import ModelProtoWithShapeInfo as ModelProtoWithShapeInfo, get_producer_consumer_maps as get_producer_consumer_maps, is_fixed_size_tensor as is_fixed_size_tensor, optimize_model as optimize_model
from _typeshed import Incomplete
from enum import IntEnum

class _SupportedOpsChecker:
    def __init__(self, filename) -> None: ...
    def is_op_supported(self, node): ...
    def get_caveats(self): ...

class PartitioningInfo:
    class TryWithEP(IntEnum):
        NO = (0,)
        MAYBE = (1,)
        YES = 2
    num_nodes: Incomplete
    num_supported_nodes: Incomplete
    num_partitions: Incomplete
    supported_ops_checker: Incomplete
    supported_groups: Incomplete
    unsupported_ops: Incomplete
    nodes_unsupported_due_to_op: Incomplete
    nodes_unsupported_due_to_dynamic_input: Incomplete
    num_unsupported_nodes_due_to_rank: Incomplete
    ops_with_unsupported_rank: Incomplete
    num_subgraphs: int
    num_nodes_in_subgraphs: int
    def __init__(self, num_nodes: int, num_supported_nodes: int, num_partitions: int, supported_ops_checker: _SupportedOpsChecker, supported_groups: list[onnx.NodeProto], unsupported_ops: set[str], nodes_unsupported_due_to_op: int, nodes_unsupported_due_to_dynamic_input: int, num_unsupported_nodes_due_to_rank: int, ops_with_unsupported_rank: set[str]) -> None: ...
    def merge(self, other: PartitioningInfo): ...
    def suitability(self): ...
    def print_analysis(self, logger: logging.Logger, ep_name: str): ...

def check_partitioning(main_graph: onnx.GraphProto, supported_ops_checker: _SupportedOpsChecker, require_fixed_input_sizes: bool, max_rank: int = 999) -> PartitioningInfo: ...
def check_nnapi_partitions(model, require_fixed_input_sizes: bool): ...
def check_coreml_partitions(model: onnx.ModelProto, require_fixed_input_sizes: bool, config_filename: str): ...
def check_shapes(graph: onnx.GraphProto, logger: logging.Logger | None = None): ...
def checker(model_path: pathlib.Path, logger: logging.Logger): ...
def analyze_model(model_path: pathlib.Path, skip_optimize: bool = False, logger: logging.Logger | None = None): ...
def parse_args(): ...
def run_analyze_model() -> None: ...
