from ._export import public_api as public_api
from _typeshed import Incomplete
from typing import Iterable

class _TypeFormatCombination:
    types: Incomplete
    layouts: Incomplete
    tactics: Incomplete
    def __init__(self, num: int = 0) -> None: ...
    def set_types(self, types) -> None: ...
    def set_layouts(self, layouts=None) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...

class AutoTuneCombination:
    io_types: Incomplete
    layouts: Incomplete
    combinations: Incomplete
    def __init__(self, io_types: str = None, layouts: str = None, tactics: Iterable[int] = None) -> None: ...
    def pos(self, pos: Iterable[int], io_types: str, layouts: str = 'LINEAR') -> None: ...
    def tactics(self, tactics: Iterable[int]) -> None: ...
