import tensorrt as trt
from ._export import IS_AOT_ENABLED as IS_AOT_ENABLED, public_api as public_api
from ._tensor import KernelLaunchParams as KernelLaunchParams, Shape as Shape, ShapeExpr as ShapeExpr, ShapeExprs as ShapeExprs, SymExprs as SymExprs, SymInt32 as SymInt32, SymIntExpr as SymIntExpr, Tensor as Tensor, TensorDesc as TensorDesc
from _typeshed import Incomplete

class _TemplatePluginBase(trt.IPluginV3, trt.IPluginV3QuickCore, trt.IPluginV3QuickBuild):
    plugin_version: str
    input_types: Incomplete
    aliased_map: Incomplete
    plugin_namespace: Incomplete
    plugin_name: Incomplete
    num_outputs: Incomplete
    autotune_combs: Incomplete
    supported_combs: Incomplete
    curr_comb: Incomplete
    def __init__(self, name, namespace, num_outputs) -> None: ...
    def get_num_outputs(self): ...
    output_types: Incomplete
    def get_output_data_types(self, input_types, ranks): ...
    def get_fields_to_serialize(self): ...
    input_descs: Incomplete
    output_descs: Incomplete
    def get_output_shapes(self, inputs, shape_inputs, exprBuilder): ...
    def configure_plugin(self, inputs, outputs) -> None: ...
    def get_supported_format_combinations(self, in_out, num_inputs): ...
    def get_aliased_input(self, output_index: int): ...
    def get_valid_tactics(self): ...
    def set_tactic(self, tactic) -> None: ...

class _TemplateJITPlugin(_TemplatePluginBase, trt.IPluginV3QuickRuntime):
    expects_tactic: bool
    def __init__(self, name, namespace, num_outputs) -> None: ...
    register_function: Incomplete
    impl_function: Incomplete
    attrs: Incomplete
    impl_attr_names: Incomplete
    autotune_attr_names: Incomplete
    autotune_function: Incomplete
    def init(self, register_function, attrs, impl_attr_names, impl_function, autotune_attr_names, autotune_function, expects_tactic) -> None: ...
    def get_capability_interface(self, type): ...
    def enqueue(self, input_desc, output_desc, inputs, outputs, in_strides, out_strides, stream) -> None: ...
    def clone(self): ...

class _TemplateAOTPlugin(_TemplatePluginBase, trt.IPluginV3QuickAOTBuild):
    kernel_map: Incomplete
    def __init__(self, name, namespace, num_outputs) -> None: ...
    def set_tactic(self, tactic) -> None: ...
    register_function: Incomplete
    aot_impl_function: Incomplete
    attrs: Incomplete
    aot_impl_attr_names: Incomplete
    autotune_attr_names: Incomplete
    autotune_function: Incomplete
    def init(self, register_function, attrs, aot_impl_attr_names, aot_impl_function, autotune_attr_names, autotune_function) -> None: ...
    def get_capability_interface(self, type): ...
    def get_kernel(self, inputDesc, outputDesc): ...
    def get_launch_params(self, inDimsExprs, in_out, num_inputs, launchParams, symExprSetter, exprBuilder) -> None: ...
    def get_timing_cache_id(self): ...
    def clone(self): ...
