import abc
import tensorrt as trt
from ._export import IS_AOT_ENABLED as IS_AOT_ENABLED, public_api as public_api
from _typeshed import Incomplete
from abc import ABC, abstractmethod

class SymExpr(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def __add__(self, other): ...
    @abstractmethod
    def __sub__(self, other): ...
    @abstractmethod
    def __mul__(self, other): ...
    @abstractmethod
    def __floordiv__(self, other): ...
    @abstractmethod
    def __eq__(self, other): ...
    @abstractmethod
    def __lt__(self, other): ...
    @property
    @abstractmethod
    def is_constant(self) -> bool: ...
    @property
    @abstractmethod
    def constant_value(self) -> int: ...

class SymIntExprMeta(Incomplete): ...

class SymIntExpr(SymExpr, metaclass=SymIntExprMeta):
    def __init__(self, value: int | trt.IDimensionExpr | SymIntExpr = None) -> None: ...
    def __add__(self, other: int | SymIntExpr): ...
    def __sub__(self, other: int | SymIntExpr): ...
    def __mul__(self, other: int | SymIntExpr): ...
    def __floordiv__(self, other: int | SymIntExpr): ...
    def __eq__(self, other: int | SymIntExpr): ...
    def __lt__(self, other: int | SymIntExpr): ...
    def __bool__(self) -> bool: ...
    @property
    def is_constant(self) -> bool: ...
    def constant_value(self) -> int: ...

class SymExprImpl(trt.ISymExpr):
    type: Incomplete
    dtype: Incomplete
    expr: Incomplete
    def __init__(self, expr: SymIntExpr) -> None: ...

class SymInt32(SymIntExpr):
    def __init__(self, value: int | trt.IDimensionExpr | SymIntExpr = None) -> None: ...
    def __call__(self): ...

class SymInt8(SymIntExpr):
    def __init__(self, value: int | trt.IDimensionExpr | SymIntExpr = None) -> None: ...

class SymInt16(SymIntExpr):
    def __init__(self, value: int | trt.IDimensionExpr | SymIntExpr = None) -> None: ...

class ShapeExpr(SymInt32):
    def __init__(self, value: int | trt.IDimensionExpr | ShapeExpr | SymIntExpr = None) -> None: ...
    def __bool__(self) -> bool: ...
    @property
    def is_fake(self) -> bool: ...
    @property
    def is_size_tensor(self) -> bool: ...
    @property
    def is_constant(self) -> bool: ...
    def constant_value(self) -> int: ...

class SizeTensorShapeExpr(ShapeExpr):
    def __init__(self, size_tensor_desc: SizeTensorDesc) -> None: ...
    @property
    def is_constant(self): ...

class SymExprs:
    def __init__(self, length: int) -> None: ...
    @classmethod
    def from_tuple(cls, shape_exprs: tuple[SymExpr | int]) -> SymExprs: ...
    def __iter__(self): ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def __setitem__(self, index, expr) -> None: ...

class ShapeExprs(SymExprs):
    def __init__(self, length, _is_dummy: bool = False) -> None: ...
    @classmethod
    def from_tuple(cls, shape_exprs: tuple[ShapeExpr | int]) -> ShapeExpr: ...
    def numel(self) -> ShapeExpr: ...
    def __setitem__(self, index, value) -> None: ...

class SymIntExprs(SymExprs):
    def __init__(self, length) -> None: ...
    @classmethod
    def from_tuple(cls, shape_exprs: tuple[SymIntExpr | int]) -> SymIntExpr: ...
    def __setitem__(self, index, value) -> None: ...

class Shape:
    def __init__(self, tensor_desc: tuple[int] | trt.DynamicPluginTensorDesc | trt.PluginTensorDesc = None) -> None: ...
    def numel(self) -> int: ...
    def __iter__(self): ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    @property
    def is_dynamic(self) -> bool: ...
    @property
    def opt(self) -> tuple[int]: ...
    @property
    def min(self) -> tuple[int]: ...
    @property
    def max(self) -> tuple[int]: ...
    def __setitem__(self, index, val) -> None: ...

class TensorDesc:
    def __init__(self, shape_expr: ShapeExprs = None, dtype: trt.DataType = None, format: trt.TensorFormat = None, scale: float = None) -> None: ...
    def numel(self) -> int: ...
    @property
    def ndim(self) -> int: ...
    @property
    def is_size_tensor(self): ...
    def like(self) -> TensorDesc: ...
    def aliased(self) -> TensorDesc: ...
    def get_aliased(self) -> TensorDesc: ...
    @property
    def shape_expr(self) -> ShapeExprs: ...
    @property
    def dtype(self) -> trt.DataType: ...
    @property
    def shape(self) -> Shape: ...
    @property
    def format(self) -> trt.TensorFormat: ...
    @property
    def scale(self) -> float: ...
    @shape_expr.setter
    def shape_expr(self, value) -> None: ...
    @dtype.setter
    def dtype(self, value) -> None: ...
    @shape.setter
    def shape(self, value) -> None: ...
    @format.setter
    def format(self, value) -> None: ...
    @scale.setter
    def scale(self, value) -> None: ...
    @property
    def is_aliased(self) -> bool: ...
    @property
    def has_shape(self) -> bool: ...
    @property
    def is_dynamic(self) -> bool: ...
    @property
    def has_shape_expr(self) -> bool: ...
    def __setattr__(self, name, value) -> None: ...

class SizeTensorDesc(TensorDesc):
    def __init__(self, opt: ShapeExpr, upper_bound: ShapeExpr) -> None: ...
    @property
    def is_size_tensor(self): ...
    @property
    def opt(self) -> ShapeExpr: ...
    @property
    def upper_bound(self) -> ShapeExpr: ...
    @property
    def index(self) -> int: ...
    def expr(self) -> SizeTensorShapeExpr: ...

class Tensor:
    def __init__(self) -> None: ...
    @property
    def ndim(self) -> int: ...
    @property
    def data_ptr(self) -> int: ...
    @property
    def dtype(self) -> trt.DataType: ...
    @property
    def shape(self) -> Shape: ...
    @property
    def format(self) -> trt.TensorFormat: ...
    @property
    def scale(self) -> float: ...
    @property
    def strides(self) -> tuple[int]: ...
    @data_ptr.setter
    def data_ptr(self, value) -> None: ...
    @dtype.setter
    def dtype(self, value) -> None: ...
    @shape.setter
    def shape(self, value) -> None: ...
    @format.setter
    def format(self, value) -> None: ...
    @scale.setter
    def scale(self, value) -> None: ...
    @strides.setter
    def strides(self, value) -> None: ...
    def numel(self) -> int: ...
    @property
    def __cuda_array_interface__(self): ...
    def __setattr__(self, name, value) -> None: ...
    def get_aliased(self) -> Tensor: ...
    @property
    def is_aliased(self): ...
    @property
    def is_data_dependent(self): ...
    def aliased(self, shape: Shape | tuple[int] | trt.PluginTensorDesc = None) -> Tensor: ...

class KernelLaunchParams:
    grid_x: Incomplete
    grid_y: Incomplete
    grid_z: Incomplete
    block_x: Incomplete
    block_y: Incomplete
    block_z: Incomplete
    shared_mem: Incomplete
    def __init__(self, grid_x: int | trt.IDimensionExpr | SymInt32 = 1, grid_y: int | trt.IDimensionExpr | SymInt32 = 1, grid_z: int | trt.IDimensionExpr | SymInt32 = 1, block_x: int | trt.IDimensionExpr | SymInt32 = 1, block_y: int | trt.IDimensionExpr | SymInt32 = 1, block_z: int | trt.IDimensionExpr | SymInt32 = 1, shared_mem: int | trt.IDimensionExpr | SymInt32 = 0) -> None: ...
    def __setattr__(self, name, value) -> None: ...
