import tensorrt as trt
from ._export import public_api as public_api
from ._tensor import ShapeExpr as ShapeExpr, ShapeExprs as ShapeExprs, SizeTensorDesc as SizeTensorDesc, TensorDesc as TensorDesc

def cdiv(first: int | ShapeExpr, second: int | ShapeExpr) -> ShapeExpr: ...
def max(first: int | ShapeExpr, second: int | ShapeExpr) -> ShapeExpr: ...
def min(first: int | ShapeExpr, second: int | ShapeExpr) -> ShapeExpr: ...
def size_tensor(opt: ShapeExpr, upper_bound: ShapeExpr) -> SizeTensorDesc: ...
def from_shape_expr(shape_expr: tuple[ShapeExpr | int] | ShapeExprs, dtype: trt.DataType) -> TensorDesc: ...
