from _typeshed import Incomplete

class QuantOperatorBase:
    quantizer: Incomplete
    node: Incomplete
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
    def should_quantize(self): ...
    def quantize(self) -> None: ...
