from ..quant_utils import QuantizedValue as QuantizedValue, QuantizedValueType as QuantizedValueType, TENSOR_NAME_QUANT_SUFFIX as TENSOR_NAME_QUANT_SUFFIX, attribute_to_kwarg as attribute_to_kwarg, find_by_name as find_by_name, get_mul_node as get_mul_node
from .base_operator import QuantOperatorBase as QuantOperatorBase
from .qdq_base_operator import QDQOperatorBase as QDQOperatorBase

class ConvInteger(QuantOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
    def add_bias(self, nodes, scaled_output) -> None: ...
    def quantize(self) -> None: ...

class QLinearConv(QuantOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
    def quantize(self): ...

class QDQConv(QDQOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
    def quantize(self) -> None: ...
