from .qdq_base_operator import QDQOperatorBase as QDQOperatorBase

class QDQNormalization(QDQOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
    def quantize(self) -> None: ...
