import os
from onnx import checker as checker, compose as compose, defs as defs, gen_proto as gen_proto, helper as helper, numpy_helper as numpy_helper, parser as parser, printer as printer, shape_inference as shape_inference, utils as utils, version_converter as version_converter
from onnx.external_data_helper import convert_model_to_external_data as convert_model_to_external_data, load_external_data_for_model as load_external_data_for_model, write_external_data_tensors as write_external_data_tensors
from onnx.onnx_cpp2py_export import ONNX_ML as ONNX_ML
from onnx.onnx_data_pb import MapProto as MapProto, OptionalProto as OptionalProto, SequenceProto as SequenceProto
from onnx.onnx_operators_pb import OperatorProto as OperatorProto, OperatorSetProto as OperatorSetProto
from onnx.onnx_pb import AttributeProto as AttributeProto, DeviceConfigurationProto as DeviceConfigurationProto, EXPERIMENTAL as EXPERIMENTAL, FunctionProto as FunctionProto, GraphProto as GraphProto, IR_VERSION as IR_VERSION, IR_VERSION_2017_10_10 as IR_VERSION_2017_10_10, IR_VERSION_2017_10_30 as IR_VERSION_2017_10_30, IR_VERSION_2017_11_3 as IR_VERSION_2017_11_3, IR_VERSION_2019_1_22 as IR_VERSION_2019_1_22, IR_VERSION_2019_3_18 as IR_VERSION_2019_3_18, IR_VERSION_2019_9_19 as IR_VERSION_2019_9_19, IR_VERSION_2020_5_8 as IR_VERSION_2020_5_8, IR_VERSION_2021_7_30 as IR_VERSION_2021_7_30, IR_VERSION_2023_5_5 as IR_VERSION_2023_5_5, IR_VERSION_2024_3_25 as IR_VERSION_2024_3_25, IntIntListEntryProto as IntIntListEntryProto, ModelProto as ModelProto, NodeDeviceConfigurationProto as NodeDeviceConfigurationProto, NodeProto as NodeProto, OperatorSetIdProto as OperatorSetIdProto, OperatorStatus as OperatorStatus, STABLE as STABLE, ShardedDimProto as ShardedDimProto, ShardingSpecProto as ShardingSpecProto, SimpleShardedDimProto as SimpleShardedDimProto, SparseTensorProto as SparseTensorProto, StringStringEntryProto as StringStringEntryProto, TensorAnnotation as TensorAnnotation, TensorProto as TensorProto, TensorShapeProto as TensorShapeProto, TrainingInfoProto as TrainingInfoProto, TypeProto as TypeProto, ValueInfoProto as ValueInfoProto, Version as Version
from typing import IO

__all__ = ['ONNX_ML', 'IR_VERSION', 'IR_VERSION_2017_10_10', 'IR_VERSION_2017_10_30', 'IR_VERSION_2017_11_3', 'IR_VERSION_2019_1_22', 'IR_VERSION_2019_3_18', 'IR_VERSION_2019_9_19', 'IR_VERSION_2020_5_8', 'IR_VERSION_2021_7_30', 'IR_VERSION_2023_5_5', 'IR_VERSION_2024_3_25', 'EXPERIMENTAL', 'STABLE', 'checker', 'compose', 'defs', 'gen_proto', 'helper', 'numpy_helper', 'parser', 'printer', 'shape_inference', 'utils', 'version_converter', 'AttributeProto', 'DeviceConfigurationProto', 'FunctionProto', 'GraphProto', 'IntIntListEntryProto', 'MapProto', 'ModelProto', 'NodeDeviceConfigurationProto', 'NodeProto', 'OperatorProto', 'OperatorSetIdProto', 'OperatorSetProto', 'OperatorStatus', 'OptionalProto', 'SequenceProto', 'SimpleShardedDimProto', 'ShardedDimProto', 'ShardingSpecProto', 'SparseTensorProto', 'StringStringEntryProto', 'TensorAnnotation', 'TensorProto', 'TensorShapeProto', 'TrainingInfoProto', 'TypeProto', 'ValueInfoProto', 'Version', 'convert_model_to_external_data', 'load_external_data_for_model', 'load_model_from_string', 'load_model', 'load_tensor_from_string', 'load_tensor', 'save_model', 'save_tensor', 'write_external_data_tensors']

def load_model(f: IO[bytes] | str | os.PathLike, format: _SupportedFormat | None = None, load_external_data: bool = True) -> ModelProto: ...
def load_tensor(f: IO[bytes] | str | os.PathLike, format: _SupportedFormat | None = None) -> TensorProto: ...
def load_model_from_string(s: bytes | str, format: _SupportedFormat = ...) -> ModelProto: ...
def load_tensor_from_string(s: bytes, format: _SupportedFormat = ...) -> TensorProto: ...
def save_model(proto: ModelProto | bytes, f: IO[bytes] | str | os.PathLike, format: _SupportedFormat | None = None, *, save_as_external_data: bool = False, all_tensors_to_one_file: bool = True, location: str | None = None, size_threshold: int = 1024, convert_attribute: bool = False) -> None: ...
def save_tensor(proto: TensorProto, f: IO[bytes] | str | os.PathLike, format: _SupportedFormat | None = None) -> None: ...
load = load_model
load_from_string = load_model_from_string
save = save_model
