import onnx
import onnx.onnx_cpp2py_export.checker as C
import os
from _typeshed import Incomplete

__all__ = ['check_attribute', 'check_function', 'check_graph', 'check_model', 'check_node', 'check_sparse_tensor', 'check_tensor', 'check_value_info', 'DEFAULT_CONTEXT', 'LEXICAL_SCOPE_CONTEXT', 'ValidationError', 'C', 'MAXIMUM_PROTOBUF']

MAXIMUM_PROTOBUF: int
DEFAULT_CONTEXT: Incomplete
LEXICAL_SCOPE_CONTEXT: Incomplete

def check_value_info(value_info: onnx.ValueInfoProto, ctx: C.CheckerContext = ...) -> None: ...
def check_tensor(tensor: onnx.TensorProto, ctx: C.CheckerContext = ...) -> None: ...
def check_attribute(attr: onnx.AttributeProto, ctx: C.CheckerContext = ..., lexical_scope_ctx: C.LexicalScopeContext = ...) -> None: ...
def check_node(node: onnx.NodeProto, ctx: C.CheckerContext = ..., lexical_scope_ctx: C.LexicalScopeContext = ...) -> None: ...
def check_function(function: onnx.FunctionProto, ctx: C.CheckerContext | None = None, lexical_scope_ctx: C.LexicalScopeContext = ...) -> None: ...
def check_graph(graph: onnx.GraphProto, ctx: C.CheckerContext = ..., lexical_scope_ctx: C.LexicalScopeContext = ...) -> None: ...
def check_sparse_tensor(sparse: onnx.SparseTensorProto, ctx: C.CheckerContext = ...) -> None: ...
def check_model(model: onnx.ModelProto | str | bytes | os.PathLike, full_check: bool = False, skip_opset_compatibility_check: bool = False, check_custom_domain: bool = False) -> None: ...
ValidationError = C.ValidationError
