from _typeshed import Incomplete
from collections.abc import Callable as Callable
from onnx.onnx_pb import AttributeProto as AttributeProto, FunctionProto as FunctionProto, GraphProto as GraphProto, ModelProto as ModelProto, TensorProto as TensorProto

class ExternalDataInfo:
    location: str
    offset: Incomplete
    length: Incomplete
    checksum: Incomplete
    basepath: str
    def __init__(self, tensor: TensorProto) -> None: ...

def load_external_data_for_tensor(tensor: TensorProto, base_dir: str) -> None: ...
def load_external_data_for_model(model: ModelProto, base_dir: str) -> None: ...
def set_external_data(tensor: TensorProto, location: str, offset: int | None = None, length: int | None = None, checksum: str | None = None, basepath: str | None = None) -> None: ...
def convert_model_to_external_data(model: ModelProto, all_tensors_to_one_file: bool = True, location: str | None = None, size_threshold: int = 1024, convert_attribute: bool = False) -> None: ...
def convert_model_from_external_data(model: ModelProto) -> None: ...
def save_external_data(tensor: TensorProto, base_path: str) -> None: ...
def uses_external_data(tensor: TensorProto) -> bool: ...
def remove_external_data_field(tensor: TensorProto, field_key: str) -> None: ...
def write_external_data_tensors(model: ModelProto, filepath: str) -> ModelProto: ...
