import google.protobuf.message
import numpy as np
import onnx
from _typeshed import Incomplete
from collections.abc import Callable as Callable, KeysView, Sequence
from google.protobuf.internal.containers import RepeatedCompositeFieldContainer as RepeatedCompositeFieldContainer
from onnx import defs as defs
from onnx.onnx_data_pb import MapProto as MapProto, OptionalProto as OptionalProto, SequenceProto as SequenceProto
from onnx.onnx_pb import AttributeProto as AttributeProto, FunctionProto as FunctionProto, GraphProto as GraphProto, ModelProto as ModelProto, NodeProto as NodeProto, OperatorSetIdProto as OperatorSetIdProto, TensorProto as TensorProto, TensorShapeProto as TensorShapeProto, TrainingInfoProto as TrainingInfoProto, TypeProto as TypeProto, ValueInfoProto as ValueInfoProto
from typing import Any

VersionRowType = tuple[str, int, int, int] | tuple[str, int, int, int, int]
VersionTableType = list[VersionRowType]
AssignmentBindingType = list[tuple[str, str]]
VERSION_TABLE: VersionTableType
VersionMapType = dict[tuple[str, int], int]
OP_SET_ID_VERSION_MAP: Incomplete

def find_min_ir_version_for(opsetidlist: Sequence[OperatorSetIdProto], ignore_unknown: bool = False) -> int: ...
def make_node(op_type: str, inputs: Sequence[str], outputs: Sequence[str], name: str | None = None, doc_string: str | None = None, domain: str | None = None, overload: str | None = None, **kwargs: Any) -> NodeProto: ...
def make_operatorsetid(domain: str, version: int) -> OperatorSetIdProto: ...
def make_graph(nodes: Sequence[NodeProto], name: str, inputs: Sequence[ValueInfoProto], outputs: Sequence[ValueInfoProto], initializer: Sequence[TensorProto] | None = None, doc_string: str | None = None, value_info: Sequence[ValueInfoProto] | None = None, sparse_initializer: Sequence[onnx.SparseTensorProto] | None = None) -> GraphProto: ...
def make_opsetid(domain: str, version: int) -> OperatorSetIdProto: ...
def make_function(domain: str, fname: str, inputs: Sequence[str], outputs: Sequence[str], nodes: Sequence[NodeProto], opset_imports: Sequence[OperatorSetIdProto], attributes: Sequence[str] | None = None, attribute_protos: Sequence[AttributeProto] | None = None, doc_string: str | None = None, overload: str | None = None, value_info: Sequence[ValueInfoProto] | None = None) -> FunctionProto: ...
def make_model(graph: GraphProto, **kwargs: Any) -> ModelProto: ...
def make_model_gen_version(graph: GraphProto, **kwargs: Any) -> ModelProto: ...
def set_metadata_props(proto: ModelProto | GraphProto | FunctionProto | NodeProto | TensorProto | ValueInfoProto, dict_value: dict[str, str]) -> None: ...
def set_model_props(model: ModelProto, dict_value: dict[str, str]) -> None: ...
def make_tensor(name: str, data_type: int, dims: Sequence[int], vals: Sequence[int | float] | bytes | np.ndarray, raw: bool = False) -> TensorProto: ...
def make_sparse_tensor(values: TensorProto, indices: TensorProto, dims: Sequence[int]) -> onnx.SparseTensorProto: ...
def make_sequence(name: str, elem_type: SequenceProto.DataType, values: Sequence[Any]) -> SequenceProto: ...
def make_map(name: str, key_type: int, keys: list[Any], values: SequenceProto) -> MapProto: ...
def make_optional(name: str, elem_type: OptionalProto.DataType, value: google.protobuf.message.Message | None) -> OptionalProto: ...
def make_attribute(key: str, value: Any, doc_string: str | None = None, attr_type: int | None = None) -> AttributeProto: ...
def make_attribute_ref(name: str, attr_type: AttributeProto.AttributeType, doc_string: str | None = None) -> AttributeProto: ...
def get_attribute_value(attr: AttributeProto) -> Any: ...
def get_node_attr_value(node: NodeProto, attr_name: str) -> Any: ...
def make_empty_tensor_value_info(name: str) -> ValueInfoProto: ...
def make_tensor_type_proto(elem_type: int, shape: Sequence[str | int | None] | None, shape_denotation: list[str] | None = None) -> TypeProto: ...
def make_tensor_value_info(name: str, elem_type: int, shape: Sequence[str | int | None] | None, doc_string: str = '', shape_denotation: list[str] | None = None) -> ValueInfoProto: ...
def make_sparse_tensor_type_proto(elem_type: int, shape: Sequence[str | int | None] | None, shape_denotation: list[str] | None = None) -> TypeProto: ...
def make_sparse_tensor_value_info(name: str, elem_type: int, shape: Sequence[str | int | None] | None, doc_string: str = '', shape_denotation: list[str] | None = None) -> ValueInfoProto: ...
def make_sequence_type_proto(inner_type_proto: TypeProto) -> TypeProto: ...
def make_optional_type_proto(inner_type_proto: TypeProto) -> TypeProto: ...
def make_map_type_proto(key_type: int, value_type: TypeProto) -> TypeProto: ...
def make_value_info(name: str, type_proto: TypeProto, doc_string: str = '') -> ValueInfoProto: ...
def make_tensor_sequence_value_info(name: str, elem_type: int, shape: Sequence[str | int | None] | None, doc_string: str = '', elem_shape_denotation: list[str] | None = None) -> ValueInfoProto: ...
def printable_attribute(attr: AttributeProto, subgraphs: bool = False) -> str | tuple[str, list[GraphProto]]: ...
def printable_dim(dim: TensorShapeProto.Dimension) -> str: ...
def printable_type(t: TypeProto) -> str: ...
def printable_value_info(v: ValueInfoProto) -> str: ...
def printable_tensor_proto(t: TensorProto) -> str: ...
def printable_node(node: NodeProto, prefix: str = '', subgraphs: bool = False) -> str | tuple[str, list[GraphProto]]: ...
def printable_graph(graph: GraphProto, prefix: str = '') -> str: ...
def strip_doc_string(proto: google.protobuf.message.Message) -> None: ...
def make_training_info(algorithm: GraphProto, algorithm_bindings: AssignmentBindingType, initialization: GraphProto | None, initialization_bindings: AssignmentBindingType | None) -> TrainingInfoProto: ...
def tensor_dtype_to_np_dtype(tensor_dtype: int) -> np.dtype: ...
def tensor_dtype_to_storage_tensor_dtype(tensor_dtype: int) -> int: ...
def tensor_dtype_to_string(tensor_dtype: int) -> str: ...
def tensor_dtype_to_field(tensor_dtype: int) -> str: ...
def np_dtype_to_tensor_dtype(np_dtype: np.dtype) -> TensorProto.DataType: ...
def get_all_tensor_dtypes() -> KeysView[int]: ...
