import onnx

def inline_local_functions(model: onnx.ModelProto, convert_version: bool = False) -> onnx.ModelProto: ...
def inline_selected_functions(model: onnx.ModelProto, function_ids: list[tuple[str, str]], exclude: bool = False, inline_schema_functions: bool = False) -> onnx.ModelProto: ...
