import numpy as np
import onnx
from _typeshed import Incomplete
from collections.abc import Iterable
from typing import Any

def make_large_tensor_proto(location: str, tensor_name: str, tensor_type: int, shape: tuple[int, ...]) -> onnx.TensorProto: ...

class ModelContainer:
    model_proto_: onnx.ModelProto | None
    large_initializers: dict[str, np.ndarray]
    def __init__(self) -> None: ...
    def check_model(self) -> None: ...
    def __getitem__(self, name: str) -> np.ndarray: ...
    @property
    def model_proto(self) -> onnx.ModelProto: ...
    graphs_: Incomplete
    @model_proto.setter
    def model_proto(self, model_proto: onnx.ModelProto): ...
    def enumerate_graph_protos(self) -> Iterable[onnx.GraphProto]: ...
    def is_in_memory_external_initializer(self, name: str) -> bool: ...
    def set_large_initializers(self, large_initializers: dict[str, np.ndarray]): ...
    def check_large_initializers(self) -> None: ...
    def save(self, file_path: str, all_tensors_to_one_file: bool = False) -> onnx.ModelProto: ...
    def load(self, file_path: str, load_large_initializers: bool = True): ...

def make_large_model(graph: onnx.GraphProto, large_initializers: dict[str, np.ndarray] | None = None, **kwargs: Any) -> ModelContainer: ...
