import numpy as np
import onnx
from onnx import helper as helper
from typing import Any

def to_float8e8m0(x: np.ndarray, saturate: bool = True, round_mode: str = 'up') -> np.ndarray: ...
def to_array(tensor: onnx.TensorProto, base_dir: str = '') -> np.ndarray: ...
def tobytes_little_endian(array: np.ndarray) -> bytes: ...
def from_array(array: np.ndarray, /, name: str | None = None) -> onnx.TensorProto: ...
def to_list(sequence: onnx.SequenceProto) -> list[Any]: ...
def from_list(lst: list[Any], name: str | None = None, dtype: int | None = None) -> onnx.SequenceProto: ...
def to_dict(map_proto: onnx.MapProto) -> dict[Any, Any]: ...
def from_dict(dict_: dict[Any, Any], name: str | None = None) -> onnx.MapProto: ...
def to_optional(optional: onnx.OptionalProto) -> Any | None: ...
def from_optional(opt: Any | None, name: str | None = None, dtype: int | None = None) -> onnx.OptionalProto: ...
def create_random_int(input_shape: tuple[int], dtype: np.dtype, seed: int = 1) -> np.ndarray: ...
def saturate_cast(x: np.ndarray, dtype: np.dtype) -> np.ndarray: ...
