import onnx

class ParseError(Exception): ...

def parse_model(model_text: str) -> onnx.ModelProto: ...
def parse_graph(graph_text: str) -> onnx.GraphProto: ...
def parse_function(function_text: str) -> onnx.FunctionProto: ...
def parse_node(node_text: str) -> onnx.NodeProto: ...
