from _typeshed import Incomplete
from collections.abc import Collection
from typing import Any, Protocol

__all__ = ['registry']

class ProtoSerializer(Protocol):
    supported_format: str
    file_extensions: Collection[str]
    def serialize_proto(self, proto: _Proto) -> Any: ...
    def deserialize_proto(self, serialized: Any, proto: _Proto) -> _Proto: ...

class _Registry:
    def __init__(self) -> None: ...
    def register(self, serializer: ProtoSerializer) -> None: ...
    def get(self, fmt: str) -> ProtoSerializer: ...
    def get_format_from_file_extension(self, file_extension: str) -> str | None: ...

class _ProtobufSerializer(ProtoSerializer):
    supported_format: str
    file_extensions: Incomplete
    def serialize_proto(self, proto: _Proto) -> bytes: ...
    def deserialize_proto(self, serialized: bytes, proto: _Proto) -> _Proto: ...

class _TextProtoSerializer(ProtoSerializer):
    supported_format: str
    file_extensions: Incomplete
    def serialize_proto(self, proto: _Proto) -> bytes: ...
    def deserialize_proto(self, serialized: bytes | str, proto: _Proto) -> _Proto: ...

class _JsonSerializer(ProtoSerializer):
    supported_format: str
    file_extensions: Incomplete
    def serialize_proto(self, proto: _Proto) -> bytes: ...
    def deserialize_proto(self, serialized: bytes | str, proto: _Proto) -> _Proto: ...

class _TextualSerializer(ProtoSerializer):
    supported_format: str
    file_extensions: Incomplete
    def serialize_proto(self, proto: _Proto) -> bytes: ...
    def deserialize_proto(self, serialized: bytes | str, proto: _Proto) -> _Proto: ...

registry: Incomplete
