from _typeshed import Incomplete

np: Incomplete

class KeyValue:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsKeyValue(cls, buf, offset: int = 0): ...
    def Init(self, buf, pos) -> None: ...
    def Key(self): ...
    def Value(self): ...

def Start(builder) -> None: ...
def KeyValueStart(builder): ...
def AddKey(builder, key) -> None: ...
def KeyValueAddKey(builder, key): ...
def AddValue(builder, value) -> None: ...
def KeyValueAddValue(builder, value): ...
def End(builder): ...
def KeyValueEnd(builder): ...
