from _typeshed import Incomplete

np: Incomplete

class TrtTable:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsTrtTable(cls, buf, offset: int = 0): ...
    def Init(self, buf, pos) -> None: ...
    def Dict(self, j): ...
    def DictLength(self): ...
    def DictIsNone(self): ...

def Start(builder) -> None: ...
def TrtTableStart(builder): ...
def AddDict(builder, dict) -> None: ...
def TrtTableAddDict(builder, dict): ...
def StartDictVector(builder, numElems): ...
def TrtTableStartDictVector(builder, numElems): ...
def End(builder): ...
def TrtTableEnd(builder): ...
