import argparse
import os

def get_args() -> argparse: ...
def export_lora_parameters(npz_file_path: os.PathLike, adapter_version: int, model_version: int, output_file_path: os.PathLike): ...
def main() -> int: ...
