import numpy as np
import numpy.typing as npt
import onnxruntime
import os
from _typeshed import Incomplete
from collections.abc import Callable, Sequence
from onnxruntime.capi import _pybind_state as C
from typing import Any

def get_ort_device_type(device_type: str) -> int: ...

class AdapterFormat:
    def __init__(self, adapter=None) -> None: ...
    @staticmethod
    def read_adapter(file_path: os.PathLike) -> AdapterFormat: ...
    def export_adapter(self, file_path: os.PathLike): ...
    def get_format_version(self) -> int: ...
    def set_adapter_version(self, adapter_version: int) -> None: ...
    def get_adapter_version(self) -> int: ...
    def set_model_version(self, model_version: int) -> None: ...
    def get_model_version(self) -> int: ...
    def set_parameters(self, params: dict[str, OrtValue]) -> None: ...
    def get_parameters(self) -> dict[str, OrtValue]: ...

def check_and_normalize_provider_args(providers: Sequence[str | tuple[str, dict[Any, Any]]] | None, provider_options: Sequence[dict[Any, Any]] | None, available_provider_names: Sequence[str]): ...

class Session:
    def __init__(self, enable_fallback: bool = True) -> None: ...
    def get_session_options(self) -> onnxruntime.SessionOptions: ...
    def get_inputs(self) -> Sequence[onnxruntime.NodeArg]: ...
    def get_outputs(self) -> Sequence[onnxruntime.NodeArg]: ...
    def get_overridable_initializers(self) -> Sequence[onnxruntime.NodeArg]: ...
    def get_modelmeta(self) -> onnxruntime.ModelMetadata: ...
    def get_input_memory_infos(self) -> Sequence[onnxruntime.MemoryInfo]: ...
    def get_output_memory_infos(self) -> Sequence[onnxruntime.MemoryInfo]: ...
    def get_input_epdevices(self) -> Sequence[onnxruntime.OrtEpDevice]: ...
    def get_providers(self) -> Sequence[str]: ...
    def get_provider_options(self): ...
    def get_provider_graph_assignment_info(self) -> Sequence[onnxruntime.OrtEpAssignedSubgraph]: ...
    def set_providers(self, providers=None, provider_options=None) -> None: ...
    def disable_fallback(self) -> None: ...
    def enable_fallback(self) -> None: ...
    def run(self, output_names, input_feed, run_options=None) -> Sequence[np.ndarray | SparseTensor | list | dict]: ...
    def run_async(self, output_names, input_feed, callback, user_data, run_options=None): ...
    def run_with_ort_values(self, output_names, input_dict_ort_values, run_options=None) -> Sequence[OrtValue]: ...
    def end_profiling(self): ...
    def get_profiling_start_time_ns(self): ...
    def io_binding(self) -> IOBinding: ...
    def run_with_iobinding(self, iobinding, run_options=None) -> None: ...
    def set_ep_dynamic_options(self, options: dict[str, str]): ...
    def get_tuning_results(self): ...
    def set_tuning_results(self, results, *, error_on_invalid: bool = False): ...
    def run_with_ortvaluevector(self, run_options, feed_names, feeds, fetch_names, fetches, fetch_devices) -> None: ...

class InferenceSession(Session):
    def __init__(self, path_or_bytes: str | bytes | os.PathLike, sess_options: onnxruntime.SessionOptions | None = None, providers: Sequence[str | tuple[str, dict[Any, Any]]] | None = None, provider_options: Sequence[dict[Any, Any]] | None = None, **kwargs) -> None: ...

def make_get_initializer_location_func_wrapper(get_initializer_location_func: GetInitializerLocationFunc) -> GetInitializerLocationWrapperFunc: ...

class ModelCompiler:
    get_initializer_location_func_wrapper: Incomplete
    def __init__(self, sess_options: onnxruntime.SessionOptions, input_model_path_or_bytes: str | os.PathLike | bytes, embed_compiled_data_into_model: bool = False, external_initializers_file_path: str | os.PathLike | None = None, external_initializers_size_threshold: int = 1024, flags: int = ..., graph_optimization_level: C.GraphOptimizationLevel = ..., get_initializer_location_func: GetInitializerLocationFunc | None = None) -> None: ...
    def compile_to_file(self, output_model_path: str | None = None): ...
    def compile_to_bytes(self) -> bytes: ...
    def compile_to_stream(self, write_function: Callable[[bytes], None]): ...

class IOBinding:
    def __init__(self, session: Session) -> None: ...
    def bind_cpu_input(self, name, arr_on_cpu) -> None: ...
    def bind_input(self, name, device_type, device_id, element_type, shape, buffer_ptr) -> None: ...
    def bind_ortvalue_input(self, name, ortvalue) -> None: ...
    def synchronize_inputs(self) -> None: ...
    def bind_output(self, name, device_type: str = 'cpu', device_id: int = 0, element_type=None, shape=None, buffer_ptr=None) -> None: ...
    def bind_ortvalue_output(self, name, ortvalue) -> None: ...
    def synchronize_outputs(self) -> None: ...
    def get_outputs(self): ...
    def get_outputs_as_ortvaluevector(self): ...
    def copy_outputs_to_cpu(self): ...
    def clear_binding_inputs(self) -> None: ...
    def clear_binding_outputs(self) -> None: ...

class OrtValue:
    def __init__(self, ortvalue: C.OrtValue, numpy_obj: np.ndarray | None = None) -> None: ...
    @classmethod
    def ortvalue_from_numpy(cls, numpy_obj: np.ndarray, /, device_type: str = 'cpu', device_id: int = 0, vendor_id: int = -1) -> OrtValue: ...
    @classmethod
    def ortvalue_from_numpy_with_onnx_type(cls, data: np.ndarray, /, onnx_element_type: int) -> OrtValue: ...
    @classmethod
    def ortvalue_from_shape_and_type(cls, shape: Sequence[int], element_type, device_type: str = 'cpu', device_id: int = 0, vendor_id: int = -1) -> OrtValue: ...
    @classmethod
    def ort_value_from_sparse_tensor(cls, sparse_tensor: SparseTensor) -> OrtValue: ...
    def as_sparse_tensor(self) -> SparseTensor: ...
    def data_ptr(self) -> int: ...
    def device_name(self) -> str: ...
    def shape(self) -> Sequence[int]: ...
    def data_type(self) -> str: ...
    def element_type(self) -> int: ...
    def tensor_size_in_bytes(self) -> int: ...
    def has_value(self) -> bool: ...
    def is_tensor(self) -> bool: ...
    def is_sparse_tensor(self) -> bool: ...
    def is_tensor_sequence(self) -> bool: ...
    def numpy(self) -> np.ndarray: ...
    def update_inplace(self, np_arr) -> None: ...

def copy_tensors(src: Sequence[OrtValue], dst: Sequence[OrtValue], stream=None) -> None: ...

class OrtDevice:
    def __init__(self, c_ort_device) -> None: ...
    @staticmethod
    def make(ort_device_name, device_id, vendor_id: int = -1): ...
    def device_id(self): ...
    def device_type(self): ...
    def device_vendor_id(self): ...
    def device_mem_type(self): ...

class SparseTensor:
    def __init__(self, sparse_tensor: C.SparseTensor) -> None: ...
    @classmethod
    def sparse_coo_from_numpy(cls, dense_shape: npt.NDArray[np.int64], values: np.ndarray, coo_indices: npt.NDArray[np.int64], ort_device: OrtDevice) -> SparseTensor: ...
    @classmethod
    def sparse_csr_from_numpy(cls, dense_shape: npt.NDArray[np.int64], values: np.ndarray, inner_indices: npt.NDArray[np.int64], outer_indices: npt.NDArray[np.int64], ort_device: OrtDevice) -> SparseTensor: ...
    def values(self) -> np.ndarray: ...
    def as_coo_view(self): ...
    def as_csrc_view(self): ...
    def as_blocksparse_view(self): ...
    def to_cuda(self, ort_device): ...
    def format(self): ...
    def dense_shape(self) -> npt.NDArray[np.int64]: ...
    def data_type(self) -> str: ...
    def device_name(self) -> str: ...

GetInitializerLocationFunc: Incomplete
GetInitializerLocationWrapperFunc: Incomplete
