import collections.abc
import numpy
import numpy.typing
import typing
import typing_extensions
from typing import ClassVar, overload

kNextPowerOfTwo: ArenaExtendStrategy
kSameAsRequested: ArenaExtendStrategy

class AdapterFormat:
    adapter_version: int
    model_version: int
    parameters: dict
    def __init__(self) -> None: ...
    def export_adapter(self, arg0: str) -> None: ...
    @staticmethod
    def read_adapter(arg0: str) -> AdapterFormat: ...
    @property
    def format_version(self) -> int: ...

class ArenaExtendStrategy:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    kNextPowerOfTwo: ClassVar[ArenaExtendStrategy] = ...
    kSameAsRequested: ClassVar[ArenaExtendStrategy] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class EPFail(Exception): ...

class EngineError(Exception): ...

class ExecutionMode:
    __members__: ClassVar[dict] = ...  # read-only
    ORT_PARALLEL: ClassVar[ExecutionMode] = ...
    ORT_SEQUENTIAL: ClassVar[ExecutionMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class ExecutionOrder:
    __members__: ClassVar[dict] = ...  # read-only
    DEFAULT: ClassVar[ExecutionOrder] = ...
    MEMORY_EFFICIENT: ClassVar[ExecutionOrder] = ...
    PRIORITY_BASED: ClassVar[ExecutionOrder] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class Fail(Exception): ...

class GraphOptimizationLevel:
    __members__: ClassVar[dict] = ...  # read-only
    ORT_DISABLE_ALL: ClassVar[GraphOptimizationLevel] = ...
    ORT_ENABLE_ALL: ClassVar[GraphOptimizationLevel] = ...
    ORT_ENABLE_BASIC: ClassVar[GraphOptimizationLevel] = ...
    ORT_ENABLE_EXTENDED: ClassVar[GraphOptimizationLevel] = ...
    ORT_ENABLE_LAYOUT: ClassVar[GraphOptimizationLevel] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class InferenceSession:
    def __init__(self, arg0: SessionOptions, arg1: str, arg2: bool, arg3: bool) -> None: ...
    def end_profiling(self) -> str: ...
    def get_provider_graph_assignment_info(self) -> list[OrtEpAssignedSubgraph]: ...
    def get_provider_options(self) -> dict[str, dict[str, str]]: ...
    def get_providers(self) -> list[str]: ...
    def get_tuning_results(self) -> list: ...
    def initialize_session(self, arg0: collections.abc.Sequence[str], arg1: collections.abc.Sequence[collections.abc.Mapping[str, str]], arg2: collections.abc.Set[str]) -> None: ...
    def run(self, arg0: collections.abc.Sequence[str], arg1: collections.abc.Mapping[str, object], arg2: RunOptions) -> list: ...
    def run_async(self, arg0: collections.abc.Sequence[str], arg1: collections.abc.Mapping[str, object], arg2: collections.abc.Callable[[collections.abc.Sequence[object], object, str], None], arg3: object, arg4: RunOptions) -> None: ...
    def run_with_iobinding(self, arg0, arg1: RunOptions) -> None: ...
    def run_with_ort_values(self, *args, **kwargs): ...
    def run_with_ortvaluevector(self, *args, **kwargs): ...
    def set_ep_dynamic_options(self, arg0: dict) -> None: ...
    def set_tuning_results(self, arg0: list, arg1: bool) -> None: ...
    @property
    def get_profiling_start_time_ns(self) -> int: ...
    @property
    def input_epdevices(self) -> list: ...
    @property
    def input_meminfos(self) -> list: ...
    @property
    def inputs_meta(self) -> list[NodeArg]: ...
    @property
    def model_meta(self) -> ModelMetadata: ...
    @property
    def output_meminfos(self) -> list: ...
    @property
    def outputs_meta(self) -> list[NodeArg]: ...
    @property
    def overridable_initializers(self) -> list[NodeArg]: ...
    @property
    def session_options(self) -> SessionOptions: ...

class InvalidArgument(Exception): ...

class InvalidGraph(Exception): ...

class InvalidProtobuf(Exception): ...

class LoraAdapter:
    def __init__(self) -> None: ...
    def Load(self, arg0: str) -> None: ...

class ModelCompiler:
    def __init__(self, arg0: SessionOptions, arg1: str, arg2: bool, arg3: bool, arg4: str, arg5: typing.SupportsInt | typing.SupportsIndex, arg6: typing.SupportsInt | typing.SupportsIndex, arg7: GraphOptimizationLevel, arg8: collections.abc.Callable[[str, OrtValue, OrtExternalInitializerInfo], OrtExternalInitializerInfo]) -> None: ...
    def compile_to_bytes(self) -> bytes: ...
    def compile_to_file(self, arg0: str) -> None: ...
    def compile_to_stream(self, arg0: collections.abc.Callable[[bytes], None]) -> None: ...

class ModelLoadCanceled(Exception): ...

class ModelLoaded(Exception): ...

class ModelMetadata:
    custom_metadata_map: dict[str, str]
    description: str
    domain: str
    graph_description: str
    graph_name: str
    producer_name: str
    version: int
    def __init__(self, *args, **kwargs) -> None: ...

class ModelRequiresCompilation(Exception): ...

class NoModel(Exception): ...

class NoSuchFile(Exception): ...

class NodeArg:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def shape(self) -> list[object]: ...
    @property
    def type(self) -> str: ...

class NotFound(Exception): ...

class NotImplemented(Exception): ...

class OrtAllocatorType:
    __members__: ClassVar[dict] = ...  # read-only
    INVALID: ClassVar[OrtAllocatorType] = ...
    ORT_ARENA_ALLOCATOR: ClassVar[OrtAllocatorType] = ...
    ORT_DEVICE_ALLOCATOR: ClassVar[OrtAllocatorType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OrtArenaCfg:
    arena_extend_strategy: int
    initial_chunk_size_bytes: int
    initial_growth_chunk_size_bytes: int
    max_dead_bytes_per_chunk: int
    max_mem: int
    max_power_of_two_extend_bytes: int
    @overload
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex, arg3: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @overload
    def __init__(self, arg0: dict) -> None: ...

class OrtCompileApiFlags:
    __members__: ClassVar[dict] = ...  # read-only
    ERROR_IF_NO_NODES_COMPILED: ClassVar[OrtCompileApiFlags] = ...
    ERROR_IF_OUTPUT_FILE_EXISTS: ClassVar[OrtCompileApiFlags] = ...
    NONE: ClassVar[OrtCompileApiFlags] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OrtCompiledModelCompatibility:
    __members__: ClassVar[dict] = ...  # read-only
    EP_NOT_APPLICABLE: ClassVar[OrtCompiledModelCompatibility] = ...
    EP_SUPPORTED_OPTIMAL: ClassVar[OrtCompiledModelCompatibility] = ...
    EP_SUPPORTED_PREFER_RECOMPILATION: ClassVar[OrtCompiledModelCompatibility] = ...
    EP_UNSUPPORTED: ClassVar[OrtCompiledModelCompatibility] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OrtDevice:
    @overload
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex, arg3: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @overload
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @staticmethod
    def cann() -> int: ...
    @staticmethod
    def cpu() -> int: ...
    @staticmethod
    def cuda() -> int: ...
    @staticmethod
    def default_memory() -> int: ...
    def device_id(self) -> int: ...
    def device_type(self) -> int: ...
    @staticmethod
    def dml() -> int: ...
    @staticmethod
    def fpga() -> int: ...
    @staticmethod
    def gpu() -> int: ...
    def mem_type(self) -> int: ...
    @staticmethod
    def npu() -> int: ...
    def vendor_id(self) -> int: ...
    @staticmethod
    def webgpu() -> int: ...

class OrtDeviceMemoryType:
    __members__: ClassVar[dict] = ...  # read-only
    DEFAULT: ClassVar[OrtDeviceMemoryType] = ...
    HOST_ACCESSIBLE: ClassVar[OrtDeviceMemoryType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OrtEpAssignedNode:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def domain(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def op_type(self) -> str: ...

class OrtEpAssignedSubgraph:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_nodes(self) -> list[OrtEpAssignedNode]: ...
    @property
    def ep_name(self) -> str: ...

class OrtEpDevice:
    def __init__(self, *args, **kwargs) -> None: ...
    def create_sync_stream(self) -> OrtSyncStream: ...
    def memory_info(self, arg0: OrtDeviceMemoryType) -> OrtMemoryInfo: ...
    @property
    def device(self) -> OrtHardwareDevice: ...
    @property
    def ep_metadata(self) -> dict[str, str]: ...
    @property
    def ep_name(self) -> str: ...
    @property
    def ep_options(self) -> dict[str, str]: ...
    @property
    def ep_vendor(self) -> str: ...

class OrtExecutionProviderDevicePolicy:
    __members__: ClassVar[dict] = ...  # read-only
    DEFAULT: ClassVar[OrtExecutionProviderDevicePolicy] = ...
    MAX_EFFICIENCY: ClassVar[OrtExecutionProviderDevicePolicy] = ...
    MAX_PERFORMANCE: ClassVar[OrtExecutionProviderDevicePolicy] = ...
    MIN_OVERALL_POWER: ClassVar[OrtExecutionProviderDevicePolicy] = ...
    PREFER_CPU: ClassVar[OrtExecutionProviderDevicePolicy] = ...
    PREFER_GPU: ClassVar[OrtExecutionProviderDevicePolicy] = ...
    PREFER_NPU: ClassVar[OrtExecutionProviderDevicePolicy] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OrtExternalInitializerInfo:
    def __init__(self, arg0: str, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def byte_size(self) -> int: ...
    @property
    def file_offset(self) -> int: ...
    @property
    def filepath(self) -> str: ...

class OrtHardwareDevice:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def device_id(self) -> int: ...
    @property
    def metadata(self) -> dict[str, str]: ...
    @property
    def type(self) -> OrtHardwareDeviceType: ...
    @property
    def vendor(self) -> str: ...
    @property
    def vendor_id(self) -> int: ...

class OrtHardwareDeviceType:
    __members__: ClassVar[dict] = ...  # read-only
    CPU: ClassVar[OrtHardwareDeviceType] = ...
    GPU: ClassVar[OrtHardwareDeviceType] = ...
    NPU: ClassVar[OrtHardwareDeviceType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OrtMemType:
    __members__: ClassVar[dict] = ...  # read-only
    CPU: ClassVar[OrtMemType] = ...
    CPU_INPUT: ClassVar[OrtMemType] = ...
    CPU_OUTPUT: ClassVar[OrtMemType] = ...
    DEFAULT: ClassVar[OrtMemType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OrtMemoryInfo:
    def __init__(self, arg0: str, arg1: OrtAllocatorType, arg2: typing.SupportsInt | typing.SupportsIndex, arg3: OrtMemType) -> None: ...
    @staticmethod
    def create_v2(arg0: str, arg1: OrtMemoryInfoDeviceType, arg2: typing.SupportsInt | typing.SupportsIndex, arg3: typing.SupportsInt | typing.SupportsIndex, arg4: OrtDeviceMemoryType, arg5: typing.SupportsInt | typing.SupportsIndex, arg6: OrtAllocatorType) -> OrtMemoryInfo: ...
    @property
    def allocator_type(self) -> OrtAllocatorType: ...
    @property
    def device_id(self) -> int: ...
    @property
    def device_mem_type(self) -> OrtDeviceMemoryType: ...
    @property
    def device_vendor_id(self) -> int: ...
    @property
    def mem_type(self) -> OrtMemType: ...
    @property
    def name(self) -> str: ...

class OrtMemoryInfoDeviceType:
    __members__: ClassVar[dict] = ...  # read-only
    CPU: ClassVar[OrtMemoryInfoDeviceType] = ...
    FPGA: ClassVar[OrtMemoryInfoDeviceType] = ...
    GPU: ClassVar[OrtMemoryInfoDeviceType] = ...
    NPU: ClassVar[OrtMemoryInfoDeviceType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OrtSparseFormat:
    __members__: ClassVar[dict] = ...  # read-only
    ORT_SPARSE_BLOCK_SPARSE: ClassVar[OrtSparseFormat] = ...
    ORT_SPARSE_COO: ClassVar[OrtSparseFormat] = ...
    ORT_SPARSE_CSRC: ClassVar[OrtSparseFormat] = ...
    ORT_SPARSE_UNDEFINED: ClassVar[OrtSparseFormat] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OrtSyncStream:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_handle(self) -> int: ...

class OrtValue:
    def __init__(self, *args, **kwargs) -> None: ...
    def as_sparse_tensor(self, *args, **kwargs): ...
    def data_ptr(self) -> int: ...
    def data_type(self) -> str: ...
    def device_name(self) -> str: ...
    def element_type(self) -> int: ...
    @staticmethod
    def from_dlpack(data: object, is_bool_tensor: bool = ...) -> OrtValue: ...
    def has_value(self) -> bool: ...
    def is_sparse_tensor(self) -> bool: ...
    def is_tensor(self) -> bool: ...
    def is_tensor_sequence(self) -> bool: ...
    def numpy(self) -> object: ...
    @staticmethod
    def ort_value_from_sparse_tensor(arg0) -> OrtValue: ...
    @staticmethod
    def ortvalue_from_numpy(arg0: object, arg1: OrtDevice) -> OrtValue: ...
    @staticmethod
    def ortvalue_from_numpy_with_onnx_type(arg0: numpy.ndarray, arg1: typing.SupportsInt | typing.SupportsIndex) -> OrtValue: ...
    @staticmethod
    def ortvalue_from_shape_and_onnx_type(arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: typing.SupportsInt | typing.SupportsIndex, arg2: OrtDevice) -> OrtValue: ...
    @staticmethod
    def ortvalue_from_shape_and_type(arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: object, arg2: OrtDevice) -> OrtValue: ...
    def shape(self) -> list: ...
    def tensor_size_in_bytes(self) -> int: ...
    def to_dlpack(self) -> object: ...
    def update_inplace(self, arg0: numpy.ndarray) -> None: ...
    def __dlpack__(self, stream: object = ...) -> object: ...
    def __dlpack_device__(self) -> tuple: ...

class OrtValueVector:
    def __init__(self) -> None: ...
    def bool_tensor_indices(self) -> list[int]: ...
    def dlpack_at(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> object: ...
    def element_type_at(self, idx: typing.SupportsInt | typing.SupportsIndex) -> int: ...
    @overload
    def push_back(self, arg0: OrtValue) -> None: ...
    @overload
    def push_back(self, dlpack_tensor: object, is_bool_tensor: bool = ...) -> None: ...
    def push_back_batch(self, arg0: collections.abc.Sequence[object], arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg2: collections.abc.Sequence[object], arg3: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], arg4: collections.abc.Sequence[OrtDevice]) -> None: ...
    def reserve(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def shrink_to_fit(self) -> None: ...
    def to_dlpacks(self, to_tensor: object) -> list: ...
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> OrtValue: ...
    def __iter__(self) -> collections.abc.Iterator[OrtValue]: ...
    def __len__(self) -> int: ...

class RunOptions:
    log_severity_level: int
    log_verbosity_level: int
    logid: str
    only_execute_path_to_fetches: bool
    terminate: bool
    def __init__(self) -> None: ...
    def add_active_adapter(self, arg0) -> None: ...
    def add_run_config_entry(self, arg0: str, arg1: str) -> None: ...
    def get_run_config_entry(self, arg0: str) -> str: ...

class RuntimeException(Exception): ...

class SessionIOBinding:
    def __init__(self, arg0: InferenceSession) -> None: ...
    @overload
    def bind_input(self, arg0: str, arg1: object) -> None: ...
    @overload
    def bind_input(self, arg0: str, arg1: OrtDevice, arg2: typing.SupportsInt | typing.SupportsIndex, arg3: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg4: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @overload
    def bind_input(self, arg0: str, arg1: OrtDevice, arg2: object, arg3: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg4: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def bind_ortvalue_input(self, arg0: str, arg1: OrtValue) -> None: ...
    def bind_ortvalue_output(self, arg0: str, arg1: OrtValue) -> None: ...
    @overload
    def bind_output(self, arg0: str, arg1: OrtDevice, arg2: typing.SupportsInt | typing.SupportsIndex, arg3: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg4: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @overload
    def bind_output(self, arg0: str, arg1: OrtDevice, arg2: object, arg3: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg4: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @overload
    def bind_output(self, arg0: str, arg1: OrtDevice) -> None: ...
    def clear_binding_inputs(self) -> None: ...
    def clear_binding_outputs(self) -> None: ...
    def copy_outputs_to_cpu(self) -> list: ...
    def get_outputs(self) -> OrtValueVector: ...
    def synchronize_inputs(self) -> None: ...
    def synchronize_outputs(self) -> None: ...

class SessionObjectInitializer:
    def __init__(self, *args, **kwargs) -> None: ...

class SessionOptions:
    enable_cpu_mem_arena: bool
    enable_mem_pattern: bool
    enable_mem_reuse: bool
    enable_profiling: bool
    execution_mode: ExecutionMode
    execution_order: ExecutionOrder
    graph_optimization_level: GraphOptimizationLevel
    inter_op_num_threads: int
    intra_op_num_threads: int
    log_severity_level: int
    log_verbosity_level: int
    logid: str
    optimized_model_filepath: str
    profile_file_prefix: str
    use_deterministic_compute: bool
    use_per_session_threads: bool
    def __init__(self) -> None: ...
    def add_external_initializers(self, arg0: list, arg1: list) -> None: ...
    def add_external_initializers_from_files_in_memory(self, arg0: collections.abc.Sequence[str], arg1: collections.abc.Sequence[collections.abc.Buffer], arg2: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None: ...
    def add_free_dimension_override_by_denotation(self, arg0: str, arg1: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def add_free_dimension_override_by_name(self, arg0: str, arg1: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def add_initializer(self, arg0: str, arg1: object) -> None: ...
    def add_provider(self, arg0: str, arg1: collections.abc.Mapping[str, str]) -> None: ...
    def add_provider_for_devices(self, arg0: collections.abc.Sequence[OrtEpDevice], arg1: collections.abc.Mapping[str, str]) -> None: ...
    def add_session_config_entry(self, arg0: str, arg1: str) -> None: ...
    def get_session_config_entry(self, arg0: str) -> str: ...
    def has_providers(self) -> bool: ...
    def register_custom_ops_library(self, arg0: str) -> None: ...
    def set_load_cancellation_flag(self, arg0: bool) -> None: ...
    def set_provider_selection_policy(self, arg0: OrtExecutionProviderDevicePolicy) -> None: ...
    def set_provider_selection_policy_delegate(self, arg0: collections.abc.Callable[[collections.abc.Sequence[OrtEpDevice], collections.abc.Mapping[str, str], collections.abc.Mapping[str, str], typing.SupportsInt | typing.SupportsIndex], list[OrtEpDevice]]) -> None: ...

class SparseBlockSparseView:
    def __init__(self, *args, **kwargs) -> None: ...
    def indices(self) -> numpy.ndarray: ...

class SparseCooView:
    def __init__(self, *args, **kwargs) -> None: ...
    def indices(self) -> numpy.ndarray: ...

class SparseCsrView:
    def __init__(self, *args, **kwargs) -> None: ...
    def inner(self) -> numpy.ndarray: ...
    def outer(self) -> numpy.ndarray: ...

class SparseTensor:
    format: OrtSparseFormat
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def blocksparse_from_numpy(arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: numpy.ndarray, arg2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], arg3: OrtDevice) -> SparseTensor: ...
    def data_type(self) -> str: ...
    def dense_shape(self) -> list: ...
    def device_name(self) -> str: ...
    def get_blocksparse_data(self) -> SparseBlockSparseView: ...
    def get_coo_data(self) -> SparseCooView: ...
    def get_csrc_data(self) -> SparseCsrView: ...
    @staticmethod
    def sparse_coo_from_numpy(arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: numpy.ndarray, arg2: typing.Annotated[numpy.typing.ArrayLike, numpy.int64], arg3: OrtDevice) -> SparseTensor: ...
    @staticmethod
    def sparse_csr_from_numpy(arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: numpy.ndarray, arg2: typing.Annotated[numpy.typing.ArrayLike, numpy.int64], arg3: typing.Annotated[numpy.typing.ArrayLike, numpy.int64], arg4: OrtDevice) -> SparseTensor: ...
    def to_cuda(self, arg0: OrtDevice) -> SparseTensor: ...
    def values(self) -> numpy.ndarray: ...

def copy_tensors(arg0: collections.abc.Sequence[OrtValue], arg1: collections.abc.Sequence[OrtValue], arg2: object) -> None: ...
def create_and_register_allocator(arg0: OrtMemoryInfo, arg1: OrtArenaCfg) -> None: ...
def create_and_register_allocator_v2(arg0: str, arg1: OrtMemoryInfo, arg2: collections.abc.Mapping[str, str], arg3: OrtArenaCfg) -> None: ...
def disable_telemetry_events() -> None: ...
def enable_telemetry_events() -> None: ...
def get_all_operator_schema(*args, **kwargs): ...
def get_all_opkernel_def(*args, **kwargs): ...
def get_all_providers() -> list[str]: ...
def get_available_providers() -> list[str]: ...
def get_build_info() -> str: ...
def get_default_session_options(*args, **kwargs): ...
def get_device() -> str: ...
def get_ep_devices() -> list[OrtEpDevice]: ...
def get_model_compatibility_for_ep_devices(arg0: collections.abc.Sequence[OrtEpDevice], arg1: str) -> OrtCompiledModelCompatibility: ...
def get_session_initializer(*args, **kwargs): ...
def get_version_string() -> str: ...
def has_collective_ops() -> bool: ...
def is_dlpack_uint8_tensor(arg0: typing_extensions.CapsuleType) -> bool: ...
@overload
def quantize_matmul_2bits(arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], arg2: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], arg3: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg4: typing.SupportsInt | typing.SupportsIndex, arg5: typing.SupportsInt | typing.SupportsIndex, arg6: typing.SupportsInt | typing.SupportsIndex, arg7: bool) -> None: ...
@overload
def quantize_matmul_2bits(arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg1: typing.Annotated[numpy.typing.ArrayLike, float16], arg2: typing.Annotated[numpy.typing.ArrayLike, float16], arg3: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg4: typing.SupportsInt | typing.SupportsIndex, arg5: typing.SupportsInt | typing.SupportsIndex, arg6: typing.SupportsInt | typing.SupportsIndex, arg7: bool) -> None: ...
@overload
def quantize_matmul_4bits(arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], arg2: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], arg3: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg4: typing.SupportsInt | typing.SupportsIndex, arg5: typing.SupportsInt | typing.SupportsIndex, arg6: typing.SupportsInt | typing.SupportsIndex, arg7: bool) -> None: ...
@overload
def quantize_matmul_4bits(arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg1: typing.Annotated[numpy.typing.ArrayLike, float16], arg2: typing.Annotated[numpy.typing.ArrayLike, float16], arg3: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg4: typing.SupportsInt | typing.SupportsIndex, arg5: typing.SupportsInt | typing.SupportsIndex, arg6: typing.SupportsInt | typing.SupportsIndex, arg7: bool) -> None: ...
@overload
def quantize_matmul_8bits(arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], arg2: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], arg3: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg4: typing.SupportsInt | typing.SupportsIndex, arg5: typing.SupportsInt | typing.SupportsIndex, arg6: typing.SupportsInt | typing.SupportsIndex, arg7: bool) -> None: ...
@overload
def quantize_matmul_8bits(arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg1: typing.Annotated[numpy.typing.ArrayLike, float16], arg2: typing.Annotated[numpy.typing.ArrayLike, float16], arg3: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg4: typing.SupportsInt | typing.SupportsIndex, arg5: typing.SupportsInt | typing.SupportsIndex, arg6: typing.SupportsInt | typing.SupportsIndex, arg7: bool) -> None: ...
@overload
def quantize_matmul_bnb4(arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], arg2: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], arg3: typing.SupportsInt | typing.SupportsIndex, arg4: typing.SupportsInt | typing.SupportsIndex, arg5: typing.SupportsInt | typing.SupportsIndex, arg6: typing.SupportsInt | typing.SupportsIndex) -> None: ...
@overload
def quantize_matmul_bnb4(arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg1: typing.Annotated[numpy.typing.ArrayLike, float16], arg2: typing.Annotated[numpy.typing.ArrayLike, float16], arg3: typing.SupportsInt | typing.SupportsIndex, arg4: typing.SupportsInt | typing.SupportsIndex, arg5: typing.SupportsInt | typing.SupportsIndex, arg6: typing.SupportsInt | typing.SupportsIndex) -> None: ...
@overload
def quantize_qdq_matmul_2bits(arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], arg2: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], arg3: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg4: typing.SupportsInt | typing.SupportsIndex, arg5: typing.SupportsInt | typing.SupportsIndex, arg6: typing.SupportsInt | typing.SupportsIndex, arg7: bool) -> bool: ...
@overload
def quantize_qdq_matmul_2bits(arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg1: typing.Annotated[numpy.typing.ArrayLike, float16], arg2: typing.Annotated[numpy.typing.ArrayLike, float16], arg3: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg4: typing.SupportsInt | typing.SupportsIndex, arg5: typing.SupportsInt | typing.SupportsIndex, arg6: typing.SupportsInt | typing.SupportsIndex, arg7: bool) -> bool: ...
@overload
def quantize_qdq_matmul_4bits(arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], arg2: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], arg3: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg4: typing.SupportsInt | typing.SupportsIndex, arg5: typing.SupportsInt | typing.SupportsIndex, arg6: typing.SupportsInt | typing.SupportsIndex, arg7: bool) -> bool: ...
@overload
def quantize_qdq_matmul_4bits(arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg1: typing.Annotated[numpy.typing.ArrayLike, float16], arg2: typing.Annotated[numpy.typing.ArrayLike, float16], arg3: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8], arg4: typing.SupportsInt | typing.SupportsIndex, arg5: typing.SupportsInt | typing.SupportsIndex, arg6: typing.SupportsInt | typing.SupportsIndex, arg7: bool) -> bool: ...
def register_execution_provider_library(arg0: str, arg1: str) -> None: ...
def register_tensorrt_plugins_as_custom_ops(arg0, arg1: collections.abc.Mapping[str, str]) -> None: ...
def set_arena_extend_strategy(arg0) -> None: ...
def set_cuda_device_id(arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
def set_cudnn_conv_algo_search(arg0: OrtCudnnConvAlgoSearch) -> None: ...
def set_default_logger_severity(arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
def set_default_logger_verbosity(arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
def set_do_copy_in_default_stream(arg0: bool) -> None: ...
def set_global_thread_pool_sizes(intra_op_num_threads: typing.SupportsInt | typing.SupportsIndex = ..., inter_op_num_threads: typing.SupportsInt | typing.SupportsIndex = ...) -> None: ...
def set_gpu_mem_limit(arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
def set_seed(arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
def unregister_execution_provider_library(arg0: str) -> None: ...
